### ISSUE TITLE
Cannot send libusb_control_transfer with zero wLength for libusb0.sys

### ISSUE THREAD

**Issue by martinmikula** [libusb/libusb#1006]
Hi all,

I'm trying to send libusb_control_transfer with zero wLength and the ret is always LIBUSB_ERROR_IO. I found this problem when trying dfu-util. Also official release and also my code works the same. At first i thought that the problem is with device, but after a hours of debugging it seems that libusb simply doesn't send the request.

Problematic code example:
```
ret = dfu_download(dif->dev_handle, dif->interface, 0, transaction, NULL);
if (ret < 0) {
	warnx("Error sending completion packet (%s)", libusb_error_name(ret));
}

int dfu_download( libusb_device_handle *device, const unsigned short interface, const unsigned short length, const unsigned short transaction, unsigned char* data ) {
    int status;
    status = libusb_control_transfer( device,
          /* bmRequestType */ LIBUSB_ENDPOINT_OUT | LIBUSB_REQUEST_TYPE_CLASS | LIBUSB_RECIPIENT_INTERFACE,
          /* bRequest      */ DFU_DNLOAD,
          /* wValue        */ transaction,
          /* wIndex        */ interface,
          /* Data          */ data,
          /* wLength       */ length,
         dfu_timeout );
    return status;
}
```

I will attach the complete output, but the most important logs for the problematic call are:
```
[ 0.327512] [00003eac] libusb: debug [libusb_alloc_transfer] transfer 015A04F0
[ 0.329209] [00003eac] libusb: debug [libusb_submit_transfer] transfer 015A04F0
[ 0.330315] [00003eac] libusb: debug [usbi_add_pollfd] add fd 2 events 4
[ 0.332199] [00003eac] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 0.333191] [00003eac] libusb: warning [winusbx_submit_control_transfer] ControlTransfer failed: [87] The parameter is incorrect.
[ 0.334193] [00003eac] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 0.336582] [00003eac] libusb: debug [libusb_free_transfer] transfer 015A04F0
Error sending completion packet (LIBUSB_ERROR_IO)
```

I'm using Win10 32bit version of application, libusb0.sys driver:
![image](https://user-images.githubusercontent.com/14890222/136183820-d69a6738-b4b0-4c18-83c2-540165f1a52a.png)
Version of the libusb is 1.0.23, because it seems that version 1.0.24 is not working with that driver at all :( I'm getting a lot of access violation exceptions. 

Any ideas what can be wrong? Or I'm doing something wrong? But also according DFU specification, the last request should be with the zero length data:
![image](https://user-images.githubusercontent.com/14890222/136184441-42cea0ed-a8e3-4984-a5ac-1556219931a1.png)

Complete log of application with LIBUSB_DEBUG=4:
[output.log](https://github.com/libusb/libusb/files/7292815/output.log)

Thanks for any help. If some information is missing i will provide it ASAP... :)

**Comment by tormodvolden** [comment]
Does it work fine with the WinUSB driver?

**Comment by martinmikula** [comment]
Hi,

yes, with WinUSB driver it works perfectly. I didn't test version 1.0.24 but version 1.0.23 works fine... So it looks like the problem is only somewhere in libusbk code... But unfortunately i'm not very familiar with this library yet... :( If I can help somehow, to test with some special version or something, please let me know...

```
Opening DFU capable USB device...
Device ID 0be5:dead
Device DFU version 0110
Claiming USB DFU Interface...
Setting Alternate Interface #1 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 0110
Device returned transfer size 2048
Copying data from PC to DFU device
Download        [=========================] 100%        33104 bytes
Download done.
DFU state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Resetting USB to switch back to runtime mode
Done!
```

**Comment by mcuee** [comment]
Do not use libusb0.sys as it is not working well. It is broken in 1.0.24 and git.
https://github.com/libusb/libusb/issues/761#issuecomment-906049400
> git head is okay with WinUSB and libusbk driver, but not libusb0.sys (libusb-win32 device driver).
> 1.024 is okay with WinUSB but not libusbk driver and libusb0.sys (libusb-win32 device driver).

**Comment by mcuee** [comment]
@martinmikula When you got the time, please try the following.
1) using libusb-1.0.23, and use Zadig 2.6 to upgrade to libusbk.dll 3.1.0.0 to see if the issue goes away, as per the comments by Tormod
https://github.com/libusb/libusb/issues/1006#issuecomment-942135499

2) using libusb-1.0.23, use Zadig snapshot to install libusb0.sys 1.2.7.2 snapshot version to see if there is any issues.

3) If you have some time, please help to test libusb git as well with the following pull-request. libusb-1.024 may have some problems with libusb0.sys.
- https://github.com/libusb/libusb/pull/1016

**Comment by mcuee** [comment]
For Info: libusb-win32 1.2.7.3 snap release is actually signed and should work for Windows 7 and above.
Ref: https://github.com/mcuee/libusb-win32/issues/24

**Comment by mcuee** [comment]
Since this is not a libusb issue but rather libusb0.sys issue, I will close it now.

**Comment by mcuee** [comment]
Wiki FAQ updated.
https://github.com/libusb/libusb/wiki/Windows#known-restrictions
libusb0.sys: cannot send libusb_control_transfer with zero wLength with libusb0.sys 1.2.6.0 version. Please use libusb0.sys 1.2.7.3 snapshot release or later.
