### ISSUE TITLE
How to extract as depends/libusb

### ISSUE THREAD

**Issue by Tavagero** [libusb/libusb#1022]
Sorry to bothr you with such stupid question, but I havn't any experience with github. I want to try a project that require your project:
"Download the latest build (.7z file) from https://github.com/libusb/libusb/releases, and extract as depends/libusb (rename folder libusb-1.x.y to libusb if any)." 
I downloaded your project and extracted it, but I don't know how to do this as depends. Do I need to start the project in Visual Studio, because I don't see any way to start it or I need to create somehow project in VS with your project?

**Comment by tormodvolden** [comment]
It would be useful if you link to the location where those instructions are, but I guess "depends" is a file directory that already exists, or you create it in the root of the other project.

**Comment by Tavagero** [comment]
https://github.com/OpenKinect/libfreenect2/blob/master/README.md#windows--visual-studio

**Comment by tormodvolden** [comment]
It is a pre-existing folder: https://github.com/OpenKinect/libfreenect2/tree/master/depends

**Comment by Tavagero** [comment]
Thank you
