### ISSUE TITLE
Does libusb not support hot plug detection on windows platform?

### ISSUE THREAD

**Issue by arilink** [libusb/libusb#1028]
I tried to use libusb to get USB hot-plug events on the windows platform, but it doesn’t seem to be supported. Is there any other way to get hot-plug events under the windows platform?

**Comment by mcuee** [comment]
This is an existing issue.
- https://github.com/libusb/libusb/issues/86

**Comment by mcuee** [comment]
Please read the comments n #86 and ask there. I will close this issue as it is a duplicate.
