### ISSUE TITLE
hotplug notifiers not called when using pollfd_notifiers

### ISSUE THREAD

**Issue by laf0rge** [libusb/libusb#1055]
I've been trying to get hotplug notifiers to work in my application for the better part of the day, but I'm unable to get any of them.  I've been stepping through gdb and I can see that the notifier thread gets the netlink and udev notifications and it sets the USBI_EVENT_HOTPLUG_MSG_PENDING flag, but the main thread never gets notified/woken up about this.

I tried to build an as-simple-as-possible reproducer, and I am attaching a modified hotplugtest.c to this issue.

Despite calling libusb_set_pollfd_notifiers(), libusb never calls  the osmo_usb_added_cb call-back, i.e. it fails to register any file descriptor.   As a result, it is obvious that the main thread cannot be notified about hotplug events.

Is this intentional?  Did I msis some kind of API documentation about hotplug notifications not being supported with pollfd notifiers? 
[hotplugtest-pollfd.tar.gz](https://github.com/libusb/libusb/files/7972791/hotplugtest-pollfd.tar.gz)

**Comment by benzea** [comment]
Right, this is a bug in the user code and it is documented correctly in `libusb_set_pollfd_notifiers`:

> Note that file descriptors may have been added even before you register these notifiers (e.g. at [libusb_init()](https://libusb.sourceforge.io/api-1.0/group__libusb__lib.html#ga7deaef521cfb1a5b3f8d6c01be11a795) time).

i.e. you need to use `libusb_get_pollfds` once.

**Comment by mcuee** [comment]
Close this then.
