### ISSUE TITLE
 Libtool library used but 'LIBTOOL' is undefined

### ISSUE THREAD

**Issue by hellisabove** [libusb/libusb#1066]
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
libusb/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
libusb/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libusb/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libusb/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
libusb/Makefile.am:6:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

**Comment by mcuee** [comment]
I think you already know the answer. You need to install libtool package.
