### ISSUE TITLE
darwin: clock_gettime usage is not guarded by HAVE_CLOCK_GETTIME

### ISSUE THREAD

**Issue by parafin** [libusb/libusb#1070]
PR #1035 (commit c1ed5895438f2ae3767162f74388b09a16ab0800) introduced into os/darwin_usb.c a clock_gettime usage which is not guarded by HAVE_CLOCK_GETTIME. This breaks compatibility with older macOS versions (see bug #836 for reference). This has to either be fixed or support for macOS <10.12 officially dropped.

**Comment by mcuee** [comment]
Please help to create a pull request to fix the issue. Thanks for the help.

**Comment by hjelmn** [comment]
Will drop support without a PR. 10.11 is 6 yeas old. I do not plan to support that old an OS but happy to take a PR to fix.

**Comment by parafin** [comment]
I'm fine with dropping support, I won't do a PR to fix this myself, but maybe author of original PR (@agoodney) wants to do it. On the other hand there are ways to workaround this problem, e.g. see https://github.com/macports/macports-legacy-support

I would suggest to explicitly mention that macOS <10.12 is not supported (maybe in release notes?) if you are to go this way.

**Comment by hjelmn** [comment]
Unfortunately not. Documentation says it is available from 10.12+

Looks like we still have code for older releases. See:

https://github.com/libusb/libusb/blob/master/libusb/os/darwin_usb.c#L2336

Probably should just use those functions to fix the issue. I plan to clean them out at the point when we definitely will not support 10.11 and earlier.

**Comment by agoodney** [comment]
To confirm: usbi_get_monotonic_time() needs to be guarded in darwin_reenumerate_device() with HAVE_CLOCK_GETTIME.

Should I make this work an update to my previous closed PR, or start a new PR?

**Comment by tormodvolden** [comment]
@agoodney Thanks a lot for working on this. I think a new PR makes sense.

Just want to chime in with what I saw when building on older macOS, as mentioned in https://github.com/libusb/libusb/pull/1056#issuecomment-1030634488
`checking whether OS X target version is 10.12 or later... yes`
when building on 10.4.11 - I wonder if something is wrong about that check (maybe only for really old macos).

**Comment by agoodney** [comment]
Should I do this against libusb/libusb or against tormodvolden/libusb?

libusb/libusb doesn't have the tweaks you did to clean up my PR, e.g: 

#define DARWIN_REENUMERATE_TIMEOUT_US (10 * USEC_PER_SEC)

**Comment by tormodvolden** [comment]
Yes, against my branch in #1056 would be good, because that one is queued up for inclusion.

**Comment by seanm** [comment]
I was just upgrading to libusb 1.0.25 and ran into this issue.  I still need old macOS support so can help with a patch or testing.

Another API you could maybe use is `mach_absolute_time()`, it has existed forever.

**Comment by tormodvolden** [comment]
Isn't it as straight-forward as just using usbi_get_monotonic_time(), i.e. never use clock_gettime() directly?

**Comment by seanm** [comment]
Yes, seems like it to me.  The usual pattern for such things is to create your own wrapper function then implement it per-platform.

**Comment by agoodney** [comment]
So move clock_gettime() inside usbi_get_monotonic() time? Yes, that makes more sense.

**Comment by seanm** [comment]
If no one has started a patch for this, I could do it...

**Comment by tormodvolden** [comment]
@agoodney , usbi_get_monotonic() uses clock_gettime() if it is available.

I added this to my PR #1056 . Testing on old and new macOS is welcome.

**Comment by agoodney** [comment]
I must not have pulled the latest version of your branch or something because I didn't see clock_gettime() inside of usbi_get_monotonic().

I'll update my work to just call usbi_get_monotonic()

**Comment by tormodvolden** [comment]
@agoodney No, I didn't modify usbi_get_monotonic. You don't need to update it, I have added it to #1056 already.

**Comment by seanm** [comment]
The fallback code for old macOS seems unnecessarily complex... I think I'll whip up a PR to complement your work @tormodvolden ...

**Comment by seanm** [comment]
>Ok, I updated my PR against your https://github.com/libusb/libusb/pull/1056 so it calls usbi_get_monotoic_time()

Which PR? Link?

**Comment by agoodney** [comment]
My PR is against this branch 

https://github.com/tormodvolden/libusb/tree/get_endpoints_IfV550

**Comment by tormodvolden** [comment]
@agoodney Sorry, I didn't see you had already started working on it, I didn't get any notification. Your PR is anyway against an outdated HEAD of my branch. For future situations like this, it is better to file the PR on the main libusb project, which also doesn't prevent you from including the commits from someone else's branch.

**Comment by agoodney** [comment]
Do you need me to do anything at this point?

Thanks for the git advice. I've still got a lot to learn about git collaboration on big, public projects like this.

**Comment by tormodvolden** [comment]
> The fallback code for old macOS seems unnecessarily complex... I think I'll whip up a PR to complement your work @tormodvolden ...

It does look overly complex at first sight, but after reading #836 I get the impression it is not trivial either. But please let us know if it can be simplified.

**Comment by tormodvolden** [comment]
@agoodney If you can do any testing of #1056 on older macOS that would be great. Thanks for your contribution and no worries about the PR confusion, it was more of a GitHub workflow issue than a git issue, their features are usually helpful but sometimes things go through the cracks. And it got unusually busy here after the release. It was dead quiet during 10 days of RC, you might wonder if people actually test them...

@seanm and @parafin We tested macOS back to 10.12 during our RC testing #1046. I'll ping you about older versions next time :)

**Comment by seanm** [comment]
>It was dead quiet during 10 days of RC, you might wonder if people actually test them...

In a company environment (where I use libusb), the next 10 days are often booked solid.  I didn't have a chance to try the RCs beforehand alas.

I take a stab at it and share my PR here...

**Comment by seanm** [comment]
Here is a draft: https://github.com/libusb/libusb/pull/1080

**Comment by parafin** [comment]
> @seanm and @parafin We tested macOS back to 10.12 during our RC testing #1046. I'll ping you about older versions next time :)

Thanx for the offer:) Sadly I don't really have a way to test things on old macOS versions. I noticed this regression thanks to macports guys, see here: https://github.com/macports/macports-ports/pull/13868
Previous clock_gettime issue was reported to darktable bug tracker by a user, so again not caught by me, but just forwarded to you (with analysis).

**Comment by agoodney** [comment]
@tormodvolden I can now build/test on MacOS 10.5, so when you have an RC for 1.0.26 I'll test it there.

**Comment by hjelmn** [comment]
Weird. c11 support should work fine with older targets. I can take a look.

**Comment by hjelmn** [comment]
Ah. I see. No thread local on 10.5.  Guess 10.5 support is dead then.

**Comment by agoodney** [comment]
I was able to build 1.0.25 on a 10.5 VM, I'll check this RC

**Comment by agoodney** [comment]
I was able to build libusb/master on a 10.5 VM, caveat is that I have MacPorts installed clang v7.1.0

The latest Apple supplied Xcode for 10.5 is using gcc 4.0.1, so I don't think non-MacPort builds have worked for awhile.

I'll see if I can get a 10.6 VM up and running.

I'm willing to help out with things like this, is there a better place for dev chat? Slack? IRC?

**Comment by seanm** [comment]
Does it work to build with Xcode 8 + macOS 10.11.5 but set the deployment target to be older?

**Comment by agoodney** [comment]
I'll check, I had to install pkg-config (see #1096) and there is a missing #define on 10.11.5 I'm still tracking down.

**Comment by seanm** [comment]
>and there is a missing #define on 10.11.5 I'm still tracking down

I just built git master on macOS 10.10.5 with Xcode 7.2.1, didn't see any missing define...

**Comment by agoodney** [comment]
I'll start a new issue for it

**Comment by tormodvolden** [comment]
@seanm @parafin @agoodney The RC is out :) Please add tested platforms and applications to #1099.
