### ISSUE TITLE
Control Transfer (or sync transfer) and Async Transfer(s) simultaneously

### ISSUE THREAD

**Issue by sonatique** [libusb/libusb#1076]
Hello,
This is maybe more a question than an issue, thank you for redirecting me elsewhere is there is a better place to ask.

I am encountering the followin issue: 
- I submit several "in" async bulk transfer, resubmitting them when they complete from inside the transfer callback
- I use a single thread to continuously call libsub_handle_events_timeout (let's call it "event thread")
- My code is therefore expecting all transfer callbacks to be processed by the event thread
- I would say that this code works pretty well in isolation, there are no know bugs to me in this code per se

While these async transfers are running and receiving data on a dedicated endpoint, I need to issue some ControlTransfers as well. For this purpose I naively use libusb_control_transfer.

The problem is that since libusb_control_transfer is internally impemented with async transfer and event handling, I suddenly have the random thread that called libusb_control_transfer doing the event handling for one of my async transfer, the result being that my async call back are sometimes executed by the "control tranfer thread" and not by the expected "event thread".

This cause various issues, including apparent disorder in the received chunks of data.

I am seeking advices about the general correct way of simultaneously having async transfers "in" while being able to issue ControlTransfer using libusb_control_transfer and avoid the above described threading problems.

Thansk a log in advance.

**Comment by diabolo38** [comment]
i used asssync bulk in with synch bulk out in the past (pre 1.0.22) and it was ok but using 

int API_EXPORTED libusb_handle_events_timeout_completed(libusb_context *ctx, 	struct timeval *tv, int *completed)

completed act as a mutex flag so  event processing doesn't hapen in a racy concurent way.
...
Their are doc on that subject may reading help 
https://libusb.sourceforge.io/api-1.0/libusb_mtasync.html

**Comment by sonatique** [comment]
thanks @diabolo38 . Actually, after further considering the case, I think there are no issue in libusb per se. It's just that when mixing "sync" calls and async transfers, one has to be prepared for having sync call threads executing async callbacks and the other way round. If no care is taken, this could lead to several different problems. I mean: after I realized it, it seemed obvious, but when first wrote my code, having the wroing impression I could handle all my async transfers in isolation, seeing this behavior was a surprise. And thusI had to rewrite some parts to take this into account.
