### ISSUE TITLE
1.0.25 Crashed when calling TRANSFER_CTX(transfer)

### ISSUE THREAD

**Issue by dspsir** [libusb/libusb#1081]
TRANSFER_CTX means transfer->dev_handle->xxxxxx. When transfer->dev_handle is equal to NULL, this Macro will cause crash. do_sync_bulk_transfer() in sync.c called libusb_free_transfer() is sufferring from this problem. Please fix it as soon as possible.

**Comment by benzea** [comment]
Duplicate, see https://github.com/libusb/libusb/issues/1079#issuecomment-1047489305

**Comment by mcuee** [comment]
@dspsir Yes, this is a duplicate. Please try the following two pull requests applied on top of 1.0.25 release. Thanks.

* https://github.com/libusb/libusb/pull/1058
* https://github.com/libusb/libusb/pull/1073

**Comment by tormodvolden** [comment]
This should be fixed in master now. Please reopen if the issue is not fixed.
