### ISSUE TITLE
libusb_bulk_transfer (read endpoint) works only with LIBUSB_LOG_LEVEL_DEBUG

### ISSUE THREAD

**Issue by njk42** [libusb/libusb#1118]
I am using libusb 1.0.25 (latest release) on Win10 to communicate with a USB device via the libusb-win32 v1.2.6 device driver.  I am calling libusb_bulk_transfer() to read 48 bytes on an input endpoint (i.e. read) but it's returning a timeout error status (-7).  

I originally suspected that this was an issue with my device hardware not responding; however, when attempting to get more debugging information by setting the log level to LIBUSB_LOG_LEVEL_**DEBUG**, the read transfers started working as expected.

When I'm using a console application and the debug messages are printed in the console, I cannot get the failure to occur with DEBUG log level, but it _always_ occurs with INFO, WARNING, and ERROR log levels.  However, when I compile my code into a library and call into that library using a GUI-based application (without a console to print the DEBUG messages) the read operation fails. 

Does this behavior make any sense to those experienced with libusb's logging functionality?  It seems strange that the ability to output debug log messages to a console would impact whether or not the bulk transfer succeeds.  Since I can't get the transfer to fail while also looking at the debug log messages, are there any other recommended ways to debug this?

Thanks in advance for your help!

**Comment by mcuee** [comment]
This looks like a timing issue with your hardware. LIBUSB_DEBUG=4 makes the things going slower.

**Comment by mcuee** [comment]
What I will suggest is to use a HW USB Analyzer to see what happens.

**Comment by mcuee** [comment]
If you do not have a USB analyzer, a software analyzer may help as well. Or you may want to try the free Microsoft solution (USB Event Tracing).
https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-event-tracing-for-windows

**Comment by mcuee** [comment]
You can also try to use WinUSB driver or libusbk driver to see if things are a bit better. The support of libusb0.sys is not as good as WinUSB or libusbk.

**Comment by njk42** [comment]
@mcuee  Thanks for your reply and assistance.  

I confirmed that the behavior is the same with the WinUSB driver, and it is actually _worse_ with libusbK:  the read operation times-out even with the DEBUG log level set.  I also tried the same connection pattern via LibUsbDotNet in a C# application and the transfer is always successful (using either the libusb-win32 or WinUSB driver).   

I suppose LibUsbDotNet could be inherently slower and thus fails to expose a timing issue in my hardware, whereas libusb (via WinUSB or libusb-win32) at logging levels _other than DEBUG_ is faster and thus exposes the issue, and finally libusb (via libusbK) is fastest even with DEBUG logging enabled and therefore is always sensitive to the issue.

I will try to interpret the DEBUG messages during failure which are available when using the libusbK driver, and also take your suggestions regarding the further probing of the USB traffic using a HW analyzer or event tracing.

**Comment by tormodvolden** [comment]
The slowness induced by DEBUG is mostly due to the Windows text console being slow. If you run with DEBUG but redirect the output to a file you may see the same behaviour as without DEBUG, e.g.
```
set LIBUSB_DEBUG=4
my_application > debug.log 2>&1
```

**Comment by mcuee** [comment]
I will close this issue for now. Please reopen when you have new info.
