### ISSUE TITLE
libusb_bulk_transfer return time out erro when write large data

### ISSUE THREAD

**Issue by tymoooo** [libusb/libusb#1120]
when i write lots of data user libusb_bulk_transfer,it always returns timeout at some point

Fake code like this

 ```
   while(1)
{
    if(src == NULL)
    {
        r = libusb_bulk_transfer(handle, endpoint, recvbuf, slen, rlen, 2000);
    }

    Sleep(20);
}
```

**Comment by diabolo38** [comment]
very likely the device  you read/write from/to  is not ready for  sending/Receving any more  data ^^ 
we don't see what is slen, rlen but if this is something not an endpoint  max packet size multiple  you can already  get bad side effect

**Comment by mcuee** [comment]
Close this for now. Please reopen if you have new info. Thanks.
