### ISSUE TITLE
1.0.26 unnecessary link with -latomic

### ISSUE THREAD

**Issue by abelbeck** [libusb/libusb#1135]
After cross-compiling 1.0.26 it unnecessarily links with `-latomic` which we don't include in our project.

x86_64-unknown-linux-gnu-gcc (crosstool-NG 1.24.0) 6.5.0

As a temporary fix, I removed this line in `configure.ac`:
```
AC_SEARCH_LIBS([__atomic_fetch_add_4], [atomic])
```
and `lsusb` works just fine.

This line got added here: https://github.com/libusb/libusb/commit/561dbdacfbcd8f26c81900d1a1a16d2f44093e0e

**Comment by mcuee** [comment]
The temporary fix is not really correct. Just wondering if you have a better fix? Maybe you can try to debug why the check in https://github.com/libusb/libusb/commit/561dbdacfbcd8f26c81900d1a1a16d2f44093e0e is not correct for your case.

**Comment by tormodvolden** [comment]
@ffontaine Does the suggested patch work on your (sparc) platforms?

**Comment by ffontaine** [comment]
Yes, the suggested patch work on sparc platforms.

**Comment by tormodvolden** [comment]
@abelbeck Can you please make a pull request?

**Comment by abelbeck** [comment]
@tormodvolden : PR #1139
