### ISSUE TITLE
deadlock with `libusb_release_interface` and `libusb_bulk_transfer`

### ISSUE THREAD

**Issue by timblechmann** [libusb/libusb#1143]
i've seen this deadlock:
* the main thread is calling `libusb_release_interface`
* my bulk reader thread is starting a new blocking read via `libusb_bulk_transfer`, but ends up deadlocked

makes me wonder if this is a user bug (where `libusb_bulk_transfer` is not supposed to be threadsafe in the first place) or if it's an issue in the blocking transfer API which can be fixed.

**Comment by mcuee** [comment]
I belive this is expected.

Ref: 
https://github.com/libusb/libusb/issues/703
https://github.com/libusb/libusb/issues/297#issuecomment-675762505

**Comment by timblechmann** [comment]
@mcuee thanks for the references!
