### ISSUE TITLE
Possible to open  and bulk transer to a device that is already open?

### ISSUE THREAD

**Issue by djnewty** [libusb/libusb#1145]
Hi,

I have a piece of closed source software which is communicating through libusb to a device.

I'm wondering is it possible to create another app/program with libusb and access this device while it is already being accessed by the other software?

Do I just need to find the device_handle and use that to libusb_open? If so, how difficult is it to find out the device_handle? Is this possible to do just in the app/prorgram I'm building using libusb?

**Comment by mcuee** [comment]
Reference:
https://github.com/libusb/libusb/wiki/Windows#known-restrictions
> WinUSB does not support multiple concurrent applications (as per the [Microsoft Windows Hardware Drivers documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-considerations)).
