### ISSUE TITLE
Re-licensing libusb

### ISSUE THREAD

**Issue by themarpe** [libusb/libusb#1148]
Disclaimer - this is coming from a "new user of libusb" perspective. I'm not up to date of any previous discussions on such topics, but mainly want to pass my thoughts on this.

With libusb gaining more traction and special branches being made for special purposes, relying on system libusb is often not an option. 
Also, some projects would benefit from having all of the dependencies built under their control.

Main idea is static linking - I see libusb be quite a candidate for this, especially on Windows platform as it reduces the hassle of dealing with DLLs for project which don't have mechanisms in place to deal with that.

So to integrate adoption of libusb as a "developer library" instead of "system library" which you use as is, I think having a more lax license would go a long way.

Idea/options: 
 1. Keep LGPLv2.1 and add static linking exception 
 2. Or MPLv2

I think both of these options keep the crux/main idea/goal of the current license - if you modify it, you have to bring back the changes - but it would reduce the current obligations on the source code that's consuming libusb. 

A bit of inspiration for this post is also ZeroMQ - which is already at LGPL+static linking exception, but they've decided to switch to MPLv2 if everyone will come onboard. (https://github.com/zeromq/libzmq/issues/2376)

I'm not sure on the scope of picking either 1. or 2., I assume its the same - get approval from everyone that contributed larger piece of work to libusb. But if in some way, option 1. doesn't require that large amount of effort, then that sounds like an easier choice.

Thoughts? Looking forward to discussion

**Comment by mcuee** [comment]
I believe this is very difficult if not impossible due to the number of contributors.

As libusb is shorts of maintainers, I believe will not have any motivations to entertain such efforts.

**Comment by mcuee** [comment]
I will close this issue in one month time if no other maintainers jumping in to support the idea.

**Comment by mcuee** [comment]
BTW, libusb projects are widely used by many organizations including big or small commercial companies. I have not heard such requests from any of them.

**Comment by themarpe** [comment]
> I believe this is very difficult if not impossible due to the number of contributors.
As libusb is shorts of maintainers, I believe will not have any motivations to entertain such requests.

Makes sense - I also think that adding static linking exception would be any simpler, so I do agree that there is a lot of work for small return to be had with this effort.

> BTW, libusb projects are widely used by many organizations including big or small commercial companies. I have not heard such requests from any of them.

I'd assume this is because of combination of it being used as system library + not having a cross platform (CMake/...) integration option for it to really be used a lot from developer perspective (find_package/add_subdirectory or some other simple mechanism). Note: this isn't a critique, is just the nature of current usage. If everyone who'd like to use libusb had to add it to their project in same manner as other libraries, then there would be many more people with a preference of just statically compiling everything together to eliminate the need for dealing with .so / .dll distribution for their simpler app / tool / etc...

> I will close this issue in two weeks time if no other maintainers jumping in to support the idea.

Got it - maybe it will serve as ground to some future debate around it:)

**Comment by pbatard** [comment]
I'm afraid I'm going to have to shut down this idea from the get go.

As one of the major contributors of the libusb Windows backend, I will not agree to relicense my code to a non (L)GPL derivative license or alter the terms of the current license in order to produce libusb-based software that I consider unfriendly to the freedoms that are guaranteed by the (L)GPL.

**Comment by mcuee** [comment]
@pbatard Thanks for jumping in.

I will close this issue now.
