### ISSUE TITLE
libuvc under MacOS 12 Monterey not working.

### ISSUE THREAD

**Issue by Alvazz** [libusb/libusb#1150]
Hi all, I wan use it on MacOS 12 Monterey, but can not working. I got some error -3 "access denied".

How can I fix it? Thanks.

**Comment by mcuee** [comment]
What is the device? Most likely the kernel driver has claimed exclusive access to the device.

For example, if your device is a UVC device like a USB camera and then you will face this issue. You can not use libusb (or libuvc) in this case.

**Comment by Alvazz** [comment]
Yes, device is a UVC device. If libuvc (libusb) is not suitable, which library should be used?

**Comment by mcuee** [comment]
> Yes, device is a UVC device. If libuvc (libusb) is not suitable, which library should be used?

Sorry I do not know. You can check out and ask here.
* https://github.com/libusb/libusb/issues/1014

**Comment by mcuee** [comment]
Ref: https://github.com/libusb/libusb/wiki/FAQ#how-can-i-run-libusb-applications-under-mac-os-x-if-there-is-already-a-kernel-extension-installed-for-the-device-and-claim-exclusive-access
> Please take note that command line apps cannot use provisioning profiles and therefore cannot hold this entitlement so you have to run as root. As for the GUI application, as of now APple support is saying that `com.apple.vm.device-access` entitlement is not the right entitlement. So basically there is no solution as of now. This means libusb (and libraries like libuvc which uses libusb) may not be the right library to use if you hit this issue (Issue #972 and Issue #1014).

**Comment by mcuee** [comment]
I will close this issue as it is out of control for libusb/libuvc.

**Comment by Alvazz** [comment]
OK, thanks!
