### ISSUE TITLE
How to open a device after libusb_handle_events

### ISSUE THREAD

**Issue by zundap1970** [libusb/libusb#1157]
Hi folks,

I use the "hotplugtest.c" example to detect when a USB is connected or disconnected.
libusb_handle_events API is blocking and return is case of connected\disconnected the device, now :

1.  How can discover which type of event ?
2. In case of device connection how to know which file under /dev/ should have to open? 
Thanks

**Comment by mcuee** [comment]
The question does not seem to be clear. Please state what you want to do. 
What do you mean by "libusb_handle_events API is blocking and return is case of connected\disconnected the device"?

**Comment by mcuee** [comment]
It seems to me libusb is not the right tool for you for your purpose, rather libudev may be the one.
