### ISSUE TITLE
how can I get a 64-bit arm libusb-1.0.so with cross-platform compile in x86_64-linux ?

### ISSUE THREAD

**Issue by Dangal2018** [libusb/libusb#1171]
Hi, 
I want to compile a 64-bit arm libusb-1.0.so,I read the configuration about install the libusb-1.0.26...
and my configuration option like this:
`
./configure --build=x86_64-linux --host=aarch64-linux --prefix=($pwd)/install CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ --disable-udev
sudo make && make install
`
successfully compile the libusb-1.0.so in my ./install/lib , I use
`
file libusb-1.0.so  
`
then I get the file message:

`
libusb-1.0.so: ELF 32-bit LSB shared object, ARM,EABI5 version 1(SYSV), dynamically linked ,BuildID[sha1]=blabla....,not stripped
`
I want to get ELF 64-bit LSB shared object ,ARM EABI5.......

How can I get a 64-bit arm libusb-1.0.so ?

**Comment by Dangal2018** [comment]
I serach my problems in Stackoverflow , and then I try to install libusb-1.0-0-dev:amd64 , and I find libusb-1.0.so.0.1.0 in my /usr/lib/x86_64-linux-gnu , but I execute the file command ,It shows

**Comment by mcuee** [comment]
Please use libusb-devel mailing list for technical support. Thanks. gitup is for issue report.
https://github.com/libusb/libusb/wiki#Support

**Comment by Dangal2018** [comment]
thanks. @mcuee 
and I solved ... 
just let the host=aarch64-linux-gnu,to be frankly,**It needs match the prefix of CC and C++ completely.**

**Comment by r4raatz** [comment]
Hi @Dangal2018, Can you please direct me to the solution since I'm also in need of libusb-1.0.so for my arm64-v8a android project?? even a plain .so file is fine for me or help me to build one??
