### ISSUE TITLE
How to solve the problem of returning error code -1 (Input/output error) when using control transmission when using libusb

### ISSUE THREAD

**Issue by Yao0828** [libusb/libusb#1176]
When I use libusb all the steps are done but I get an Input/output error when I transmit a 03 signal through the control transfer to control the Cap_Lock key of the keyboard?

**Comment by mcuee** [comment]
You have to state more details in order for others to help.
https://github.com/libusb/libusb/wiki/Troubleshooting

And take note github issues are more for issue reporting and not technical support.

**Comment by tormodvolden** [comment]
Isn't your keyboard claimed by an OS driver?

**Comment by mcuee** [comment]
Closed this issue for now.
