### ISSUE TITLE
Error claming Interface on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by greenscreenflicker** [libusb/libusb#1184]
I copied the following example.
https://raw.githubusercontent.com/tytouf/libusb-cdc-example/master/cdc_example.c

And i get the error: 
Error claiming interface: LIBUSB_ERROR_NOT_FOUND

Please advice how I can get this fixed.

Issue seems similar to #1153.

**Comment by tormodvolden** [comment]
https://github.com/libusb/libusb/wiki/Troubleshooting

**Comment by mcuee** [comment]
You have to set up the right permission and please do not open multiple github issues on the same question. I will close this one and you can ask further questions in https://github.com/libusb/libusb/issues/1185.

**Comment by mcuee** [comment]
@greenscreenflicker 

Please read the FAQ here as well.
https://github.com/libusb/libusb/wiki/FAQ#running-libusb
