### ISSUE TITLE
USB Control transfer retrieving interface descriptor (was #1180)

### ISSUE THREAD

**Issue by symdeb** [libusb/libusb#1204]
Continuing from #1180:

https://github.com/libusb/libusb/issues/1180
Looked at get_descriptor as an alternative. The desired request to make is: libusb_control_transfer(handle,0x81,0x06,0x2601,1,data,5,0);
How to do accomplish this with get_descriptor ?

    The bmRequest type is 0x81. Though get_descriptor always fixed it to 0x80
    The Index required is 1 (interface 1), but get_descriptor puts desc_index in the lower byte of wValue, thus wIndex is always 0
    wValue should be 0x26
    Example:
    libusb_get_descriptor(handle, 0x26, 2, data, 5 );
    The device receives:
    req->bmRequest:80 req->bRequest:06 req->wValue:2602 , req->wIndex:0000, req->wLength:0005
    This is different than what was desired.

**Comment by mcuee** [comment]
Please use libusb-devel mailing list for technical support. Thanks. This is more for reporting issues of libusb.
