### ISSUE TITLE
Parallel build is broken

### ISSUE THREAD

**Issue by mispix** [libusb/libusb#121]
When building latest libusb with "make -j 4", I'm getting:

...
Making all in libusb
make[2]: Entering directory `/home/mp/work/sigrok/libusb/libusb'
  CC       libusb_1_0_la-core.lo
  CC       libusb_1_0_la-descriptor.lo
  CC       libusb_1_0_la-io.lo
make[3]: Entering directory `/home/mp/work/sigrok/libusb/libusb'
  CC       libusb_1_0_la-core.lo
  CC       libusb_1_0_la-strerror.lo
  CC       libusb_1_0_la-sync.lo
  CC       libusb_1_0_la-descriptor.lo
mv: cannot stat ‘.deps/libusb_1_0_la-core.Tpo’: No such file or directory
make[2]: *** [libusb_1_0_la-core.lo] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by LudovicRousseau** [comment]
It is a known problem. But nobody proposed a solution yet.
see http://sourceforge.net/p/libusb/mailman/message/34456286/

**Comment by mcuee** [comment]
Chris posted the fix here. We also need Haiku users to test it though.
http://libusb.6.n5.nabble.com/libusb-PATCH-Misc-Simplify-Haiku-build-and-fix-broken-parallel-build-td5715358.html

**Comment by dickens** [comment]
I tested on Haiku and was able to build it and run listdevs in the examples.

>

**Comment by dickens** [comment]
Maybe @akshay1994 can confirm?

**Comment by LudovicRousseau** [comment]
@dickens I guess you also tested your patch on GNU/Linux?

I tried to extract you patch from the email to the list but it is not easy.
Do you have a git branch with your patch somewhere? or a Pull Request?

**Comment by dickens** [comment]
@LudovicRousseau Yes, I tested on GNU/Linux. I've attached the patch here, so hopefully it is easy to download.

[patch.txt](https://github.com/libusb/libusb/files/58809/patch.txt)

**Comment by LudovicRousseau** [comment]
The patch works for me. I propose to apply it.
