### ISSUE TITLE
How to set the baud rate and stop bit of the serial port through libusb on Android?

### ISSUE THREAD

**Issue by zhousongs** [libusb/libusb#1212]
How to set the baud rate and stop bit of the serial port through libusb on Android?
I can normally read USB HID device data through libusb.   However, when reading the data of the serial port device, an error "Input/Output Error" is reported.
After I connect the device on the JAVA layer, I use the JAVA code to set the baud rate, stop bit and other parameters.  I don't know the reason why reading and writing data are still unsuccessful. can you help me,what to do?

**Comment by mcuee** [comment]
libusb cannot be used for serial port device under Android. You should use different library.
