### ISSUE TITLE
Support ipados 16 DriverKit

### ISSUE THREAD

**Issue by colabi** [libusb/libusb#1214]
Now that ipados 16 supports user space driver development, it would be fantastic for libusb as a cross platform option to write drivers.

**Comment by mcuee** [comment]
Please elaborate what you want to achieve and how libusb can help. Thanks.

**Comment by mcuee** [comment]
I will close this for now. iPadOS is not supported as of now.

**Comment by mcuee** [comment]
I will reopen this when someone works out a way to support libusb on iPadOS without jailbreak.
