### ISSUE TITLE
libusb_init: Should not log warning for normal usage

### ISSUE THREAD

**Issue by photron** [libusb/libusb#1215]
Since commit 6b29aeb9ca22ed5ea9768020895698bd452c2a85 libusb_init logs a warning "installing new context as implicit default" when calling for a non-NULL libusb_context argument for the first time.

Why should this be a warning for perfectly good and normal usage? I think this should be lowered to debug level.

**Comment by mcuee** [comment]
@tormodvolden and @benzea
The above seems to be a good suggestion. Please check as well. Thanks.

**Comment by tormodvolden** [comment]
Yes, I also think this should be info/debug and not warning, and that it is meant as a "warning" for the programmer with regards to earlier behavior, but not for the user running the program to starting wondering if something is wrong.

**Comment by benzea** [comment]
Yes, that should never have been a warning, as it will happen even in the case of normal API usage. The only important warning/error message is `API misuse! Using non-default context as implicit default.` message and it should be kept.
