### ISSUE TITLE
Missing include folder in the release package

### ISSUE THREAD

**Issue by AlbertShown** [libusb/libusb#1218]
In the release package, I don't see the `include` folder in `VS2015-Win32` and `VS2015-x64`, while it exist in all other folder `MinGW`, `macOS`, `Cygwin`. Is that normal?

**Comment by tormodvolden** [comment]
It should be the same include files for all platforms so it should probably be an identical copy in all folders or just one common. Anyway we'll try to mirror the structure of the 1.0.24 binary packages next time.

**Comment by mcuee** [comment]
I will close this one and please use #1166 for further discussion.
* https://github.com/libusb/libusb/issues/1166
