### ISSUE TITLE
libusb_bulk_transfer() return -99 in macOS sub thread

### ISSUE THREAD

**Issue by yuzifu** [libusb/libusb#1219]
I have a qt app, if libusb_bulk_transfer() call by main thread, it works. If call by in sub thread(like boost::thread, QtConcurrent), libusb_bulk_transfer() return -99.

**Comment by mcuee** [comment]
You may want to provide more details. And since this is a technical support question, it is better to ask in libusb-devel mailing list. I am afraid that you will not get any answers here as github is for issues report.

**Comment by mcuee** [comment]
Close issue for now.
