### ISSUE TITLE
Bluescreen on Windows when an Elgato CamLink resets due to loose HDMI connection

### ISSUE THREAD

**Issue by FrostKiwi** [libusb/libusb#1221]
I have an App compiled in MSYS2's MinGW64 environment on Windows 11 Version 21H2 build 22000.1219, streaming from an Elgato CamLink via libUVC (https://github.com/libuvc/libuvc/) and the libusbK (https://github.com/mcuee/libusbk) driver. 
This libUVC library depends libUSB. The exact library setup for my app is here: https://github.com/libuvc/libuvc/issues/245

A loose HDMI connector under vibration, or when wiggling said connector, causes an Elgato CamLink to reset due to momentary loss of HDMI signal. When this happens *during* streaming, Windows BlueScreens with Error message `KERNEL_SECURITY_CHECK_FAILURE` and reboots. 100% repeatable.

https://user-images.githubusercontent.com/60887273/204079682-6c978ec1-d10b-4b24-a84c-e1c68f8483bd.mp4

The maintainer of libusbK suggests https://github.com/mcuee/libusbk/issues/42, that libUSB may be the cause.

This issue is not all that important to me, since I'll buy just a proper HDMI cable and only need the App to work once for a demo. Bug attribution towards libUSB is hard to give for me, since I don't have any experience debugging on the system level in Windows. libUSB might not even be at fault here. But still thought I should follow up on it and reported it here to gain more insight.

**Comment by tormodvolden** [comment]
libusb is only a userspace library, calling into other userspace libraries (e.g. DLLs) delivered with the operating system. There could be bugs in libusb, but they should never be able to cause a bluescreen. Only a kernel driver bug or unhandled hardware problem can cause this. It sounds from the libuvc bug report that this was a hardware problem.
