### ISSUE TITLE
Can I use the libusb library to connect the winUSB device on the Android side?

### ISSUE THREAD

**Issue by zhousongs** [libusb/libusb#1222]
Can I use the libusb library to connect the winUSB device on the Android side?I have a winUSB device. I want to use libusb to read and write the data of this device. Does libusb support it?

**Comment by mcuee** [comment]
Right now it does not work well under Android if your device is not rooted. 
 
Please try the PR #https://github.com/libusb/libusb/pull/1164 and post your test results there. I will close this issue as github is not used for technical support.
