### ISSUE TITLE
Failed to make install libusb in mac m1

### ISSUE THREAD

**Issue by tricia0127** [libusb/libusb#1223]
mac osx m1 12.3.1
When I first executed sudo make install, I was prompted that `# include<libusb-1.0/libusb. h>`could not be found,

Then I put

```
//#ifndef WIN32
//#include <libusb-1.0/libusb.h>
//#else
```

After //, make install again, and tell me that `# include<libusb. h`>cannot be found

Then I downloaded libusb.h myself. Re make install, andtell me that：

```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1
```

How to solve this problem?

**Comment by mcuee** [comment]
Take note github is not for technical support. Please post to libusb-devel.

I will close the issue here.
