### ISSUE TITLE
-lusb

### ISSUE THREAD

**Issue by iddq** [libusb/libusb#124]
I cannot compile a program under cygwin because the compiler cannot find the usb library

workaround create a link manually:

cd /usr/local/lib
ln -s libusb-1.0.a libusb.a

**Comment by LudovicRousseau** [comment]
Maybe you should use ``-lusb-1.0``

**Comment by hiyuh** [comment]
recently libusb1.0-devel is updated to 1.0.20-1, so use official package,
if you do not required to use locally modified one.
and compile/link w/ `pkg-config --cflags --libs libusb-1.0`.
