### ISSUE TITLE
The insertion of a new usb device causes the transfer of the usb device that is being transferred to slow down。

### ISSUE THREAD

**Issue by xumoxiao** [libusb/libusb#1248]
Thank you for developing libusb, I encountered a problem when using it, I would like to ask for advice.

Under MacOS, USB device A is transferring data at a speed of 200MB/s. At this time, when any USB device is inserted, the transmission of device A will freeze, which is obviously affected.

Is this phenomenon caused by libusb? Is there a way to eliminate this phenomenon?

**Comment by mcuee** [comment]
Most likely this is a USB device FW issue.

You need to provide more info about your device -- the USB report descriptor from either macOS USB Prober or `lsusb -vvv` output of your device. 

`lsusb` is part of usbutils package.
https://github.com/Homebrew/homebrew-core/blob/b6544f786f678eef03c26c487ecf4c179dd51b1c/Formula/usbutils.rb

What do you mean by "freeze" in this case? Do you mean if your device got disappeared from the OS?

**Comment by xumoxiao** [comment]
Thank you for your reply.
Device A does not disappear, but the transmission of the device is blocked. It may wait 2~3s for the system to enumerate new usb devices before the transmission of device A returns to normal.
Any usb device newly inserted into the system will affect the transmission of device A.
The insertion of the U disk will also affect the transmission of device A.

![image](https://user-images.githubusercontent.com/19544093/220910938-386870d1-55b1-4d5f-ab49-4f075cc84b17.png)

The usb chip of device A is Cypress Cyusb3014, and the running firmware is basically the official example.
Here is the output of **lsusb -vvv**

Bus 020 Device 040: ID 04b4:00f1  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         9
  idVendor           0x04b4 
  idProduct          0x00f1 
  bcdDevice            0.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0046
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              400mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           4
      bInterfaceClass       255 
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               0
Binary Object Store Descriptor:
  bLength                 5
  bDescriptorType        15
  wTotalLength       0x0016
  bNumDeviceCaps          2
  USB 2.0 Extension Device Capability:
    bLength                 7
    bDescriptorType        16
    bDevCapabilityType      2
    bmAttributes   0x00000002
      HIRD Link Power Management (LPM) Supported
  SuperSpeed USB Device Capability:
    bLength                10
    bDescriptorType        16
    bDevCapabilityType      3
    bmAttributes         0x00
    wSpeedsSupported   0x000e
      Device can operate at Full Speed (12Mbps)
      Device can operate at High Speed (480Mbps)
      Device can operate at SuperSpeed (5Gbps)
    bFunctionalitySupport   3
      Lowest fully-functional device speed is SuperSpeed (5Gbps)
    bU1DevExitLat           0 micro seconds
    bU2DevExitLat           0 micro seconds
can't get debug descriptor: Operation timed out
Device Status:     0x0000
  (Bus Powered)

**Comment by mcuee** [comment]
@xumoxiao 

What is your mac machine and macOS version?

You may want to post your test code and FW image if possible. I have the Cyusb FX3 development board and I had no issues around 300MBps (2.4Gbps) last time using libusbdotnet (which is using libsub) on my Mac Mini M1 running official FW.
https://github.com/LibUsbDotNet/LibUsbDotNet/issues/137#issuecomment-884863648

```
libusbdotnet_v2 on  v2 took 18s ❯ ./stage/BenchmarkCon/bin/Release/net5.0/BenchmarkCon list notestselect buffercount=3 buffersize=32768 loop mode=async
LibUsbDotNet USB Benchmark v2.2.0.0
Copyright (c) 2010 Travis Robinson. <libusbdotnet@gmail.com>
website: http://sourceforge.net/projects/libusbdotnet
1. 04B4:00F1 Cypress - FX3
2. 046D:C52B Logitech - USB Receiver
3. 047F:C025 Plantronics C320-M
4. 1A40:0201 
5. 0AC8:3420 Vimicro Corp. - PROLiNK PCC3220
6. 1A40:0201 
7. 0BDA:5411 Generic - 4-Port USB 2.0 Hub
8. 05E3:0749 Generic - USB3.0 Card Reader
9. 0BDA:0411 Generic - 4-Port USB 3.0 Hub
10. 0BDA:0411 Generic - 4-Port USB 3.0 Hub
11. 0BDA:5411 Generic - 4-Port USB 2.0 Hub

Select device (1-11) :1

Benchmark device 04B4:00F1 opened..
Loop Test Information
	Vid / Pid       : 04B4h / 00F1h
	Interface #     : 00h
	Alt Interface # : 00h
	Priority        : Normal
	Buffer Size     : 32768
	Buffer Count    : 3
	Display Refresh : 1000 (ms)
	Transfer Timeout: 5000 (ms)
	Retry Count     : 0
	Verify Data     : Off

Bulk Read (Ep81h) max packet size: 1024
Bulk Write (Ep01h) max packet size: 1024

While the test is running:
Press 'Q' to quit
Press 'T' for test details
Press 'I' for status information
Press 'R' to reset averages

Press 'Q' to exit, any other key to begin..
Avg. Bytes/s: 281226203.00 Transfers: 8086 Bytes/s: 281226203.00
Avg. Bytes/s: 288942931.94 Transfers: 17199 Bytes/s: 296153452.65
Avg. Bytes/s: 291884573.12 Transfers: 26336 Bytes/s: 297587420.67
Avg. Bytes/s: 293362093.71 Transfers: 35470 Bytes/s: 297707201.40
Avg. Bytes/s: 294178361.38 Transfers: 44600 Bytes/s: 297393131.68
Avg. Bytes/s: 294741105.78 Transfers: 53733 Bytes/s: 297520426.37
Avg. Bytes/s: 295190625.51 Transfers: 62869 Bytes/s: 297862455.43
Avg. Bytes/s: 295488757.12 Transfers: 72000 Bytes/s: 297557922.46
Avg. Bytes/s: 295693625.44 Transfers: 81130 Bytes/s: 297319243.79
Avg. Bytes/s: 295910920.67 Transfers: 90252 Bytes/s: 297857662.74
Avg. Bytes/s: 296073306.84 Transfers: 99385 Bytes/s: 297687636.52
Avg. Bytes/s: 296204760.63 Transfers: 108519 Bytes/s: 297642661.24
Avg. Bytes/s: 296320007.38 Transfers: 117654 Bytes/s: 297695970.59
Avg. Bytes/s: 296410631.73 Transfers: 126781 Bytes/s: 297583831.34
qAvg. Bytes/s: 296493732.55 Transfers: 135920 Bytes/s: 297651376.26
stopped Ep81h thread.
stopped Ep01h thread.
Loop Test Information
	Vid / Pid       : 04B4h / 00F1h
	Interface #     : 00h
	Alt Interface # : 00h
	Priority        : Normal
	Buffer Size     : 32768
	Buffer Count    : 3
	Display Refresh : 1000 (ms)
	Transfer Timeout: 5000 (ms)
	Retry Count     : 0
	Verify Data     : Off

Bulk Read (Ep81h) max packet size: 1024
	Total Bytes     : 4453859328
	Total Transfers : 135921
	Avg. Bytes/sec  : 296490308.47
	Elapsed Time    : 15.02 seconds

Bulk Write (Ep01h) max packet size: 1024
	Total Bytes     : 4822728704
	Total Transfers : 147178
	Avg. Bytes/sec  : 321044531.44
	Elapsed Time    : 15.02 seconds

Press any key to exit..


```

**Comment by xumoxiao** [comment]
@mcuee Sorry i'm late.
Bought a new Macbook air these days, did the same test.
This mac is an m2 chipset, and it runs multiple libusb reads and writes, plugs and unplugs at the same time, without any blocking at all.
My previous machine was Macmini 2018，i5 + 8g configuration, running on MacOS 10.14.6 environment.
This problem is estimated to be related to the chipset or the system itself.
If you have time, I hope you can study it. The impact of my use here is not great, but I just need to emphasize to the user that the device cannot be plugged and unplugged at runtime or the timeout period should be increased when the software is used (the current usage scenario must be under Macmini 2018, i5 + 8g). 
Thank you for your reply

**Comment by mcuee** [comment]
@xumoxiao 

Sorry but I am not so sure how to help here as I do not have the Mac Mini 2018. I have the Mac Mini M1. As you do not see issues with Mac Mini M2, most likely the device FW is good and it could be related to your paticular Mac Mini 2018 system.

Please help to provode the test FW, test code and the debug log (set LIBUSB_DEBUG=4). If it is not possible for you to provide the test FW, then at least the test code and debug log.

**Comment by mcuee** [comment]
@xumoxiao 
I will close this issue for now. Please reopen if you have new information to say there is an issue with libusb.
