### ISSUE TITLE
LIBUSB_ERROR_NOT_FOUND when trying to redirect Xbox Elite Series 2 Wireless Controller

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [libusb/libusb#1251]
OS: Manjaro Linux
Kernel 6.2
Virt-manager with KVM QEMU
VM with Win11

Redirecting e.g. DualSense Controller works fine

**Comment by mcuee** [comment]
You may post the issue to the wrong project. You may want to post the issue to Virt-manager project.

**Comment by FZXizzbKv7jg** [comment]
Yes. Thank you.
