### ISSUE TITLE
libusb_bulk_transfer will change data's pointer address？

### ISSUE THREAD

**Issue by biepenghaomie** [libusb/libusb#1268]
I want to use shared_ptr<uchar[]> to manage memory.But it will generate error which is "malloc(): invalid size (unsorted)" by use make_shared to malloc data's size.Or generating error which is " free(): invalid size"  when using "shared_ptr<uchar[]> ByteData(new uchar[Len])" to malloc data's size.So I want to know libusb_bulk_transfer will change data's pointer address?Or free the pointer then renew a memory block?

**Comment by mcuee** [comment]
You may get better support if you ask in libusb-devel mailing list for technical questions like this one.
https://github.com/libusb/libusb/wiki#user-content-Support
