### ISSUE TITLE
El Capitan: Problem with port number

### ISSUE THREAD

**Issue by dumych** [libusb/libusb#127]
I've found strange behaviour on new Mac Os (El Capitan). I just little bit customized 
output format of  libusb example (https://github.com/libusb/libusb/blob/master/examples/listdevs.c), used libusb_get_port_number() instead of libusb_get_port_numbers()  and noticed that all my devices have port number 0. Is this OK?

I'm using Mac mini(Late 2012). I've checked 19 and 20 versions of libusb. 

My debug output:
 bus number 20 
 port number 0 
 device address 15 

 bus number 20 
 port number 0 
 device address 12 

 bus number 29 
 port number 0 
 device address 5 

 bus number 26 
 port number 0 
 device address 3 

 bus number 29 
 port number 0 
 device address 4 

 bus number 29 
 port number 0 
 device address 3 

 bus number 26 
 port number 0 
 device address 2 

 bus number 29 
 port number 0 
 device address 2 

 bus number 20 
 port number 0 
 device address 2 

 bus number 26 
 port number 0 
 device address 1 

 bus number 29 
 port number 0 
 device address 1 

 bus number 29 
 port number 0 
 device address 0 

 bus number 29 
 port number 0 
 device address 0 

 bus number 29 
 port number 0 
 device address 0

**Comment by hjelmn** [comment]
ill add that to the todo list. Apple appears to have rewritten IOUSBFamily

**Comment by mvp** [comment]
I also noticed that `libusb_get_port_numbers()` does not work on El Capitan for my utility [uhubctl](https://github.com/mvp/uhubctl/blob/master/uhubctl.c#L334), `libusb_get_port_numbers()` always returns 0.

Koromix [has a code](https://github.com/Koromix/ty/blob/master/libty/device_darwin.c#L301-L305) to support new Apple USB stack.
I think this file: [darwin_usb.c](https://github.com/libusb/libusb/blob/master/libusb/os/darwin_usb.c#L783) needs to be changed to handle new USB stack as "ty" does.

**Comment by diabolo38** [comment]
the port alway 0 is not necessary wrong on other os (win xp) and base on the bus/hub structure that can happen . 
if you combine bus + device address and it always the same for different plug then that will be a real problem
 


    Le Vendredi 20 novembre 2015 19h51, mvp <notifications@github.com> a écrit :
 

 I also noticed that libusb_get_port_numbers() does not work on El Capitan for my utility uhubctl, libusb_get_port_numbers() always returns 0.Koromix has a code to support new Apple USB stack.
I think this file: darwin_usb.c needs to be changed to handle new USB stack as "ty" does.—

**Comment by mvp** [comment]
@diabolo38: in this particular case, it is definitely a bug. uhubctl always worked on any OSX version before, and on any Linux. But, on El Capitan, `libusb_get_port_numbers()` simply does not work: it DOES NOT fill array with port numbers, and returns 0 for filled array length.

**Comment by hjelmn** [comment]
In this case it is wrong. Will patch later today.

**Comment by mvp** [comment]
For reference: commit which adds new USB stack support to "ty" by Koromix:
https://github.com/Koromix/ty/commit/eee4cb952583ab213df7c1eb0871c36aa82aea0b

**Comment by mvp** [comment]
It seems like this fix is not really necessary - everything works now without this patch with libusb 1.0.20 under OSX 10.11.2 (15C50). I guess Apple added back exporting PortNum.

**Comment by hjelmn** [comment]
Huh, guess someone else complained about it. Was a bug in the legacy USB stack support in 10.11. We will still have support for directly using the new stack in the next libusb version.
