### ISSUE TITLE
In windows open USB to serial port tools error, why?

### ISSUE THREAD

**Issue by liutt1312** [libusb/libusb#1277]
Log info

[ 0.038437] [000035c0] libusb: debug [libusb_open] open 1.7
[ 0.038524] [000035c0] libusb: debug [winusb_open] unsupported API call for 'open' (unrecognized device driver)
[ 0.038647] [000035c0] libusb: debug [libusb_open] open 1.7 returns -12

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/wiki/Windows#user-content-How_to_use_libusb_on_Windows

**Comment by mcuee** [comment]
@liutt1312 

Please read the Wiki before raising issues. Thanks. And this github repo is not for technical support, but for issues (bugs, enhancement request, etc).

If you want to ask for technical support, please use libusb-devel mailing list.

**Comment by mcuee** [comment]
FYI, libusb is not the right libary to use for USB to Serial Port. You should use Windows native API for serial port.
