### ISSUE TITLE
Need api to wakup poll thread

### ISSUE THREAD

**Issue by kangjianbin** [libusb/libusb#128]
Hi, guys.
We need an api to export function 'usbi_signal_event', so we can exit the polling thread quicker.
Otherwise we need to wait unit libusb_handle_events or libusb_handle_events_timeout return.

 The scenario is:
Thread 1:
while (!is_exit) {
        libusb_handle_events(NULL);
        ....
}
Thread 2:
is_exit = true;
libusb_wakup_poller(...);   /* or something similar */

**Comment by dickens** [comment]
There was a recent pull request for this [1], but it was not valid for
the current branch. I may very well just write the appropriate patch
myself.

[1] https://github.com/libusb/libusb/pull/99

**Comment by dickens** [comment]
Closed with commit a6db382a
