### ISSUE TITLE
libusb_bulk_transfer Does the parameter length setting affect the read rate?

### ISSUE THREAD

**Issue by aichimangguo** [libusb/libusb#1286]
When I set the length of 512 * 1024 to receive data normally, but the length is set to 1024 * 1024, data will be lost

**Comment by mcuee** [comment]
> When I set the length of 512 * 1024 to receive data normally, but the length is set to 1024 * 1024, data will be lost

github is for issue reporting and not for technical support. You may want to ask the question in libusb-devel mailing list.
https://github.com/libusb/libusb/wiki#user-content-Support

And you need to provide more details.
https://github.com/libusb/libusb/wiki/Troubleshooting
