### ISSUE TITLE
libusb_control_transfer only failed in Windows

### ISSUE THREAD

**Issue by alexandrggdev9** [libusb/libusb#1292]
Hi there,
I am developing a mouse device with libusb.
I am able to send data to the mouse with libusb_control_transfer function in Ubuntu but when I call this in Windows it returns -12.
I installed WinUSB driver.
it is exactly the same code but why it failed in Windows?
Any advice will be appreciated.

**Comment by mcuee** [comment]
Code and debug log please. Thanks.

Ref:
https://github.com/libusb/libusb/wiki/Troubleshooting#example-of-a-good-request-for-help
