### ISSUE TITLE
How to communicat with hid device on IpadOs with Type-c interface

### ISSUE THREAD

**Issue by pengxianheng-nreal** [libusb/libusb#1301]
As we know, The libusb is not support on IpadOs. but I want to know whether exist Mature solutions on ipados.

**Comment by mcuee** [comment]
You can probably use native API from iPadOS.
https://developer.apple.com/documentation/hiddriverkit/iohiddevice

**Comment by pengxianheng-nreal** [comment]
Does this https://developer.apple.com/documentation/driverkit/creating_drivers_for_ipados is the same with you suggested above?

**Comment by mcuee** [comment]
I think not. The link I mention is the user space API, not to create a kernel driver.
