### ISSUE TITLE
HID device

### ISSUE THREAD

**Issue by 1369841815** [libusb/libusb#1312]
Again to bother you, I still want to know, the HID device in obtaining the device list did not, but the computer device manager has, I follow the source code found that the DeviceIoControl function to obtain device information failed, but I changed to another port of the usb hub works, other ports have failed, The scanned device list is not displayed.

**Comment by mcuee** [comment]
I have re-opened your previous issue. Please continue there and I will close this one.
https://github.com/libusb/libusb/issues/1310
