### ISSUE TITLE
USB composite devices

### ISSUE THREAD

**Issue by Fly2023-HM** [libusb/libusb#1316]
USB composite devices have multiple sub devices, each with different interfaces. Can I use libusb_open the interface to open different sub devices separately,

operating system:windows10

**Comment by mcuee** [comment]
> USB composite devices have multiple sub devices, each with different interfaces. Can I use libusb_open the interface to open different sub devices separately,
> 
> operating system:windows10

Yes you can as long as you have supported driver for the devices.

There are some issues though.
* https://github.com/libusb/libusb/issues/1177
* https://github.com/libusb/libusb/pull/1181 (which is supposed to fix the above issue)
* https://github.com/libusb/libusb/issues/1238

**Comment by mcuee** [comment]
github is not for technical support. You can use libusb-devel if you need further support. I will close this issue.
