### ISSUE TITLE
Lost data when using Cyusb3014 in Windows

### ISSUE THREAD

**Issue by ZTZ-99** [libusb/libusb#1318]
I designed a simple counter with FPGA and Cyusb3014, which will continue to accumulate with the 100MHz clock of GPIF II and then send it directly to Endpoint.。
On the PC, I read data through the asynchronous IO of Libusb to verify whether the data is continuous. 
In the Linux platform (Jetson Nano Ubuntu18.04.6), it can run continuously for several hours without losing data at a speed of 100MHz * 32bit. 
But in the Win10 environment, libusb cannot transmit data normally. Almost every transfer will lose a part of the data, and sometimes the data is lost between transfer. The reduction speed can improve the error rate. When 80MHz * 32bit, it can run normally for a few minutes. The transmission of errors will not last too long. Generally, a few transfer will be recovered. I tested libusbk and Winusb and did not improve. Is there any way to solve this problem?

**Comment by mcuee** [comment]
Please use libusb-devel mailing list for  technical support questions like this one. 

I believe you will get better support there.

github is mainly for issue reporting and feature requests.
