### ISSUE TITLE
libusb + WinUSB backend claim interface 1 and 2 failed for iPhone on Windows

### ISSUE THREAD

**Issue by Pivot2017** [libusb/libusb#1328]
I am using libusb + WinUSB backend to communicate with iPhone on Windows.
first, iPhone is recognized as a MTP device;
then i replace iPhone's driver with WinUSB(zadig/libwdi generate the driver);
libusb then can open iPhone and claim interface 0(submit control transfer);
but i can't claim interface 1 and interface 2 ( libusb_get_active_config_descriptor() can emun all the 5 altsettings in 3 interfaces ).
this is because WinUSB driver(.inf file) issue? what should i do?
thanks in advance.

**Comment by mcuee** [comment]
How do you replace the driver of iPhone? 

What is the version of libusb you are using? Please post the debug log of `xusb -d xxxx:yyyy` where xxxx/yyyy is your iPhone's USB VID/PID.

**Comment by Pivot2017** [comment]
Hi mcuee, 
i replace the driver with command "wdi-simple.exe -v 1452 -p 4776".
i am using libusb version 1.0.22.
below is "xusb -d 05ac:12a8" output(latest xusb from version 1.0.26):

===============================

Using libusb v1.0.26.11724
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000341] [00000b8c] libusb: debug [libusb_init] created default context
[ 0.000449] [00000b8c] libusb: debug [libusb_init] libusb v1.0.26.11724
[ 0.000570] [00000b8c] libusb: debug [usbi_add_event_source] add HANDLE 00000000000000A8 events 0
[ 0.000695] [00000b8c] libusb: debug [usbi_io_init] using timer for timeouts
[ 0.000795] [00000b8c] libusb: debug [usbi_add_event_source] add HANDLE 00000000000000AC events 0
[ 0.000915] [00000b8c] libusb: debug [get_windows_version] Windows 8 (or later) 64-bit
[ 0.000977] [00000b8c] libusb: debug [htab_create] using 1021 entries hash table
[ 0.007578] [00000b8c] libusb: info [winusbx_init] WinUSB DLL available (with isoch support)
[ 0.007669] [00000b8c] libusb: info [winusbx_init] libusbK DLL is not available
[ 0.008802] [00000b8c] libusb: info [windows_init] UsbDk backend is not available
Opening device 05AC:12A8...
[ 0.008875] [00000b8c] libusb: debug [libusb_get_device_list]
[ 0.009193] [000024cc] libusb: debug [windows_iocp_thread] I/O completion thread started
[ 0.018083] [00000b8c] libusb: debug [winusb_get_device_list] allocating new device for session [5]
[ 0.018248] [00000b8c] libusb: debug [winusb_get_device_list] allocating new device for session [6]
[ 0.018680] [00000b8c] libusb: debug [get_api_type] driver(s): BTHUSB
[ 0.019146] [00000b8c] libusb: debug [get_api_type] lower filter driver(s): ibtusb
[ 0.019225] [00000b8c] libusb: debug [winusb_get_device_list] allocating new device for session [33]
[ 0.019464] [00000b8c] libusb: debug [get_api_type] driver(s): WinUSB
[ 0.019579] [00000b8c] libusb: debug [get_api_type] matched driver name against WinUSB
[ 0.019594] [00000b8c] libusb: debug [winusb_get_device_list] allocating new device for session [37]
[ 0.019796] [00000b8c] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.019842] [00000b8c] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.019906] [00000b8c] libusb: debug [winusb_get_device_list] allocating new device for session [5C]
[ 0.020037] [00000b8c] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_A0ED&SUBSYS_15451025&REV_20\3&11583659&0&A0' bus number 1
[ 0.020119] [00000b8c] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_9A13&SUBSYS_72708086&REV_01\3&11583659&0&68' bus number 2
[ 0.020717] [00000b8c] libusb: debug [winusb_get_device_list] found existing device for session [5C]
[ 0.020852] [00000b8c] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.020933] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 577 bytes)
[ 0.021021] [00000b8c] libusb: debug [init_device] (bus: 1, addr: 1, depth: 1, port: 5): 'USB\VID_0408&PID_A094\5&586B51A&0&5'
[ 0.021235] [00000b8c] libusb: debug [winusb_get_device_list] found existing device for session [33]
[ 0.021457] [00000b8c] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.022091] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 200 bytes)
[ 0.022272] [00000b8c] libusb: debug [init_device] (bus: 1, addr: 3, depth: 1, port: 10): 'USB\VID_8087&PID_0026\5&586B51A&0&10'
[ 0.022894] [00000b8c] libusb: debug [winusb_get_device_list] extra GUID: {20348E47-A897-468E-9D0E-56307802FC2A}
[ 0.022993] [00000b8c] libusb: debug [winusb_get_device_list] allocating new device for session [70]
[ 0.023412] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.073620] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.124764] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.175906] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.226654] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.277287] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.327634] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.378763] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.429808] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.480524] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.531175] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.581507] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.632714] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.683044] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.733751] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.784177] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.834686] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.885742] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.936276] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 0.987174] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 1.038445] [00000b8c] libusb: debug [init_device] 0x1c7a:0x575 found 1 configurations (not configured)
[ 1.089312] [00000b8c] libusb: info [init_device] 0x1c7a:0x575 found 1 configurations but device isn't configured, forcing current configuration to 1
[ 1.089620] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 46 bytes)
[ 1.091757] [00000b8c] libusb: debug [init_device] (bus: 1, addr: 2, depth: 1, port: 7): 'USB\VID_1C7A&PID_0575\07B30DB5'
[ 1.092826] [00000b8c] libusb: debug [init_root_hub] root hub 'USB\ROOT_HUB30\4&12C539F&0&0' reports 16 ports
[ 1.094969] [00000b8c] libusb: debug [init_device] (bus: 1, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\4&12C539F&0&0'
[ 1.095450] [00000b8c] libusb: debug [winusb_get_device_list] extra GUID: {0D83FEE0-9A3B-4C2E-8CE1-1A43A200EA9E}
[ 1.095568] [00000b8c] libusb: debug [winusb_get_device_list] found existing device for session [37]
[ 1.096113] [00000b8c] libusb: debug [init_device] found 4 configurations (current config: 1)
[ 1.096232] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 39 bytes)
[ 1.098092] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 1 (bConfigurationValue=2, 149 bytes)
[ 1.098790] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 2 (bConfigurationValue=3, 62 bytes)
[ 1.099491] [00000b8c] libusb: debug [cache_config_descriptors] cached config descriptor 3 (bConfigurationValue=4, 117 bytes)
[ 1.099612] [00000b8c] libusb: debug [init_device] (bus: 1, addr: 19, depth: 1, port: 1): 'USB\VID_05AC&PID_12A8\5FD5A98332891CEDB76DBD94C240B351A1046E61'
[ 1.100147] [00000b8c] libusb: debug [init_root_hub] root hub 'USB\ROOT_HUB30\4&1A63DC7C&0&0' reports 5 ports
[ 1.102152] [00000b8c] libusb: debug [init_device] (bus: 2, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\4&1A63DC7C&0&0'
[ 1.104890] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\SYNA7DAB&COL01\5&2F64DFEA&0&0000' (non USB HID, newly connected, etc.) - ignoring
[ 1.105129] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\INTC816\3&D2322F2&0&0000' (non USB HID, newly connected, etc.) - ignoring
[ 1.105250] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\SYNA7DAB&COL02\5&2F64DFEA&0&0001' (non USB HID, newly connected, etc.) - ignoring
[ 1.105764] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\SYNA7DAB&COL03\5&2F64DFEA&0&0002' (non USB HID, newly connected, etc.) - ignoring
[ 1.105816] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\SYNA7DAB&COL04\5&2F64DFEA&0&0003' (non USB HID, newly connected, etc.) - ignoring
[ 1.105860] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\CONVERTEDDEVICE&COL02\5&32CF90E6&0&0001' (non USB HID, newly connected, etc.) - ignoring
[ 1.106087] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\CONVERTEDDEVICE&COL03\5&32CF90E6&0&0002' (non USB HID, newly connected, etc.) - ignoring
[ 1.106671] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\10251229\3&9D5D338&0&0000' (non USB HID, newly connected, etc.) - ignoring
[ 1.106950] [00000b8c] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\CONVERTEDDEVICE&COL01\5&32CF90E6&0&0000' (non USB HID, newly connected, etc.) - ignoring
[ 1.107609] [00000b8c] libusb: debug [get_api_type] driver(s): WinUSB
[ 1.107796] [00000b8c] libusb: debug [get_api_type] matched driver name against WinUSB
[ 1.108568] [00000b8c] libusb: debug [libusb_get_device_descriptor]
[ 1.108640] [00000b8c] libusb: debug [libusb_get_device_descriptor]
[ 1.108973] [00000b8c] libusb: debug [libusb_get_device_descriptor]
[ 1.109195] [00000b8c] libusb: debug [libusb_get_device_descriptor]
[ 1.109536] [00000b8c] libusb: debug [libusb_get_device_descriptor]
[ 1.109885] [00000b8c] libusb: debug [libusb_open] open 1.19
[ 1.111234] [00000b8c] libusb: debug [libusb_unref_device] destroy device 1.1
[ 1.114030] [00000b8c] libusb: debug [libusb_unref_device] destroy device 1.3
[ 1.115012] [00000b8c] libusb: debug [libusb_unref_device] destroy device 1.2
[ 1.115280] [00000b8c] libusb: debug [libusb_unref_device] destroy device 2.0

Reading device descriptor:
[ 1.115323] [00000b8c] libusb: debug [libusb_get_device_descriptor]
            length: 18
      device class: 0
               S/N: 3
           VID:PID: 05AC:12A8
         bcdDevice: 1003
   iMan:iProd:iSer: 1:2:3
          nb confs: 4

Reading BOS descriptor: [ 1.117308] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.117563] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.117837] [00000b8c] libusb: debug [libusb_claim_interface] interface 0
[ 1.118315] [00000b8c] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 1.118789] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 02 to interface 0
[ 1.118818] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 81 to interface 0
[ 1.118844] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 83 to interface 0
[ 1.119008] [00000b8c] libusb: debug [auto_claim] auto-claimed interface 0 for control request
[ 1.119048] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.119242] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.119493] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 5
[ 1.123713] [00000b8c] libusb: debug [handle_events] event sources modified, reallocating event data
[ 1.127014] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.128056] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.128259] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.128616] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 5
[ 1.129123] [00000b8c] libusb: debug [libusb_release_interface] interface 0
[ 1.129322] [00000b8c] libusb: debug [auto_release] auto-released interface 0
[ 1.129800] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.129986] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.130803] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=5
[ 1.131023] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
[ 1.131506] [00000b8c] libusb: debug [libusb_get_bos_descriptor] found BOS descriptor: size 140 bytes, 3 capabilities
[ 1.131768] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.132846] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.132879] [00000b8c] libusb: debug [libusb_claim_interface] interface 0
[ 1.133320] [00000b8c] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 1.133448] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 02 to interface 0
[ 1.133474] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 81 to interface 0
[ 1.133489] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 83 to interface 0
[ 1.133588] [00000b8c] libusb: debug [auto_claim] auto-claimed interface 0 for control request
[ 1.133870] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.133933] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.134333] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.134288] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 140
[ 1.135140] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.137607] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.137629] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 140
[ 1.137919] [00000b8c] libusb: debug [libusb_release_interface] interface 0
[ 1.137940] [00000b8c] libusb: debug [auto_release] auto-released interface 0
[ 1.137954] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.137970] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.138869] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=140
[ 1.138893] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
3 caps
    USB 2.0 extension:
      attributes             : 02
    Unknown BOS device capability 05:
    Unknown BOS device capability 05:

Reading first configuration descriptor:
[ 1.139183] [00000b8c] libusb: debug [libusb_get_config_descriptor] index 0
              total length: 39
         descriptor length: 9
             nb interfaces: 1
              interface[0]: id = 0
interface[0].altsetting[0]: num endpoints = 3
   Class.SubClass.Protocol: 06.01.01
       endpoint[0].address: 02
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[2].address: 83
           max packet size: 0040
          polling interval: 0A
[ 1.141123] [00000b8c] libusb: debug [libusb_kernel_driver_active] interface 0

Kernel driver attached for interface 0: -12

Claiming interface 0...
[ 1.141514] [00000b8c] libusb: debug [libusb_claim_interface] interface 0
[ 1.141595] [00000b8c] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 1.142106] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 02 to interface 0
[ 1.142427] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 81 to interface 0
[ 1.142731] [00000b8c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 83 to interface 0

Reading string descriptors:
[ 1.143540] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.143860] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.144102] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.148613] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.148813] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.148955] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 4
[ 1.149659] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.153696] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.154133] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 4
[ 1.154544] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.154906] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.155366] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=4
[ 1.155799] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
[ 1.156064] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.156328] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.156685] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.161346] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.161496] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.161628] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 22
[ 1.161997] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.162317] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.162480] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 22
[ 1.162824] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.162985] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.163330] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=22
[ 1.163485] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
   String (0x01): "Apple Inc."
[ 1.164014] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.164377] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.164538] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.164922] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.165073] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.165176] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 4
[ 1.166211] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.166895] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.167053] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 4
[ 1.167612] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.170134] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.170787] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=4
[ 1.171016] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
[ 1.171538] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.171703] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.172341] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.172558] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.172810] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 14
[ 1.173371] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.173927] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.174096] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.174470] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 14
[ 1.174629] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.175001] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.175155] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=14
[ 1.175547] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
   String (0x02): "iPhone"
[ 1.176179] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.176404] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.176812] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.177018] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.177266] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 4
[ 1.177418] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.179407] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.182340] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.182510] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 4
[ 1.183315] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.183503] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.183889] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=4
[ 1.184046] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
[ 1.184419] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.184579] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.184918] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.185106] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.185586] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.185376] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 82
[ 1.186137] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.186302] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.187201] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 0, length 82
[ 1.187356] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.187697] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.187862] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=82
[ 1.188261] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
   String (0x03): "5fd5a98332891cedb76dbd94c240b351a1046e61"

Reading OS string descriptor:[ 1.189083] [00000b8c] libusb: debug [libusb_submit_transfer] transfer 00000207A69B5F70
[ 1.189446] [00000b8c] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.189605] [00000b8c] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 1.190020] [00000b8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 1.190181] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[ 1.190328] [000024cc] libusb: debug [windows_iocp_thread] transfer 00000207A69B5F70 completed, length 0
[ 1.194332] [00000b8c] libusb: debug [usbi_wait_for_events] WaitForMultipleObjects() returned 0
[ 1.194361] [00000b8c] libusb: debug [handle_event_trigger] event triggered
[ 1.194392] [00000b8c] libusb: debug [windows_handle_transfer_completion] handling transfer 00000207A69B5F70 completion with errcode 31, length 0
[ 1.194782] [00000b8c] libusb: debug [windows_handle_transfer_completion] detected endpoint stall
[ 1.195853] [00000b8c] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.196034] [00000b8c] libusb: debug [usbi_handle_transfer_completion] transfer 00000207A69B5F70 has callback 00007FF6D8287DC0
[ 1.196620] [00000b8c] libusb: debug [sync_transfer_cb] actual_length=0
[ 1.196788] [00000b8c] libusb: debug [libusb_free_transfer] transfer 00000207A69B5F70
 no descriptor

Releasing interface 0...
[ 1.198025] [00000b8c] libusb: debug [libusb_release_interface] interface 0
Closing device...
[ 1.198778] [00000b8c] libusb: debug [libusb_close]
[ 1.199204] [00000b8c] libusb: debug [libusb_unref_device] destroy device 1.19
[ 1.199301] [00000b8c] libusb: debug [libusb_unref_device] destroy device 1.0
[ 1.199697] [00000b8c] libusb: debug [libusb_exit] destroying default context
[ 1.199855] [000024cc] libusb: debug [windows_iocp_thread] I/O completion thread exiting
[ 1.201008] [00000b8c] libusb: debug [usbi_remove_event_source] remove HANDLE 00000000000000AC
[ 1.201080] [00000b8c] libusb: debug [usbi_remove_event_source] remove HANDLE 00000000000000A8

**Comment by tormodvolden** [comment]
It looks like the device has 4 configurations. But WinUSB only allows accessing the first configuration, which has 1 interface as seen in the xusb log. https://github.com/libusb/libusb/wiki/Windows#known-restrictions

**Comment by Pivot2017** [comment]
> It looks like the device has 4 configurations. But WinUSB only allows accessing the first configuration, which has 1 interface as seen in the xusb log. https://github.com/libusb/libusb/wiki/Windows#known-restrictions

any other way to switch configuration and access interface 1 and interface 2? for example install a different winusb.inf driver?
or use libusb-win32 instead?

**Comment by mcuee** [comment]
> any other way to switch configuration and access interface 1 and interface 2? for example install a different winusb.inf driver? or use libusb-win32 instead?

You can try libusb-win32 device driver.

Still just wondering what is your end goal? I think you can not do much with libusb for iPhones.

**Comment by Pivot2017** [comment]
> > any other way to switch configuration and access interface 1 and interface 2? for example install a different winusb.inf driver? or use libusb-win32 instead?
> 
> You can try libusb-win32 device driver.
> 
> Still just wondering what is your end goal. I think you can not do much with iPhones using libusb under Windows.
> 
> Not so sure if your needs are better served by usbmuxd project or not. https://github.com/libimobiledevice/usbmuxd

Yes. i want to use usbmuxd to communicate with iPhone. 
so "libusb+winusb backend" or "libusb-win32", which works?

**Comment by mcuee** [comment]
Hmm, I do not use usbmuxd but I tend to believe that you do not need to use libusb at all, you just need to install iTunes under Windows. 

Maybe you want to ask in usbmuxd project.

**Comment by Pivot2017** [comment]
> Hmm, I do not use usbmuxd but I tend to believe that you do not need to use libusb at all, you just need to install iTunes under Windows.
> 
> Maybe you want to ask in usbmuxd project.

Thanks very much. i will try to look into libusb-win32 first.
