### ISSUE TITLE
the parameter config of op_get_configuration in linux_usbfs.c is not assigned

### ISSUE THREAD

**Issue by dotNetTest** [libusb/libusb#137]
The config parameter is not assigned in bellow function. 

static int op_get_configuration(struct libusb_device_handle *handle,
	int *config)
{
	int r;
	if (sysfs_can_relate_devices) {
		r = sysfs_get_active_config(handle->dev, config);
	} else {
		r = usbfs_get_active_config(handle->dev,
					    _device_handle_priv(handle)->fd);
		if(r>=0)       //new add    
                *config = r;  //new add
        }
	if (r < 0)
		return r;
	if (*config == -1) {
		usbi_err(HANDLE_CTX(handle), "device unconfigured");
		*config = 0;
	}

	return 0;
}

**Comment by rgfernandes** [comment]
To help here, I think that you can assign config even r is negative.

    diff --git a/libusb/os/linux_usbfs.c b/libusb/os/linux_usbfs.c
    index a63852f..bd41a16 100644
    --- a/libusb/os/linux_usbfs.c
    +++ b/libusb/os/linux_usbfs.c
    @@ -1345,6 +1345,7 @@ static int op_get_configuration(struct libusb_device_handle *handle,
            } else {
                    r = usbfs_get_active_config(handle->dev,
                                                _device_handle_priv(handle)->fd);
    +               *config = r;
            }
            if (r < 0)
                    return r;
