### ISSUE TITLE
Segmentation fault when passing a NULL value in libusb_bulk_transfer and libusb_interrupt_transfer

### ISSUE THREAD

**Issue by rgfernandes** [libusb/libusb#139]
I've got a segmentation fault when running the following code:

    r = libusb_bulk_transfer( devh, 0x02, data, 31, NULL, 1000);

Using the debugger, I discovered that the NULL argument (int *transferred) is causing the crash.
I have no interest in length of transfered data because it is a bulk out transfer.
So, I think anyone should be able to use a NULL argument.
I made a patch to libusb against the master branch to libusb_bulk_transfer accept this argument as NULL.

    diff --git a/libusb/sync.c b/libusb/sync.c
    index 0d1acd8..ee5a09f 100644
    --- a/libusb/sync.c
    +++ b/libusb/sync.c
    @@ -188,7 +188,9 @@ static int do_sync_bulk_transfer(struct libusb_device_handle  *dev_handle,
     
            sync_transfer_wait_for_completion(transfer);
     
    -       *transferred = transfer->actual_length;
    +       if(transferred) {
    +         *transferred = transfer->actual_length;
    +       }
            switch (transfer->status) {
            case LIBUSB_TRANSFER_COMPLETED:
                    r = 0;

**Comment by hjelmn** [comment]
If we decide to make this change we should update the documentation to indicate that NULL is valid for the transferred field.
