### ISSUE TITLE
int num_urbs = tpriv->num_urbs; // segfault

### ISSUE THREAD

**Issue by Ingener74** [libusb/libusb#14]
struct libusb_transfer *transfer = USBI_TRANSFER_TO_LIBUSB_TRANSFER(itransfer);
struct linux_transfer_priv *tpriv = usbi_transfer_get_os_priv(itransfer);
int num_urbs = tpriv->num_urbs; // < -- segfault here
int urb_idx = 0;
int i;

Signal : SIGSEGV:Segmentation fault)	
handle_iso_completion() at linux_usbfs.c:2,275 0x7ffff6e08d55	
reap_for_handle() at linux_usbfs.c:2,480 0x7ffff6e08d55	
op_handle_events() at linux_usbfs.c:2,529 0x7ffff6e08d55	
handle_events() at io.c:2,052 0x7ffff6e0389b	
libusb_handle_events_timeout_completed() at io.c:2,137 0x7ffff6e04473	
libusb_handle_events() at io.c:2,213 0x7ffff6e0453f	
_uvc_handle_events() at init.c:89 0x4e5d69	
start_thread() at pthread_create.c:312 0x7ffff6b1a182	
clone() at clone.S:111 0x7ffff612530d

**Comment by dickens** [comment]
I believe that this will really only occur if the transfer has been freed before it was completed. The transfer private data (tpriv) can only be invalid if the transfer itself is invalid.

**Comment by dickens** [comment]
Since no further issues have been reported by OP or others, closing.
