### ISSUE TITLE
Opening the AX201 Bluetooth device causes a blue screen

### ISSUE THREAD

**Issue by ggaudeau** [libusb/libusb#1490]
libusb 1.0.26
usbdk 1.00.22

When calling the `libusb_open` method with the wireless controller AX201 Bluetooth, I always get a bsod **WDF_VIOLATION (10d)**.

Reproduced with several laptops with Bluetooth driver enabled. 

Workaround found for the moment is to filter all devices belonging to `LIBUSB_CLASS_WIRELESS` class.

[windbg.txt](https://github.com/libusb/libusb/files/15163024/windbg.txt)

**Comment by mcuee** [comment]
I will suggest not to use usbdk as it seems to be more and more problemtatic.
