### ISSUE TITLE
Examples: to port testlibusb example from libusb-compat-0.1

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb#150]
Ref: http://marc.info/?l=libusb-devel&m=145639098209030&w=2

Nathan's version: https://github.com/hjelmn/libusb-darwin/blob/master/examples/testlibusb1.c

I think testlibusb is a better example than listdev.

**Comment by anilgit90** [comment]
The library call snprintf is only supported in VS 2015, for VS 2015 below we have to add a flags to check for snprintf . testlibusb works and builds in VS 2015, let me know what can we do to standardize it.

**Comment by mcuee** [comment]
The example is included in 1.0.21 release. The windows port can be in Ticket #151 .
