### ISSUE TITLE
Getting LIBUSB_TRANSFER_ERROR when working in USB 3.2 port

### ISSUE THREAD

**Issue by pramod-kg-sndk** [libusb/libusb#1518]
I was working in Ubuntu 22.04 PC, where I have a script to send SCSI command to device in UAS mode. It is working properly in USB 2.x ports( taken care of read ready and write ready IUs), but showing LIBUSB_TRANSFER_ERROR when requesting for status IU after the command transfer complete. This is happening with Test Unit Ready command. I would like to know why it is throwing error while requesting status. 
Could some can help me to resolve this issue?

**Comment by mcuee** [comment]
Probably nothing to do with libusb but the underlying kernel.
