### ISSUE TITLE
Bulk Async received error data when start

### ISSUE THREAD

**Issue by chenzhaoting** [libusb/libusb#1546]
![image](https://github.com/user-attachments/assets/31737172-558f-4126-bdf1-6ba6ef9520f4)
![89d054eefeb5149df846b09ae8254a50](https://github.com/user-attachments/assets/7a68df6f-63d1-4c2b-8c81-50efb52a3920)
when start transfer somedata,there is a error data in callback and in bus hound all data is correct, after that all receive was  corrrect.

**Comment by mcuee** [comment]
Please read the guide below and provide more information about the OS, libusb version used and info about your device.
https://github.com/libusb/libusb/wiki/Troubleshooting

**Comment by chenzhaoting** [comment]
> Please read the guide below and provide more information about the OS, libusb version used and info about your device. https://github.com/libusb/libusb/wiki/Troubleshooting
> 
> I also think Bus Hound is not a good tool. You may need a real HW USB analyzer to handle low level issues.



> Please read the guide below and provide more information about the OS, libusb version used and info about your device. https://github.com/libusb/libusb/wiki/Troubleshooting
> 
> I also think Bus Hound is not a good tool. You may need a real HW USB analyzer to handle low level issues.

use The Latest release Vs2022 libusb-1.0.27.7z MS64, and the event is processed  by a  thread.
#include "winusbdriver.h"
#include "QDebug"
#include "usbthread.h"


#define     DBG(X)  qDebug()<<(X)<<endl


void WinUSBDriver::close_usb1()
{
    release_usb();
}

WinUSBDriver::WinUSBDriver()
{
 
}

#define USB_VID         0x07E4          //USB的产商ID
#define USB_PID         0x07E4          //USB的产品ID

#define EP0ADDR         0x01            //Write端口0地址，通道0
#define EP1ADDR         0x81            //Read 端口1地址，通道1
#define EP2ADDR         0x02            //Write端口2地址，通道2
#define EP3ADDR         0x86            //Read 端口3地址，通道3

#define USB_TIMEOUT     200            //传输数据的时间延迟

libusb_context* m_libusb_context;

typedef union convert
{
    unsigned char buf[4];
    int32_t data;
}union_cov;

uint8_t *ptr;

void LIBUSB_CALL WinUSBDriver::completeCallback(libusb_transfer *xfer)
{
    WinUSBDriver *driver = (WinUSBDriver *)xfer->user_data;
    
    switch(xfer->status)
    {
        case LIBUSB_TRANSFER_COMPLETED:
        //DBG("recv %d",xfer->actual_length);
         //qDebug()<<"recv_len:"<<xfer->actual_length<<endl;

            if(xfer->actual_length > 0){
                
                driver->recv_len = xfer->actual_length;
                memcpy(driver->recv_buf_tmp,xfer->buffer,xfer->actual_length);

                for (int64_t i = 0; i < xfer->actual_length; i += 4)
                {
                    union_cov test1;
                    test1.buf[0] = xfer->buffer[i];
                    test1.buf[1] = xfer->buffer[i + 1];
                    test1.buf[2] = xfer->buffer[i + 2];
                    test1.buf[3] = xfer->buffer[i + 3];

                    if (test1.data == 0)
                    {

                        qDebug() << "err1"<< test1.data;
                    }
                }
                ptr = driver->recv_buf_tmp;
                emit driver->recvSignals(driver->recv_buf_tmp,driver->recv_len);
               qDebug() << "driver->recv_len"<< driver->recv_len<<  driver->recv_buf_tmp[0]<< driver->recv_buf_tmp[1]<<endl;
            }
        
                             
        break;
        case LIBUSB_TRANSFER_CANCELLED:
            DBG("LIBUSB_TRANSFER_CANCELLED");
            return;
            break;
        case LIBUSB_TRANSFER_NO_DEVICE:
            DBG("LIBUSB_TRANSFER_NO_DEVICE");
            break;
        case LIBUSB_TRANSFER_TIMED_OUT:
            DBG("LIBUSB_TRANSFER_TIMED_OUT");
            break;
        case LIBUSB_TRANSFER_ERROR:
            DBG("LIBUSB_TRANSFER_ERROR");
            break;
        case LIBUSB_TRANSFER_STALL:
            DBG("LIBUSB_TRANSFER_STALL");
            emit driver->disconnectSignals();
            
            break;
        case LIBUSB_TRANSFER_OVERFLOW:
            DBG("LIBUSB_TRANSFER_OVERFLOW");
            break;
        default:
        break;
    }

    if(driver->is_open)
    {
        int r = libusb_submit_transfer(xfer);
        if( r < 0 ){
            qDebug() << "fail to re-submit transfer";

            if (xfer) {
                libusb_cancel_transfer(xfer);
                xfer = NULL;
            }
            driver->usb_thread->close();
            //if (driver->dev_handle != NULL)
               // libusb_release_interface(driver->dev_handle, 0);
          
            //if (driver->dev_handle != NULL)
                //libusb_close(driver->dev_handle);
            /*
            if (m_libusb_context) {
                libusb_exit(m_libusb_context);
                m_libusb_context = NULL;
            }*/
            //driver->is_open = false;
            
        }    
    }

}



int WinUSBDriver::open(int vid,int pid)
{
    
    int error = 0,i = 0;
    dev_handle = NULL;

    if (usb_thread == nullptr)
        usb_thread = new USBThread();
    connect(this->usb_thread, &USBThread::close_usb, this, &WinUSBDriver::close_usb1, Qt::UniqueConnection);

    
    ret = libusb_init(&m_libusb_context);
	if (ret < 0) {
        
		DBG("failed to initialise libusb");
        
        error =1;
        goto init_fail;
    }else{
        DBG("initialise libusb success");
    }

    
//    dev_handle = libusb_open_device_with_vid_pid(m_libusb_context, vid, pid);
//    if (dev_handle == NULL) {
//        DBG("Cannot open device\n");
//    }
//    else {
//        DBG("Device Opened\n");
//    }
    
    ret = libusb_get_device_list(m_libusb_context, &devs);
    if (ret < 0)
    {
        DBG("get usb device list error when open");
        error =1;
        goto get_list_fail;
    }else{
        DBG("libusb_get_device_list success");
    }
    
    while ((dev = devs[i++]) != NULL)
    {
        //DBG("start to get device descriptor");
        ret = libusb_get_device_descriptor(dev, &desc);
        if (ret < 0) {
            DBG("failed to get device descriptor");
            error =1;
            goto fail;
        }else{
           //  DBG( "Find VID:%02X PID:%02X",desc.idVendor,desc.idProduct);
            if(desc.idVendor == vid && desc.idProduct == pid)
            {
                
                ret = libusb_open(dev, &dev_handle);
                if (ret < 0)
                {
                    dev_handle = NULL;
                    DBG("fail to open usb device");
                    error =1;
                    goto open_fail;
                }else{
                    DBG("libusb_open success");
                    break;
                }
            }
        }
    }
    libusb_free_device_list(devs, 1);
    
    if(dev_handle == NULL)
    {
        DBG("fail find device");
        error = 1;
        goto find_device_fail;
    }
    
    ret = libusb_get_active_config_descriptor(dev, &cfg);
    if (ret < 0){
        DBG("Fail to get device config_descriptor");
        error =1;
        goto get_config_fail;
    }else{
        DBG("libusb_get_active_config_descriptor success");
    }
    
    for (int j = 0; j < cfg->bNumInterfaces; j++){
        const struct libusb_interface_descriptor *interface_desc = (cfg->interface+j)->altsetting;
        //DBG("bInterfaceNumber:%d",interface_desc->bInterfaceNumber);
        //DBG("bNumEndpoints:%d",interface_desc->bNumEndpoints);
    }
    
    libusb_free_config_descriptor(cfg);
    
    ret = libusb_detach_kernel_driver(dev_handle,0);
    if(ret < 0){
        DBG("Fail to libusb_detach_kernel_driver");
        DBG(ret);
    }
    
    ret = libusb_claim_interface(dev_handle,0);
    if(ret < 0){
        DBG("Fail to libusb_claim_interface");
    }
    
    m_xfer = libusb_alloc_transfer(0);
    
    libusb_fill_bulk_transfer(m_xfer,
                        dev_handle,
                        EP1ADDR, // Endpoint ID
                        recv_buf,
                        RECV_LEN,
                        WinUSBDriver::completeCallback,
                        this,
                        USB_TIMEOUT
                        );
    
    if(m_xfer){
        ret = libusb_submit_transfer(m_xfer);
        if( ret < 0 ){
            libusb_free_transfer(m_xfer);
            m_xfer = 0;
            error =1;
            goto fail;
        }
    }

    usb_thread->start();
   
    is_open = true;
    return 0;

fail:   
    DBG("fail kk");
    libusb_cancel_transfer(m_xfer);
    get_config_fail:
    open_fail:
    libusb_close(dev_handle);
    get_list_fail:
    libusb_free_device_list(devs, 1);
    find_device_fail:
    init_fail:
    libusb_exit(m_libusb_context);
    return error;
}

void WinUSBDriver::send(QByteArray byte)
{
    if(is_open)
    {
        libusb_bulk_transfer(dev_handle,EP0ADDR,(unsigned char *)byte.data(),byte.length(),NULL,0xFFFF);
    }
    
}

bool WinUSBDriver::get_open_state()
{
    return is_open;
}


void WinUSBDriver::release_usb()
{
    if (m_xfer) {
        libusb_cancel_transfer(m_xfer);
        m_xfer = NULL;
    }
    if (dev_handle != NULL)
        libusb_release_interface(dev_handle, 0);

    if (dev_handle != NULL)
        libusb_close(dev_handle);

    if (m_libusb_context) {
        libusb_exit(m_libusb_context);
        m_libusb_context = NULL;
    }
    is_open = false;
}



int WinUSBDriver::close(void)
{
    if(usb_thread->isFinished()==false)
        usb_thread->close();

    return true;
}


###########  the thread code is ##############
void USBThread::run()
{
    m_mutex.lock();
    is_stop=false;
    m_mutex.unlock();


   // qDebug()<<"libusb thread "<<this->thread()->currentThreadId() << endl;

    while(true)
    {
        int ret = 0;
       
        if (is_stop == false)
        {
          //  qDebug() << "libusb thread "<< is_stop;
            ret = libusb_handle_events(NULL);
           // qDebug() << "libusb thread out ";
        }
       
  
        
        msleep(10);
       // QMutexLocker locker(&m_mutex);
        if (is_stop || ret != 0)
        {
           // qDebug() << "begin usb thread exit";
            break;
        }
    }
    qDebug()<<"usb thread exit";
    emit close_usb();


}

**Comment by chenzhaoting** [comment]
![image](https://github.com/user-attachments/assets/e564b57d-c4f2-495b-94bd-2fd9fb3c9d4d)

**Comment by tormodvolden** [comment]
Please see https://libusb.sourceforge.io/api-1.0/group__libusb__asyncio.html first, then
https://libusb.sourceforge.io/api-1.0/group__libusb__poll.html#ga4989086e3f0327f3886a4c474ec7c327
(I think we need to update the first text to not use libusb_handle_events.)

Your threadFunction() should use libusb_handle_events_completed().

Since libusb_handle_events_completed() uses blocking mode there is no reason to sleep in the loop. You should process events as fast as possible and more often than every 10 seconds.

To keep things simple, please change the `#if` in  your example to use threadFunction() directly instead of your handling thread.
