### ISSUE TITLE
MAC OS use libusb to handle a usb storage with FAT32 filesystem with a system warning  "disk not ejected properly"

### ISSUE THREAD

**Issue by benbryantzoro1** [libusb/libusb#1559]
when I use libusb to handle a USB storage with FAT32 filesystem, the system warning "disk not ejected properly", if I unmount the disk ,the system no warning again, it also happend that device gets string descriptor timeout. can libusb release device interface  unmount disk auto? maybe other idea?

**Comment by mcuee** [comment]
Wrong libary to use.

libusb is not the right library to use for your use case.
