### ISSUE TITLE
linux_usbfs.c functions

### ISSUE THREAD

**Issue by AaronIngE** [libusb/libusb#1562]
I would like to know in which .h file are the functions of the source code to linux_usbfs.c?

Specifically, the get_usbfs_fd function. I have tried to compiling a code that uses the function, but I have gotten an error because the function is not defined.

I didn't find these functions in the libusb .h files.

**Comment by mcuee** [comment]
> I would like to know in which .h file are the functions of the source code to linux_usbfs.c?
> 
> Specifically, the get_usbfs_fd function. I have tried to compiling a code that uses the function, but I have gotten an error because the function is not defined.
> 
> I didn't find these functions in the libusb .h files.

That is not a public function. You can not use it.
https://github.com/libusb/libusb/blob/467b6a8896daea3d104958bf0887312c5d14d150/libusb/os/linux_usbfs.c#L185
