### ISSUE TITLE
ps5 controller no longer working after instaled driver

### ISSUE THREAD

**Issue by bryn0783** [libusb/libusb#1566]
I was trying to play Mario kart using my ps5 controller, and assumed it would work like a Gameboy one, so I tried to set it up in that manner, downloading the driver for it as shown in https://www.youtube.com/watch?v=yxpOuxL3YVQ this YouTube video. Now my ps5 controller is not recognised by my pc, so I am unable to use it at all, even for other games. Any ideas how to fix this?

**Comment by mcuee** [comment]
You have to revert the driver to the original driver.

**Comment by mcuee** [comment]
Please use github Discussions or libusb-devel mailing list for technical support. github issue is for reporting issues.

github libusb Discussions:
https://github.com/libusb/libusb/discussions
