### ISSUE TITLE
Support cmake compilation

### ISSUE THREAD

**Issue by Mangomm** [libusb/libusb#1590]
When can the author support cmake compilation, when my project is a cmake project, I want to embed the libusb source code, but find it a bit difficult, because libusb currently uses autogen.sh on linux, and uses a separate msvc project on windows, which gives people like me, It is a little inconvenient for developers who want to embed the source code into their projects and cross platform

**Comment by mcuee** [comment]
https://github.com/libusb/libusb-cmake
