### ISSUE TITLE
Add Solaris backend

### ISSUE THREAD

**Issue by leilchen** [libusb/libusb#169]
Many applications turn to libusb 1.0 API. Solaris needs to support that set of APIs.

**Comment by mcuee** [comment]
Not so sure how many people are using Solaris, but that will be good.
Probably the existing OpenUSB Solaris Backend can be the starting point.

Ref: https://sourceforge.net/projects/openusb/

BTW, OpenUSB seems to be inactive now since the last commit is on
24-June-2013.

**Comment by leilchen** [comment]
On Thu 2016-Mar-10 16:57 PM mcuee wrote:
> Not so sure how many people are using Solaris, but that will be good.
There's requirement. I'll work on it.

> Probably the existing OpenUSB Solaris Backend can be the starting point.
>
> Ref: https://sourceforge.net/projects/openusb/
>
> BTW, OpenUSB seems to be inactive now since the last commit is on
> 24-June-2013.
As the maintainer of that project, I feel depressed. But as you said, that'll be a starting point for libusb 1.0 implementation.

Thanks,
Lei Chen

**Comment by hiyuh** [comment]
pull request #177 is closed, so close this issue too?

**Comment by leilchen** [comment]
Yes, please go ahead with proper procedures.

Thanks,

Lei Chen
