### ISSUE TITLE
Is it possible write unit tests for libusb

### ISSUE THREAD

**Issue by CAMOBAP795** [libusb/libusb#173]
I have user-space driver. And I wanna to cover it by some unit tests.

I have prepared raw ISOC data (test data)

I see some beginnings [here](https://github.com/libusb/libusb/tree/master/tests) but looks like for now no possible to mock response output

How can I mock libusb somehow to achieve this?

**Comment by CAMOBAP795** [comment]
After code review, looks like there is no possibility for now.

According current architecture, test feature can be accomplished by own implementation of `struct usbi_os_backend` which will provide test interface to mock usb_request

It will be nice to hear some critics of this approach

**Comment by mcuee** [comment]
Feature request is better discussed in the mailing list. Close this one as it is aging.
