### ISSUE TITLE
Merge usb zerocopy patch

### ISSUE THREAD

**Issue by xlz** [libusb/libusb#175]
The patch is here http://thread.gmane.org/gmane.comp.lib.libusb.devel.general/22679/focus=22798 (with one issue remained).

The kernel support has been merged to mainline https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=f7d34b445abc00e979b7cf36b9580ac3d1a47cd8.

**Comment by mcuee** [comment]
IMHO it will be better that you reply to that email than creating a new
ticket.

**Comment by mcuee** [comment]
You may need to subscribe to the libusb mailing list in order to post
to the mailing list.
URL:   https://lists.sourceforge.net/lists/listinfo/libusb-devel

**Comment by xlz** [comment]
Linux 4.6 is released with usbfs zerocopy support. This should be merged.

**Comment by dickens** [comment]
Closed via a283c3b5
