### ISSUE TITLE
Android 6.01 not supported by libUSB -  libusb_init -99

### ISSUE THREAD

**Issue by nilstk** [libusb/libusb#191]
Hello everyone,
on Android 6.01 in a native app (JNI) I'm getting error -99, which seems to be caused by SEAndroid, since it's enforced now. Setting setenforce to 0 with root rights fixes the issue for me, but not for customers, of course.

Is there any solution for non-rooted devices? Does it need light modifications maybe only or is it not fixable? Otherwise i'd appreciate some sample source code on how to get it working. Thanks.

**Comment by mcuee** [comment]
As mentioned in the other issue #188 , the situation for libusb under Android is a bit unfortunate (nobody came up to libusb mailing list and offer to help to sort out the issue). Before that is sorted out, I guess to go back to the Android native USB Host API is the way to go.

**Comment by mcuee** [comment]
If you want, please continue on issue #188. I will close the issue here.
