### ISSUE TITLE
Device Manager "Group"

### ISSUE THREAD

**Issue by arrmo** [libusb/libusb#208]
Hi,

I installed libusb on two different Windows machines. On one, in Device Manager I see a group titled "libusb-win32", and my device (UPS) is inside there - perfect! On the second machine though, the device I applied libusb to shows up in a group of "Jawbone Devices", which seems very odd to me.

Thoughts?

Thanks!

**Comment by dickens** [comment]
This is a libusb-win32 issue, not a libusb issue. The project isn't in active development, so I don't know how much support you'll receive.

**Comment by arrmo** [comment]
NP, understood. But to figure this out (just curious) - there are updates still ongoing to the code ... but not active development? Just confused ... :(.

Thanks!

**Comment by mcuee** [comment]
For libusb-win32 support, please use libusb-win32 mailing list. It is a
separate project from libusb.

-- 
Xiaofan

**Comment by arrmo** [comment]
Ahhh - there is my confusion. Thanks for clarifying!
