### ISSUE TITLE
Call API libusb_claim_interface(handle, iface) return -3(LIBUSB_ERROR_ACCESS) (windows 7)

### ISSUE THREAD

**Issue by lookfuyao** [libusb/libusb#213]
Dear,
     I use xusb to test my usb device, like title said, it cannot call libusb_claim_interface success, I debuged the program step by step, I found my device will call winusbx_claim_interface, and failed at get_interface_details_filter for GUID_DEVINTERFACE_LIBUSB0_FILTER, actually is the function pSetupDiEnumDeviceInfo failed, GetLastError function return 259. 
    I don't konw what is the  GUID_DEVINTERFACE_LIBUSB0_FILTER?
    By the way, the libusb_win32's API usb_claim_interface is worked.
B&R,
Yordan.

**Comment by mcuee** [comment]
Please do not use libusb-win32 filter with libusb Windows. You should use WinUSB. Or you can look at usbdk as well.
