### ISSUE TITLE
libusb_bulk_transfer bulk read return 0 but buffer is empty

### ISSUE THREAD

**Issue by tinysniper** [libusb/libusb#216]
```
int libusb_bulk_transfer    (struct libusb_device_handle * dev_handle,
                             unsigned char  endpoint,
                             unsigned char *    data,
                             int    length,
                             int *  transferred,
                             unsigned int   timeout 
)   
```

The libusb_bulk_transfer returns 0(success) while bulk reading. 
And the actual read length `transferred` is the same as `length`. But the buffer readed `data` is empty with `0`. I don't understand what's wrong.
- Using zadig to install WinUSB driver
- libusb0(libusb-win32) works well while reading/writing
- Test is on Windows10

**Comment by mcuee** [comment]
Please provide more information. 
You may want to try the latest release version of libusb (1.0.21).
You may want to attach the debug log as well.

**Comment by tinysniper** [comment]
My libusb is right the 1.0.21.

**Comment by mcuee** [comment]
You need to provide more details, like what is the device, what your program is doing and probably the relevant codes as well.

**Comment by mcuee** [comment]
Will close this issue if no more details are provided within another week.
