### ISSUE TITLE
libusb_control_transfer return

### ISSUE THREAD

**Issue by kindleinthewind** [libusb/libusb#221]
I run dpfp.c to test  usb device CY7C68013 EZ-USB FX2 USB 2.0 Development Kit, but subfunction libusb_control_transfer return -7,  does it need to load firmware to usb device?

**Comment by kindleinthewind** [comment]
anybody help me?

**Comment by kindleinthewind** [comment]
my email is 442913397@qq.com

**Comment by mcuee** [comment]
You have to provide more details. This is more for bug report and not for technical support. Please subscribe to libusb mailing list and ask in the mailing list. Thanks.
