### ISSUE TITLE
libusb_get_device_list() cann't list USB 3.1 Device?

### ISSUE THREAD

**Issue by Tody-Guo** [libusb/libusb#227]
We have device Asmedia USB 3.1 device. When I plugin Type-C device, this function cann't list the devices.

**Comment by Tody-Guo** [comment]
I found that, if install Asmedia driver, libusb_get_device_list() can't list the device, but use inbox-driver of asmedia 3.1 driver. libusb_get_device_list() functon can list deivces.

**Comment by hjelmn** [comment]
Need more info. Is this windows?

**Comment by Tody-Guo** [comment]
Yes, in windows. But, there is something strange. First time, libusb_get_device_list() can list the device, then plug-out type-c device and plug-in other side libusb_get_device_list() can still list the device. but when change it back to original side, libusb_get_device_list() can't list the type-c devices. type-c device is missing. I use another tool to check. it is fine. but libusb_get_device_list() can't list the type-c devices. 
then reboot the system, libusb_get_device_list()  works. if  you try again, libusb_get_device_list() can't list type-c device, too.

**Comment by diabolo38** [comment]
what windows version ? 
you can  expect strange issue with win 7 cos usb 3.0 3.1 support is done by device driver and it may not implement all ioctl use by libusb enumeration.
For instance strange enumeration issue (single port work and port may swap) occur on TI xhci controller .

**Comment by Tody-Guo** [comment]
Windows 10 14393.

**Comment by mcuee** [comment]
If the Windows inbox driver works but ASMedia driver does not work, it is
quite possible the name of the hub driver is not included in libusb Windows
backend yet. What is the hub driver name listed under Device Manager for
the ASMedia driver? Right now the one included for ASMedia is ASMTHUB3.

In libusb/os/windows.c file, look at the line const char* hub_driver_names[]

**Comment by mcuee** [comment]
I just googled and find out that the hub driver for ASMedia driver is still ASMTHUB3. Based on your description, it is a bit strange. I am wondering what you have done. Take note that libusb Windows does not support hotplug as of now. You may need to wait for sometime before you run libusb_get_device_list().

**Comment by mcuee** [comment]
Will close this issue for now. It may be related to ASMedia driver. 
To OP: please reopen this issue if you have more info.

**Comment by ArnonCh** [comment]
Hi,

I'm facing the same problem as described by Tody-Guo.
My windows version is 8.1 pro.

I tried to debug it and see where it fails - 
Inside the function **_init_device_** (windows_winusb.c)
When it calls the funcion **_DeviceIoControl_** with **_IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX_** it fails with the error of no device connected

**Comment by photron** [comment]
I had problems with an ASMedia hub on Windows before and in my case the enumeration changes in libusb 1.0.22-rc3 have fixed the problem now.
