### ISSUE TITLE
Where is `INSTALL` file?

### ISSUE THREAD

**Issue by kuanyen** [libusb/libusb#235]
```
Installation Instructions for Windows
*************************************

If you are compiling for MinGW or cygwin, please refer to the INSTALL file.
```
But I don't find any INSTALL file.

**Comment by mcuee** [comment]
INSTALL file is generated when running autogen.sh or bootstrap.sh when running under Linux, Mac OS X or Cygwin or MSYS/MSYS2.

**Comment by GPery** [comment]
Considering the fact it's referenced in INSTALL_WIN.txt which exists off the bat, it might be worth mentioning there.

**Comment by E3V3A** [comment]
Yes please! Please add a separate and more clear INSTALL file.
For example. I would like to just compile the *examples* without having to re-compile the entire library.  
How can I do this using MinGW on x64??

**Comment by LudovicRousseau** [comment]
The `.tar.bz2` archives in https://github.com/libusb/libusb/releases contains the `INSTALL` file you are looking for.
I don't know if we must keep this issue open.
