### ISSUE TITLE
Find device type

### ISSUE THREAD

**Issue by Waishon** [libusb/libusb#240]
Hi,

whats the proper way to check if a connected usb device is a keyboard or a mouse?

It should be possible to check where it is mounted, but is it also makeable with libusb?

**Comment by diabolo38** [comment]
usb keyboard/mice are HID class  device inspecting interface/device  descriptor class/subclass/prootcol field tell  you what they are . But deeper HID descriptor analyses may be required to find out if it is "a regular keyboard"  and/or mousse  or just a key in an headset etc ..

i'm scared your requirement is out of lib scope.

**Comment by mcuee** [comment]
I think this is a question and it is better to ask in libusb mailing list. You may need to provide more details of what you want to achieve and what is the OS of concern.

**Comment by mcuee** [comment]
Close this issue here. If the OP wants to pursue further, please ask in the mailing list.
