### ISSUE TITLE
libusb doesn't find virtual USB devices

### ISSUE THREAD

**Issue by nickich** [libusb/libusb#251]
I'm using Eltima Network Gate on Windows 7 to access remote devices, but libusb doesn't find them properly.
When I run listdevs, the virtual devices came up with Linux VID/PID.
I was looking at 'windows_winusb.c' and it seems that it thinks the devices are hubs...

> 8086:8c2d (bus 2, device 1)
> 8086:8c26 (bus 1, device 1)
> 046d:c52b (bus 3, device 2) path: 2
> 1d6b:0001 (bus 4, device 1) path: 1
> 0c45:64d0 (bus 2, device 3) path: 1.5
> 8087:07da (bus 1, device 3) path: 1.5
> 8087:8000 (bus 1, device 2) path: 1
> 8087:8008 (bus 2, device 2) path: 1
> 8086:8c31 (bus 3, device 1)
>

**Comment by mcuee** [comment]
I think this is the correct behavior since it acts a virtual USB hub for the network device. Why do you think it is a bug? What is the issue you are facing?

**Comment by nickich** [comment]
It's actually a virtual USB device. The libusb thinks it is a hub and since it can't get its VID/PID, libusb assigns Linux ones. 
Same virtual device is recognised and enumetated properly by other sw.

**Comment by mcuee** [comment]
No I do not think this is true. It is not a virtual USB device. Rather those remote USB device connect to it is a virtual USB device. Itself is a virtual HUB. If it is a USB device, virtual or real, it will have a USB VID/PID.

Ref: http://www.eltima.com/products/usb-over-ethernet/

**Comment by nickich** [comment]
The remote device connects as a virtual device on a local machine. This virtual device has PID/VID, but the libusb doesn't recognize it as such.

**Comment by mcuee** [comment]
Please refer to Pull Request 257. https://github.com/libusb/libusb/pull/257
