### ISSUE TITLE
WebUSB support on Windows requires custom driver

### ISSUE THREAD

**Issue by larsgk** [libusb/libusb#259]
It seems strange that a custom WinUSB driver is needed for libusb in order to work.  Shouldn't it be possible 'just' to work on directly supporting e.g. the latest WinUsb driver shipping with windows (that loads automatically with the right MS OS 1.0 descriptors in place):

https://bugs.chromium.org/p/chromium/issues/detail?id=637404

**Comment by mcuee** [comment]
I do not understand you, libusb does not need a custom WinUSB driver. It supports those WCID USB device with the proper MS OS descriptors in place. Please post more information.

**Comment by mcuee** [comment]
Since you are using a composite device with CDC + custom, I think you are using IAD. I am not so sure if you hit the current libusb Windows backend's limitation or not.
https://github.com/libusb/libusb/issues/85

**Comment by mcuee** [comment]
https://github.com/WICG/webusb/issues/75
Pete is helping there.

**Comment by mcuee** [comment]
From what I read, this issue does not seem to relate to libusb Windows, rather the FW is not working very well under Windows.

**Comment by mcuee** [comment]
I am closing this as the conclusion is that libusb is not the issue (other than the IAD issue covered in ticket #85.
