### ISSUE TITLE
usbdk Compatibility with virtual box host (Win7-64)

### ISSUE THREAD

**Issue by diabolo38** [libusb/libusb#264]
Under win7-64 (home edition) using virtual-box 5.1.12 r112440 (Qt5.6.2) to use an usb device in guest os  i had to play with  registry editor and delete an entry "upfilter" or alike  that was  "Usdbk" . Is this a know issue  kind of linked to dual filter and some default set to usdbdk ?  
I came to this solution described in many virtual box forum post  like here https://forums.virtualbox.org/viewtopic.php?f=2&t=37326

**Comment by mcuee** [comment]
I think this is not related to the libusb usbdk backend, but rather usbdk itself. Will close this ticket for now. You can raise the issue in usbdk site.
