### ISSUE TITLE
Stop supporting Windows XP?

### ISSUE THREAD

**Issue by dickens** [libusb/libusb#267]
Can we, please? We are approaching the three year anniversary of Microsoft's official end of support. There could be some notable simplifications to the Windows threading code.

**Comment by mcuee** [comment]
I support this. We can release 1.0.22 as the last Windows XP supported release or even declare 1.0.21 as the last version to support Windows XP.

**Comment by mcuee** [comment]
Based on the feedbacks from the mailing list, it is okay to drop Windows XP support.
