### ISSUE TITLE
xusb fails WCID/WinUSB Device test with non-ASCII vendor codes

### ISSUE THREAD

**Issue by Timmmm** [libusb/libusb#269]
The xusb example is supposed to let you test WCID/WinUSB devices. The way it works is it gets the 0xEE string descriptor, which is supposed to be ([excellent reference](https://github.com/pbatard/libwdi/wiki/WCID-Devices)) `M_S_F_T_1_0_0_#_` (where `_` is a null byte (it's UTF-16 sort of), and `#` is *any byte*). Windows then later sends requests with `bRequest` set to `#`.

Unfortunately in `xusb.c` it [uses `libusb_get_string_descriptor_ascii()`](https://github.com/libusb/libusb/blob/73d15d1f8eee372e0609d072f3df705f7de18214/examples/xusb.c#L933) to get the string descriptor, and [`libusb_get_string_descriptor_ascii()`](https://github.com/libusb/libusb/blob/73d15d1f8eee372e0609d072f3df705f7de18214/libusb/descriptor.c#L1183) converts all non-ASCII characters to `?`!

It should be a fairly simple fix.

**Comment by patstew** [comment]
I had the same problem independently. It's fixed in #276.
