### ISSUE TITLE
Massive performance problems on Windows

### ISSUE THREAD

**Issue by firesurfer** [libusb/libusb#27]
Hello,
i wrote an application which roughly transfers about 700 KB/s over a USB Connection as a bulk transfer. The usb device has 3 interfaces. Two of them are for a cdc connection, but at the moment i access them directly via libusb. The third interface has one in endpoint for the incoming data. 
On Linux i've got no problems transfering this amount of data. But on windows i only get around 40 KB/s. The USB device is a Atmel AVR32 Controller. I allready tried serveral versions of libusb and libusbx and various drivers (WinUSB and libusbk) but it didn't fix the error. I also tried using the synchronous interface instead of the async interface but it didn't work.

**Comment by pbatard** [comment]
These kind of questions are better addressed directly to the mailing list. Closing.
