### ISSUE TITLE
libusb: warning [submit_iso_transfer] submiturb failed, transfer too large [LINUX]

### ISSUE THREAD

**Issue by aurquiel** [libusb/libusb#270]
Hello i am trying to receive an isochronic transfer but i always fail send it back the message 

**libusb: warning [submit_iso_transfer] submiturb failed, transfer too large** 

I am using libusb 1.0.21 kernel linux 4.9.9

I am trying to receive packets MPEG_TS of multimedia type, using high speed usb configuration.

Here is a piece of the my code 

```
    libusb_transfer *transfer;

    transfer = libusb_alloc_transfer(16);

    int pktsize_in = libusb_get_max_iso_packet_size(the_device, 130);

    int len = pktsize_in*16;   
    unsigned char *MEPEG2_TS = new unsigned char[len];  // To recieve the data

    libusb_fill_iso_transfer(transfer, device_handle, 130, MEPEG2_TS, len, 16, NULL, NULL, 0 );
    libusb_set_iso_packet_lengths(transfer, pktsize_in);
    transfer->flags = LIBUSB_TRANSFER_FREE_BUFFER | LIBUSB_TRANSFER_FREE_TRANSFER;
    libusb_submit_transfer(transfer);

```

I was reading another issue 
https://github.com/libusb/libusb/issues/119

MAYBE  the packet i am trying to receive is too large for linux kernel handle, but there are things i don't understand

> First, if bMaxBurst is 15, then you should use 16 (bMaxBurst + 1). 1024*15*3*128  is 5.625MB. The buffer is too large for linux kernel to allocate. See #118. For now you can use ISO_PACKET_CT = 64.

The descriptor of my endpoint
```
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               1

```      
 Even if change to ISO_PACKET_CT = 16 i have the same issue

**UPDATE** the issue doesn't display in the descriptor of the endpoint i was made a mistake Transfer Type was declare as interrupt now change it to Transfer Type Isochronous

But the buffer doesn't fill it with anything and is returning a successful operation

Debug after submit the transfer
[67.634343] [00001137] libusb: debug [submit_iso_transfer] need 1 6144k URBs for transfer

**Comment by mcuee** [comment]
https://github.com/OpenKinect/libfreenect2/wiki/Linux-USB-Notes#other-usb-limits
 Not so sure if the above helps you or not. Or maybe you want to ask in the libusb mailing list.
