### ISSUE TITLE
API: Hotplug API Ideas

### ISSUE THREAD

**Issue by computerquip** [libusb/libusb#29]
I honestly don't like the hotplug API too much. I find it messy and over complicated. So I came up with some ideas that I'd like to discuss. They break API (heavily) but perhaps in the future, they can be of use. 

1) Callback registration. In reality, there's only two possible events, connect and disconnect. We should take advantage of that. We should also use a struct of data which has multiple advantages. One is that we can use that for recognition of the "hotplug driver" as I'm going to call it. Another is it reduces call overhead (not that big a deal) and another is that we can hold that data as const structure in global space which is much easier to fetch, if wanted. Here's what I propose.

Instead of 

```
int libusb_hotplug_register_callback(
    libusb_context * ctx,
    libusb_hotplug_event    events,
    libusb_hotplug_flag     flags,
    int     vendor_id,
    int     product_id,
    int     dev_class,
    libusb_hotplug_callback_fn  cb_fn,
    void *  user_data,
    libusb_hotplug_callback_handle *    handle 
)
```

Maybe we should do something along the lines of:

```
int libusb_hotplug_register(libusb_context*, libusb_hotplug_driver*, void *user_data);
```

libusb_hotplug_driver would be similar to as follows (by the way, there could be a lot more filter variables from what I see? For another issue I suppose...):

```
struct libusb_hotplug_driver {
    connect_callback_t on_connect;
    disconnect_callback_t on_disconnect;
    int flags;
    int vid;
    int pid;
    int dev_class;
};
```

The callback signatures change in this idea, and they are discussed below. It's almost the exact same as the data passed to the function before but in the form of a struct and comprehensive. We no longer have to make multiple registration calls per each event. flags is the same and would have the same effect.

(EDIT: I realize you don't have to make multiple registration calls and can use one with a switch or if statement to determine what type of event is being called. I don't think that's ideal... it splits the function into two sections anyways, making the purpose of forcing the two events to be dealt with in two different callbacks more viable.)

More noticeably, the handle was removed. "Now we can no longer deregister?". In practicality though, we can use libusb_hotplug_driver\* passed to the register function to determine what to unregister, which is easy for the user to accomplish, and should be easy to implement.

I also have a half desire to remove the user_data argument as I don't feel it solves any problem what so ever but I may just be overlooking that situation. So... RFC on that.

2) Callback signatures. There's only two of them in a hotplug, that's connect and disconnect. But they're different. With the above proposition, the callbacks would be slightly changed. They are as follows:

```
void (*connect_callback_t)(libusb_context *ctx, libusb_device *device, void *user_data)
```

and

```
void (*disconnect_callback_t)(libusb_context *ctx, libusb_device *device, void *user_data)
```

We don't want to individually unregister callback functions. At most, we want to unregister the entire "hotplug_driver" structure from being used. That's fair... a function special for that. That function would make sure that all devices associated with that structure that are connected, have their disconnect callbacks called on for clean up, and all newly created devices are not setup. If the user really wants to, they can register multiple hotplug driver structures... but I don't think that's a realistic issue. 

That's it for now! I don't think these are too far fetched. Please ignore the crappy names... I've never been good at naming things. If it gets positive feedback, I might implement them in a small fork and see how they look.

**Comment by computerquip** [comment]
I'm reopening the issue after various months. I still think the changes are valid although my branch will no longer work with upstream...

**Comment by mcuee** [comment]
If you still care for this idea, please discuss in the mailing lists. If not hearing back for another month, I will probably close this ticket.

**Comment by computerquip** [comment]
Didn't expect a comment almost two years later. Unfortunately, I've lost interest in the changes. I've also tried posting on the mailing list but it never seems to go through.

**Comment by mcuee** [comment]
Never mind, I will leave this ticket open just in case some one wants to discuss hotplug API improvement.

**Comment by dickens** [comment]
Is there any reason to leave this open?  We should try and clean up the issues list to real outstanding issues with the library and not technical or design discusssions.

**Comment by mcuee** [comment]
I agree. Close this for now.

TO OP: please submit the discussion to the mailing list instead.
