### ISSUE TITLE
Access validation by libusb_get_string_descriptor_ascii() call [libusb 1.0.21] Windows

### ISSUE THREAD

**Issue by SubHL** [libusb/libusb#292]
Hello,
I get an access validation by `libusb_get_string_descriptor_ascii()` call at this point in windows_winusb.c:

```C++
static int windows_get_config_descriptor_by_value(struct libusb_device *dev, uint8_t bConfigurationValue,
	unsigned char **buffer, int *host_endian)
{
	struct windows_device_priv *priv = _device_priv(dev);
	PUSB_CONFIGURATION_DESCRIPTOR config_header;
	uint8_t index;

	*buffer = NULL;
	*host_endian = 0;

	if (priv->config_descriptor == NULL)
		return LIBUSB_ERROR_NOT_FOUND;

	for (index = 0; index < dev->num_configurations; index++) {
		config_header = (PUSB_CONFIGURATION_DESCRIPTOR)priv->config_descriptor[index];
		if (config_header->bConfigurationValue == bConfigurationValue) {
```
**config_header** is in case of error == NULL!

This error occurs sometimes on Windows when the USB device is disconnected from the bus and I re-enumerate the device directly. In this case, the LibUsb will find the device even though it is physically disconnected from the USB bus.

I guess it is missing a check if **config_header** is NULL?

**Comment by dickens** [comment]
This was fixed by commit 92093a5924.
