### ISSUE TITLE
libusb_get_port_numbers is broken on Mac OS Sierra 10.12.4 (16E195)

### ISSUE THREAD

**Issue by mvp** [libusb/libusb#303]
My utility [uhubctl](https://github.com/mvp/uhubctl) is broken on Mac OS Sierra 10.12.4 (16E195) because `libusb_get_port_numbers()` always returns just 1 as list of port numbers in this call:
https://github.com/mvp/uhubctl/blob/master/uhubctl.c#L346

    int pcount = libusb_get_port_numbers(dev, port_numbers, MAX_HUB_CHAIN);

`pcount` returned is always `1` no matter which device it is called for. On older MacOS, it would return unique port_numbers of varying size, even running on exact same hardware.

This may be somehow related to #127.

**Comment by mvp** [comment]
Hi, can anyone from libusb team take a look at this? This is extremely annoying that `libusb_get_port_numbers()` does not return device topology :(

**Comment by mvp** [comment]
This seems to be fixed in 871eb299b9. Can we please have next libusb release?
OR, perhaps make sure that this is fixed in brew...

**Comment by hjelmn** [comment]
I agree. We will start discussing the next release soon.

**Comment by mvp** [comment]
Any ETA for next release? Not many homebrew users are technical enough to build libusb from HEAD to fix this issue :(

**Comment by mvp** [comment]
Any update on new release? libusb is broken on Mac OS Sierra :(

**Comment by mvp** [comment]
@hjelmn, any news on next release?

**Comment by lame-turtlez** [comment]
@hjelmn  we really need a new and working release. This is completely broken for 10.12 . Thank you for your hard work.,

**Comment by mvp** [comment]
@hjelmn, what are the expectations of having 1.0.22 release cut anytime soon?
According to [libusb 1.0.22 milestone](https://github.com/libusb/libusb/milestone/6), libusb 1.0.22 should have been released 2 weeks ago...

**Comment by hjelmn** [comment]
Sorry it took so long to get back to this. I will see where we are now. There are a couple things that were desired for 1.0.22 but I don't know what has been completed.

**Comment by mvp** [comment]
Any progress on getting 1.0.22 released?
It's been stalled in limbo for quite a while now...

**Comment by hjelmn** [comment]
Sorry about that. Was planning to do a release last month but there were multiple outstanding Windows issues that needed to be resolved. I have gotten tied up with travel the last couple of weeks but will be willing to take another look next week.

**Comment by dickens** [comment]
I've nearly finished resolving the Windows issues. There are multiple fixes that will improve many aspects of the Windows backend.

**Comment by mvp** [comment]
This problem is open for 5 months now. Can we just have release already? Sorry for being so impatient, but this is a lot of time to wait for simple release of what was fixed long time ago.

**Comment by mvp** [comment]
Full 6 months later, [libusb 1.0.22 milestone](https://github.com/libusb/libusb/milestone/6) is past due once again, and there is no evidence that blocking issues for it are going to be fixed anytime soon.

Can you please just cut 1.0.22 as is from trunk?

**Comment by mvp** [comment]
@hjelmn, @dickens: as far as I can tell, libusb-1.0.22-rc3 was out for a while, and it was supposed to be last release candidate.
Can you guys release libusb-1.0.22 now?

**Comment by dickens** [comment]
v1.0.22 has been released, closing this issue.
