### ISSUE TITLE
Android: Android build name correction

### ISSUE THREAD

**Issue by kuldeepdhaka** [libusb/libusb#31]
android/jni/libusb.mk

LOCAL_MODULE := libusb1.0
this should be
LOCAL_MODULE := usb-1.0

"lib" should be dropped as it is not required
"-" should be placed between "usb" and "1.0".

also appropriately update  android/jni/examples.mk 
why important: afaik naming system on desktop is libusb-1.0.so\* not libusb1.0.so*

**Comment by mcuee** [comment]
Refer to this pull request:
https://github.com/libusb/libusb/pull/143

**Comment by mcuee** [comment]
Close this aging ticket since it is captured in the above pull request. Please re-open if you think it is wrongly closed.

**Comment by iliis** [comment]
https://github.com/libusb/libusb/pull/143 was apparently never merged, so this issue still remains. I've ran into this when cross-compiling my own library that finds libusb via pkg-config (and thus looks for "libusb-1.0", i.e. with "-").

**Comment by mcuee** [comment]
Reopen this since it is mentioned in another ticket.

**Comment by mcuee** [comment]
Close this for now and please use #596 for further discussion.

**Comment by mcuee** [comment]
@adisuciu Does #596 cover this? I think #596 covers this so I closed this ticket. If it is not true, I will reopen this ticket.

**Comment by adisuciu** [comment]
I'm not an expert on the matter but I think this ticket is a prerequisite for #596 as you can see in the P.S at the end of #596. #596 proposes that the Android build script should also create a .pc file which would be even better for detecting the library.

**Comment by xloem** [comment]
@adisuciu do you have any idea on how to prevent breaking existing buildsystems that rely on the wrong library name?  Maybe an environment or make variable, or outputting two libraries, or waiting until a major version release?

Did anyone ever make a PR for this change?  I think it might be a different issue from #874 but I do see that my pr is getting used and it would be good to help other issues out if I can.  It's been so many years with this issue here unaddressed.

**Comment by adisuciu** [comment]
I think some kind of variable that changes the library name would be good.
When making without the variable, the script should say that the .so name would be deprecated and they should set the variable when making to be fully compatible in the future ?

**Comment by mcuee** [comment]
Reopen as this is still needed.
