### ISSUE TITLE
"do_sync_bulk_transfer " return error "LIBUSB_TRANSFER_ERROR"

### ISSUE THREAD

**Issue by gx598034749** [libusb/libusb#310]
What's reason maybe cause return "LIBUSB_TRANSFER_ERROR" ?
or what I need to do.

OS is Ubuntu Linux. GDB for interface and endpoint......all is OK.
Anyone help me?

**Comment by dickens** [comment]
Please provide a log file with LIBUSB_DEBUG set to 4.

**Comment by dickens** [comment]
Closing this since OP hasn't responded.
