### ISSUE TITLE
libusb return LIBUSB_CANCEL_ERROR error when using interrupt transfer in mac os

### ISSUE THREAD

**Issue by tluson** [libusb/libusb#317]
I'm using libusb library in my mac,  OS 10.11. I claim four endpoint, two for bulk type and another two for interrupt type. but, the interrupt endpoint transfer callback function return transfer cancel error in mac os, while the bulk callback function is okay. And with all the same code, there is not such error in windows 7 system. Here is my test code, and the return result.

Find fv device
Config: 1
interface nums: 1
eps nums: 4
alt setting nums: 1
Dat Count: 1
Dat Count: 2
Msg Count: 1
Dat Count: 3
Msg Count: 2
Msg EP: Stop

[listdevs.txt](https://github.com/libusb/libusb/files/1121168/listdevs.txt)

**Comment by dickens** [comment]
Can you provide a debug log? There might be some race going on with timeout handling since the OS doesn't handle timeouts for interrupt transfers.

**Comment by dickens** [comment]
No response, so closing this for now. The OP can reopen if there is additional information to provide.
