### ISSUE TITLE
Build: Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [libusb/libusb#32]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/libusb/libusb/blob/4e95d0e7f90ea8bb900df61ef6e6dd4bbece114c/configure.ac#L96)?

**Comment by mcuee** [comment]
Close aging ticket. Please re-open if you think it is wrongly closed.

**Comment by elfring** [comment]
Unfortunately, I can not reopen this issue myself here directly.
Why did you close it when the possible acceptance of the suggested software improvement was not clarified so far?

**Comment by LudovicRousseau** [comment]
@elfring maybe you should explain _why_ you think the change is important.
What problem exactly would it fix?

You can add comments here even if the bug is closed.

**Comment by elfring** [comment]
How do you think about to benefit more from current macros (like `AX_PTHREAD`) in the GNU Autoconf Archive?

**Comment by LudovicRousseau** [comment]
I don't think about any benefit.

You want to have something changed. Please document and justify why.

**Comment by elfring** [comment]
* Why do you usually perform special configuration checks in build scripts?
* How much do you care for software portability around the POSIX thread programming interface?

**Comment by LudovicRousseau** [comment]
@elfring it looks like you are a troll.
I have no time for that. I quit.
