### ISSUE TITLE
Add CMakeLists.txt file.

### ISSUE THREAD

**Issue by sahil56** [libusb/libusb#322]
I wish to create _CMakeLists.txt_ file for this project. Although VS solution files are provided, one might to create project files for other IDEs e.g. Code Blocks for building.

**Comment by hjelmn** [comment]
Don't think this is going to happen. It was discusses at length some time ago and it was determined that cmake is a solution in search of a problem. We already provide VS and Xcode projects.

**Comment by Youw** [comment]
For reference, help those who are trying to google this one: now there is a community-supported https://github.com/libusb/libusb-cmake
