### ISSUE TITLE
Add Conan support

### ISSUE THREAD

**Issue by uilianries** [libusb/libusb#323]
Hi!

Conan is a create tool for package management, it's different from other packages, as .rpm or .dpkg because it can export, build, test and deploy the project.

I created some support for libusb [here](https://github.com/uilianries/conan-libusb), but would be nice if the project provides it own recipe, as result, anyone could obtain libusb on any platform.

I can help libusb project to develop such feature.

**Comment by LudovicRousseau** [comment]
libusb does not provide configuration files to generate ``.rpm``or ``.deb`` files because these configuration files are better managed by RPM and Debian maintainers using there own tools.

I did not know Conan. I think it is best if you manage the Conan support files in your own repository.

**Comment by uilianries** [comment]
I appreciated your explanation. 

Thanks!
