### ISSUE TITLE
Misc: Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libusb/libusb#33]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html) ⇒ [main](https://github.com/libusb/libusb/blob/e11525c66c7dd2db466c8f5785ff0b37d6a99ec9/examples/dpfp.c#L417)
- [usbi_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [usbi_io_init](https://github.com/libusb/libusb/blob/12e9e3557979af218ddb40f1e221d7fc56596fe9/libusb/io.c#L1109)

**Comment by mcuee** [comment]
Close this aging request. Please re-open if you think it is wrongly closed.

**Comment by elfring** [comment]
Unfortunately, I can not reopen this issue myself here directly.

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Reconsider unchecked return values") a bit more.
Would you like to [detect every error situation](https://github.com/libusb/libusb/blob/a90331a3be0a7919dfd256d700c38cfad5718575/libusb/io.c#L1123 "Update candidate: usbi_io_init()") as early as possible?

**Comment by LudovicRousseau** [comment]
@elfring can you propose a patch as a Pull Request?

We need manpower to implement what you propose so if you do it yourself that would help a lot.

**Comment by elfring** [comment]
* Would you like to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "Development with AspectC++")?
  
  How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Description for aspect-oriented software development") in your software?

**Comment by LudovicRousseau** [comment]
Would YOU want to improve libusb?
If yes then please provide a patch.

**Comment by elfring** [comment]
How do you think about to integrate a development tool like [AspectC++](http://aspectc.org/Publications.php "Descriptions for AspectC++") into your software build process?
