### ISSUE TITLE
windows 7 Cannot Claim Interface 1

### ISSUE THREAD

**Issue by willKw** [libusb/libusb#330]
windows 7 x64 ,used zadig install winusb v6.1.7600.16385
libusb_claim_interface(dev_handle, 0); is ok
libusb_claim_interface(dev_handle, 1);  error,

return LIBUSB_ERROR_NO_DEVICE ,cypress's   endpoint 0/endpoint 1 support, 

why,help me  thanks

**Comment by mcuee** [comment]
Most likely this is due to driver installation -- install WinUSB driver as
the parent device driver and try again.

**Comment by mcuee** [comment]
Will close this if no further reply in one month.

**Comment by mcuee** [comment]
To make it easy, close this issue for now. If OP comes back with more info, I will reopen the issue.
