### ISSUE TITLE
Linux OS - can't set interface  to device with usb 3.0 host controller (xhci)

### ISSUE THREAD

**Issue by reemba** [libusb/libusb#333]
when using linux os (ubuntu 16.042 with update kernel 4.12.8)  with python (pyusb) and cypress usb device (FX3) ,
fail to set interface with wmaxpacketsize = 1024 * 3 (isod-3 , isochronous).

error was:
2017-08-23 19:27:04,888 DEBUG:usb.backend.libusb1:_LibUSB.set_interface_altsetting(<usb.backend.libusb1._DeviceHandle object at 0x7f085574ea50>, 0, 1)
Exception occur: [Errno None] Other error

**this bug occur only with usb3.0 host controller (xhci).**
attached files:
1. cypress descriptor 
2. linux_usb_dmesg 
3. py_debug_libusb1_backend: 

[device descriptor.txt](https://github.com/libusb/libusb/files/1245789/device.descriptor.txt)
[linux_usb_dmesg.txt](https://github.com/libusb/libusb/files/1245790/linux_usb_dmesg.txt)
[py_debug_libusb1_backend.txt](https://github.com/libusb/libusb/files/1245788/py_debug_libusb1_backend.txt)

Thanks!

**Comment by dickens** [comment]
This isn't a libusb issue. The following messages from the kernel tell what is going on:

[   41.791152] usb 1-8: Not enough bandwidth for new device state.
[   41.791155] usb 1-8: Not enough bandwidth for altsetting 1

The XHCI driver is complaining that it cannot reserve the bandwidth needed the desired alternate setting. You should check if you have other devices on the same host controller that are using up the available bandwidth. If you think everything is okay and this is a kernel bug, you can send an e-mail to the kernel's linux-usb mailing list.
