### ISSUE TITLE
reset card reader with libusb ACR122U?

### ISSUE THREAD

**Issue by userDevop123** [libusb/libusb#338]
I'm working on a [libnfc ](https://github.com/nfc-tools/libnfc)that use on libusb.
 and sometimes my reader is get messed up and i can't reconnect to it. If i re-plug the USB cable everything is fine.

I saw [libusb_reset_device](http://libusb.sourceforge.net/api-1.0/group__dev.html#ga7321bd8dc28e9a20b411bf18e6d0e9aa) but for this i need to get `libusb_device_handle *` .
can you see my any example how to get it and reset the reader?
or maybe you know another way on libnfc to do that without call to libusb_reset_device

**Comment by LudovicRousseau** [comment]
You can have a look at the libusb samples. For example https://github.com/libusb/libusb/blob/master/examples/testlibusb.c

For libnfc questions you should contact libnfc user support.
