### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by dunk8888** [libusb/libusb#344]
Hi can you tell me how i can compile my code,its saying this below,is somthing missing,pkg config? how do i get this? Ime trying to compile a usb project i think its pretty old,ime using windows 7 thanks

gcc -g -Wall -O2 `pkg-config --libs --cflags libusb-1.0`  -c tool.c -o tool.o
/usr/bin/sh: pkg-config: command not found
/usr/bin/sh: gcc: command not found
make: *** [tool.o] Error 127

**Comment by elfmedy** [comment]
emm, i think it should be -lusb-1.0 or libusb-1.0.a

**Comment by LudovicRousseau** [comment]
I am not sure that using GCC under Windows is a good idea unless you know what you do.
Your problem is not related to libusb but to your build environment.

**Comment by dunk8888** [comment]
So I need to installbone of those versions.

**Comment by dunk8888** [comment]
Oh I see,I didn't,read the second message,is it for use with Linux or some
thing like that.
