### ISSUE TITLE
USB 3 Port

### ISSUE THREAD

**Issue by Jeenusck** [libusb/libusb#346]
Hi,

We are using legacy libusb 0.1.12 in our tool.  Our tool is USB 2.0 compatible. In Centos OS we found a strange issue. In USB 3.0 port, Our device is not detected but working fine in USB 2.0 port. If we disable, USB 3.0 in BIOS then our device is working fine. In same PC with Windows OS our device is detecting properly in both USB 2.0 port and USB 3.0 port.  we are testing using Dell Latitude 7440 laptop.

Thanks in advance
Jeenus

**Comment by mcuee** [comment]
What do you mean by legacy 0.1.12? libusb-compat-0.1 is supported but libusb-0.1.12 is not supported.

Anyway, your issue has nothing to do with libusb, you may want to chck with CentOS side.
