### ISSUE TITLE
LibUsbDotNet Bulk Transfer Usb Communication Win32Error

### ISSUE THREAD

**Issue by serhanyilmaz** [libusb/libusb#347]
We have a vendor-specific device for USB connections.

We used LibUsbDotNet Bulk Transfer communication. In the first case, I did 64 byte data transfer. In the second case I made 1024 byte data transfer. In case of 64 byte transfer, there is usually no problem (Problems are rare). In case of 1024 byte transfer, there is a problem (almost always in USB 2.0 port, also rare in USB 3.0 port) and Finally, when doing USB Write, I get Win32Error error in LibUsbDotNet ErrorCode class. 

What causes to this problem?

**Comment by mcuee** [comment]
Take note libusbdotnet is a separate project.
https://github.com/LibUsbDotNet/LibUsbDotNet

**Comment by serhanyilmaz** [comment]
Thank you so much  for answer to my ask 

Have a nice day.

**Comment by mcuee** [comment]
Closed for now. Will reopen if it is linked to libusb.
