### ISSUE TITLE
Documentation lacks information on the semantics of timeouts in the synchronous API

### ISSUE THREAD

**Issue by jleben** [libusb/libusb#348]
The documentation for `libusb_bulk_transfer` mentions that when the timeout expires, some data may have already been transferred. It remains unclear what the user should do in that case: should the user repeat the call to transmit the remaining `length - transferred` bytes?

The documentation also contains this confusing statement:
> libusb is careful not to lose any data that may have been transferred
If some data *has already been transferred*, isn't it obsolete and can safely be lost? If anything, I would expect perhaps that libusb would keep the data that has *not* been transferred yet, and would transfer it on behalf of the user asynchronously...

Link to the documentation:
http://libusb.sourceforge.net/api-1.0/group__syncio.html#gab8ae853ab492c22d707241dc26c8a805

**Comment by LudovicRousseau** [comment]
Please provide a Pull Request to fix the documentation.
