### ISSUE TITLE
Documentation is not clear on when callbacks used in the asynchronous API may be called

### ISSUE THREAD

**Issue by jleben** [libusb/libusb#349]
The documentation for the asynchronous API is not clear when and on what threads the user callbacks may be called.

The documentation says that the user *must* call the `handle_events_*` functions when there is work to do, and that this "gives libusb opportunity to ... invoke callbacks". This is unclear from multiple aspects:

1. It is unclear what it means that "libusb has work to do", and consequently, *when* the user must call `handle_events`.
2. It is unclear whether the callbacks are called synchronously within the call to `handle_events`, on the same thread that calls it, or whether they are called from a different thread.
3. It is unclear whether the callbacks are only called as a result of the user calling `handle_events`, or if they may ever be called as a result of other libusb function calls, or asynchronously from other libusb threads.

**Comment by LudovicRousseau** [comment]
Please provide a Pull Request to fix the documentation.
