### ISSUE TITLE
Unable to work with device connected to ASMedia 3.1 port

### ISSUE THREAD

**Issue by ArnonCh** [libusb/libusb#353]
Hi,

I am facing a similar issue to:
https://github.com/libusb/libusb/issues/227

I'm using windows 8.1 pro, and when I try to detect my device, the function libusb_get_device_list() does not list it.

Inside the function init_device (windows_winusb.c)
When it calls the funcion DeviceIoControl with IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX it fails with the error of no device connected

Update:
I am getting different behavior with different drivers for the ASMedia.
When I'm working with ASMedia driver - 1.16.36.1 I see the above issue.
When I'm working with Microsoft driver - 10.0.15063.296 I have a different problem:
The device is listed by libusb_get_device_list(), but every call to libusb_bulk_transfer(), returns with success always, even when I disable any transition from my composite device (The data is zeroed).

I tried to use windows 10 pro, and I see the same thing.

**Comment by mcuee** [comment]
So the first problem seems to be an ASMedia driver problem. Can you see the device with Microsoft tools like USBView?

For the 2nd problem, you may want to provide more details.

**Comment by ArnonCh** [comment]
Yes the device is visible with USBView (also shows up in the device manager)

**Comment by diabolo38** [comment]
1st issue is certainly on as media (same happen on other drivers) and we can't do anything about it. Unless you need to support win 7 I suggest to use ms native driver and see if we cand dimd a solution for bulk.

**Comment by ArnonCh** [comment]
Win7 is not a must for me.
My update above refers to the phenomena when I use ms native driver - every call to libusb_bulk_transfer() on the input ep returns with success, even tho my device is not transmitting anything

**Comment by mcuee** [comment]
You will need to provide more details, eg: your code snippets and debug log

**Comment by photron** [comment]
I had problems with an ASMedia hub on Windows before and in my case the enumeration changes in libusb 1.0.22-rc3 have fixed the problem now.

**Comment by mcuee** [comment]
Thanks for the update. Close this issue for now. To the OP, you may reopen the issue if you still encounter issues.
