### ISSUE TITLE
Bug: libusb_unref_count on zero ref device crashes

### ISSUE THREAD

**Issue by corby** [libusb/libusb#357]
if a device has the refcount set to 0 either by libusb_close or libusb_unref_count, if you call libusb_unref_count again, the library segfaults.
It should return and error code (possibly an int) to indicate that the operation failed.

Justification:
I use golang to integrate with libusb and it works great, but golang is not awesome at handling signals like SIGABRT or SIGSEG.  Returning error codes instead of having to implement signal handlers would be much nicer.

**Comment by LudovicRousseau** [comment]
Please provide a Pull Request.

**Comment by dickens** [comment]
This is not a bug and what you are requesting cannot be done. As soon as the refcount reaches 0, the memory is freed. At that point there is no way to detect an error in a subsequent call.
