### ISSUE TITLE
有人能给个Andriod cmake引用libusb的例子吗, 不胜感激

### ISSUE THREAD

**Issue by lastidea** [libusb/libusb#372]
最近一指想用Andriod cmake引用libusb, 但是去java和c++, cmake都不熟, 深深的歉意, 所以看看有人有做过这方面的事吗, 指教一下, 给个例子, 不胜感激!!!! QQ: 17620286@qq.com

**Comment by dickens** [comment]
Not sure what this is meant to be. OP can reopen this issue if needed.

**Comment by mcuee** [comment]
To OP: please use the mailing list for technical support. Please also use English as this is the common language for the libusb project.
