### ISSUE TITLE
How to use libusb for composite device (Microsoft LifeCam)

### ISSUE THREAD

**Issue by shbgr** [libusb/libusb#379]
How can I Use libusb for a composite device (Microsoft Lifecam Studio HD for me, USB\VID_045E&PID_0772)?

Whenever I replace the driver for the Composite Parent (with Zadig) the Camera and Microphone devices are lost.

**Comment by diabolo38** [comment]
Assigne driver with Zadig only to the interface to manage. If you mess up install once it may be tricky to do a clean driver uninstall and install again. Note that  If the interface you need  is part of the iad for voice or video then it may not be possible to not losses this function

**Comment by mcuee** [comment]
Close this issue. If the OP needs further support, please use mailing list for technical support. Thanks.
