### ISSUE TITLE
Stuck command key after running freenect examples on OSX 10.9 macbook pro

### ISSUE THREAD

**Issue by grrrwaaa** [libusb/libusb#38]
Posting here as this seems likely to be libusb-related (but also posted here: https://github.com/OpenKinect/libfreenect/issues/414)

Libfreenect examples work correctly, but after quitting I often get a series of fake keypresses that sometimes close down any open windows (any other application currently running), and always leave the computer thinking that the command key is down. 

Macbook pro mid-2014, OSX 10.9.4, Intel Core i7; Kinect Xbox 360 model 1473.
It's a new machine, hardly anything installed.

Sometimes I get "Unable to claim interface -7", but the streams do work anyway.
Same results whether compiling/installing libusb/libfreenect from git master or using brew.

**Comment by mcuee** [comment]
Closing the issue since we have not heard back anything from the OP.
