### ISSUE TITLE
libusb_init not using

### ISSUE THREAD

**Issue by binhln95** [libusb/libusb#388]
I setting libusb in Mac OS and Ubuntu, but when I use function libusb_init, I have error: linker command failed with exit code 1. Please help me.Thank you

> Undefined symbols for architecture x86_64:
  "_libusb_init", referenced from:
      _main in test-1fa259.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hjelmn** [comment]
The GitHub issues list is not for user support. Use the libusb-devel mailing list @ sourceforge.
