### ISSUE TITLE
libusb_get_device_descriptor fails to return correct  iSerialNumber on MacOSX and Ubuntu 16.04

### ISSUE THREAD

**Issue by righthalfplane** [libusb/libusb#407]
The latest version of HackRF calls libusb_get_device_descriptor to get the device serial number. iSerialNumber always comes back as zero on MacOSX and Ubuntu 16.04. HackRF also calls libusb_control_transfer to get the serial number  -

	result = libusb_control_transfer(
		device->usb_device,
		LIBUSB_ENDPOINT_IN | LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_RECIPIENT_DEVICE,
		HACKRF_VENDOR_REQUEST_BOARD_PARTID_SERIALNO_READ,
		0,
		0,
		(unsigned char*)read_partid_serialno,
		length,
		0
	);

read_partid_serialno contains the serial number in an encoded form and it is correct.

**Comment by dickens** [comment]
This isn't a libusb issue. If the device isn't reporting the correct string index in the device descriptor, the device is broken.
