### ISSUE TITLE
When Python bindings for release 1.0.22 will be available on PyPI?

### ISSUE THREAD

**Issue by vasily-v-ryabov** [libusb/libusb#411]
Please post latest release to PyPI. We'd like to use final release through `pip` instead of beta. Thanks!

**Comment by mcuee** [comment]
Wrong one. libusb has nothing to do with PyPi. Maybe you are talking about
pyusb or python-libusb1. Will close this.

> --
Xiaofan

**Comment by vasily-v-ryabov** [comment]
Sorry, it seems there is different maintainer for Python bindings:
https://pypi.python.org/pypi/libusb

**Comment by mcuee** [comment]
Interestingly there is new python binding for libusb. Just wondering what is the advantage compare to the more popular pyusb. There is also python-libusb1.

pyusb
https://pypi.python.org/pypi/pyusb

python-libusb1
https://pypi.python.org/pypi/libusb1

**Comment by vasily-v-ryabov** [comment]
Well, we decided to use C version as a Git submodule for now. There were no deep comparison of these bindings. Thanks for the links!
