### ISSUE TITLE
Windows binary release installation package 

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb#426]
Not so sure if this is really necessary or not but it may be good to release a Windows binary installation package -- offer to install libusb-1.0.dll to the Windows system directory (32/64bit) and install libusb examples binary to Windows Program directory or user selected directory. The program can also provide simple help file to point user to install Zardig/usbdk/libusbK.

**Comment by cellularmitosis** [comment]
👍

**Comment by mcuee** [comment]
This will be a low priority work and may not be implemented at all.

**Comment by mcuee** [comment]
Close this for now as it does not seem to be needed.
