### ISSUE TITLE
libusb-1.0 fails to compile with mingw32

### ISSUE THREAD

**Issue by Swiftkill** [libusb/libusb#429]
Can't compile with mingw32: undefined reference to__ms_vsnprintf.
Tool chain limited to 32bit and mingw32 and program that uses library can't be modified.

**Comment by diabolo38** [comment]
Be sure to use Mingw w64 or msys2 . i guess older mingw (ie msys)miss few ms api

**Comment by mcuee** [comment]
To: OP, you should use MinGW-w64 distributions like MSYS2. 
MinGW.org is no longer supported unless someone wants to provide the patches.

**Comment by mcuee** [comment]
Close this for now.
