### ISSUE TITLE
Explanation of libusb vs libusb-win32; libusb.org, libusb.info, etc

### ISSUE THREAD

**Issue by gwideman** [libusb/libusb#43]
The landscape for someone just trying to figure out what to install to get a USB peripheral working (in my case, AVRISP MkII with WinAVR's included libusb version who-knows-what) is dauntingly confusing.  

Is there somewhere (or could someone create it if there isn't) a concise explanation of the conspicuous players in this space, all the components, and how they do or don't relate to each other?  For starters:

How does libusb relate to libusb-win32?  I thought they were alternatives to one another or possibly that the -win32 one superceeds the not-win32 one, in light of not-win32 being uninstallable due to lack of signature. But now I see on page https://github.com/libusb/libusb/wiki/Windows that libusb claims to support recent Windows. Except then I read that libusb requires libusb-win32. What? Totally confused.

And then there's the proliferation of websites that might or might not be related:
libusb.org.  libusb,info ("The old site is now obsolete, please use libusb.info." -- what "old site" is that?), github.com/libusb, sourceforge.net/projects/libusb-win32.

Help!

-- Graham

**Comment by mcuee** [comment]
Further discussions were carried out in the mailing list. Closing this ticket.

**Comment by gwideman** [comment]
@mcuee I searched mailing list libusb-devel, and didn't see any discussion. Could you point me to the discussions you mention? Thanks.

**Comment by mcuee** [comment]
Is the following not enough for you? What do you exactly want? If possible, please use the mailing list for further discussion.
https://github.com/libusb/libusb.github.com/issues/1

**Comment by gwideman** [comment]
@mcuee  I am confused. You wrote there was a discussion on the mailing list. I wanted to keep up with the discussion, so I went to look for it but didn't see it, and am not entirely sure I looked at the right archive (https://sourceforge.net/p/libusb/mailman/libusb-devel/). So I asked where this discussion is. Is this the list you referred to? And if so, I'm not seeing the discussion, so I asked about that. Have I somehow made a misstep?

**Comment by mcuee** [comment]
Sorry it is not in the mailing list but rather it is in the discussion of
the ticket. Is it good enough for you or not?
libusb/libusb.github.com#1
<https://github.com/libusb/libusb.github.com/issues/1>

And I think it is more productive to use mailing list and not github ticket
to have further discussions.

-- 
Xiaofan

**Comment by gwideman** [comment]
Sure, that's fine.
