### ISSUE TITLE
libusb_init() return -99 in Android5.1.1, but return 0 in Android4.4.2

### ISSUE THREAD

**Issue by Shuyun6** [libusb/libusb#444]
Code like : `int res = libusb_init(NULL);`
am I using a wrong method? or libusb cannot support Android 5.+?

**Comment by mcuee** [comment]
Duplicate: will close this one.
https://github.com/libusb/libusb/issues/233
https://github.com/libusb/libusb/issues/188

You can try pull request.
https://github.com/libusb/libusb/pull/242

**Comment by Shuyun6** [comment]
@mcuee it means I should invoke `libusb_wrap_fd()` before `libusb_init()`, right?

**Comment by Shuyun6** [comment]
@mcuee [#242](https://github.com/libusb/libusb/pull/242) means that use `libusb_wrap_fd()` instead `libusb_open()`, but no anything about `libusb_init()`. I use [libuvc](https://github.com/ktossell/libuvc) that build atop libusb, it initilized through `libusb_init()`. So, how can I use `libusb_init()`?

**Comment by mcuee** [comment]
It means currently unmodified libusb will not work for you — you need to
apply the patches provided by that pull request first.
-- 
Xiaofan
