### ISSUE TITLE
Create a Way to Cancel libusb_handle_events

### ISSUE THREAD

**Issue by gudenau** [libusb/libusb#454]
I noticed that there does not seem to be a way to interrupt a call to `libusb_handle_events` if it is doing nothing, I am working on a program that will use a threaded event handler and it can not be made to keep a device handle open at all times. I would rather not have to create and destroy contexts as the devices are opened and closed.

**Comment by mcuee** [comment]
Close this for now. 
Please ask in libusb mailing list.
