### ISSUE TITLE
Windows: Add isochronous support for libusbK and WinUSB

### ISSUE THREAD

**Issue by piedar** [libusb/libusb#46]
@JoshBlake proposed [this patch](https://github.com/libusbx/libusbx/pull/164) to libusbx, but it was never merged.  A cherry-pick still applies cleanly to libusb HEAD.

```
git clone https://github.com/libusb/libusb.git
cd libusb
git remote add jblake https://github.com/JoshBlake/libusbx.git
git fetch jblake
git cherry-pick c5b0af4 1c74211
```

I tested the patch and it appears to work with libusbK v3.0.7.0.  Any chance this can be merged into libusb?  It would make libfreenect a lot easier to build on Windows by replacing our emulation layer that is woefully out of date.

**Comment by QianJin2013** [comment]
from Windows 8.1, WinUSB also support isochronous mode. Hope this be implemented in future.

**Comment by mcuee** [comment]
It will be good to add WinUSB isoc support (directly to libusb WIndows backend or through libusbK). Travis mentioned he intended to add WinUSB isoc support to libusbK recently but I am not so sure when he will start that work.

**Comment by mcuee** [comment]
Another option is to look at usbdk backend which has not yet been integrated.

https://github.com/dmitryfleytman/libusb/tree/usbdk-backend-v3

**Comment by mkassner** [comment]
https://github.com/ktossell/libuvc would finally work on windows if isochronous transfers where to be implemented with winusb8.1: https://github.com/ktossell/libuvc/issues/12

Any chance for this to happen in the near future?

**Comment by xlz** [comment]
@mcuee 
What is the plan now?
Is the usbdk backend favored over the libusbk patch? WinUSB? What about Windows 7 users?

**Comment by mcuee** [comment]
Not sure when this support will be added to Windows backend which is now
lagging behind Linux and Mac OS X (isoc support and hotplug support). It
depends on the time and priority of the main Windows developer now.

BTW, usbdk works under Windows 7.

**Comment by diabolo38** [comment]
with new Microsoft policy on driver signing i'm scared no new libusbk release will ever happen.
So usbdk and winusb  seam the only possible candidate to enhance support on windows.

I will not be able to participate actively on development but i can participate and provide some punctual help with testing on win 7  (uvc cam,  gadget 0 target) and bus level debug if needed.

**Comment by xlz** [comment]
I just tested usbdk. It failed to enumerate Kinect v2 sensor (no other tests could follow). It also has some incomplete support for important features https://github.com/daynix/UsbDk/issues/10, which is specially required by libfreenect2.

The isochronous patch for libusbK backend just works, and has been extensively tested. What is the reason not to merge it?

**Comment by mcuee** [comment]
Ref: https://github.com/libusb/libusb/pull/109

**Comment by philemonf** [comment]
Ref: #284

**Comment by mcuee** [comment]
Take note #246 is now closed since it has been merged.

**Comment by piedar** [comment]
[Excellent!](https://github.com/libusb/libusb/commit/55ced7746dd697024f2042aca009b7436892bf2b)  :+1:
