### ISSUE TITLE
set_composite_interface function fails to get the interface number under Windows 

### ISSUE THREAD

**Issue by joska86** [libusb/libusb#461]
I am trying to connect to my Huawei mobile phone via USB and communicate with it as ADB (Android Debug Bridge) does. But it seems, something went wrong, because in the file **windows_winusb.c** the function set_composite_interface failed to get the valid interface number value (I debugged it, so the problem is there for sure), because the _device_id_ parameter does not contain any subsrting prefixed with "MI_" which should contain the interface number.

The piece of the debug log:

`[ 0.199000] [00000e00] libusb: debug [get_api_type] driver(s): WinUSB
[ 0.208000] [00000e00] libusb: debug [get_api_type] matched driver name against WinUSB
[ 0.215000] [00000e00] libusb: debug [winusb_get_device_list] setting composite interface for [1BBC]:
[ 0.225000] [00000e00] libusb: warning [set_composite_interface] failure to read interface number for USB\VID_12D1&SUBCLASS_42&PROT_01\8&277680DE&0&0004, using default value
[ 0.231000] [00000e00] libusb: debug [set_composite_interface] interface[0] = \\.\USB#VID_12D1&SUBCLASS_42&PROT_01#8&277680DE&0&0004#{F72FE0D4-CBCB-407D-8814-9ED673D0DD6B}`

![report_2](https://user-images.githubusercontent.com/42214796/43849581-131aea90-9b36-11e8-8add-f8cf018c49d5.png)

![report_1](https://user-images.githubusercontent.com/42214796/43849606-2167633a-9b36-11e8-82b2-832ca2e2b0dd.png)

As you can see, the Device Instance Path which is used in libusb code too:
`			if (!pSetupDiGetDeviceInstanceIdA(*dev_info, &dev_info_data, dev_id, sizeof(dev_id), NULL)) {
				usbi_warn(ctx, "could not read the device instance ID for devInst %X, skipping",
					  dev_info_data.DevInst);
				continue;
			}`
did not returned any MI_ prefixed string.

**Comment by mcuee** [comment]
Please provide more details.
1) post the usb descriptor of your device
2) provide the details how you install the driver for your device.
3) provide the code and debug log

**Comment by joska86** [comment]
1.
0x12	bLength
0x01	bDescriptorType
0x0200	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x40	bMaxPacketSize0   (64 bytes)
0x12D1	idVendor
0x107D	idProduct
0x0318	bcdDevice
0x01	iManufacturer   "HUAWEI"
0x02	iProduct   "HUAWEI MLA-L11"
0x03	iSerialNumber   "GLDDU16A30003604"
0x01	bNumConfigurations


The interface (0x03) which I want to use to communicate to the phone is:
0x09	bLength
0x04	bDescriptorType
0x03	bInterfaceNumber
0x00	bAlternateSetting
0x02	bNumEndPoints
0xFF	bInterfaceClass      (Vendor specific)
0x42	bInterfaceSubClass   
0x01	bInterfaceProtocol   
0x09	iInterface   "ADB Interface"

2

Just plug in and Windows installed the driver, but I've tried to install manually the driver (HiSuite Huawei package)

3
The code snippet:

```
libusb_device_handle* handle_raw = nullptr;
	rc = libusb_open(device, &handle_raw);
	unique_device_handle handle(handle_raw);
	std::string deviceSerial;
	if (rc == 0) {
		
		std::cout << "successfully opened adb device at " << deviceAddress << std::endl;

		deviceSerial.resize(255);
		rc = libusb_get_string_descriptor_ascii(handle_raw, device_desc.iSerialNumber,
			reinterpret_cast<unsigned char*>(&deviceSerial[0]),
			deviceSerial.length());
		if (rc == 0) {
			std::cout << "received empty serial from device at " << deviceAddress<<std::endl;
			return;
		}
		else if (rc < 0) {
			std::cout << "failed to get serial from device at " << deviceAddress
				<< libusb_error_name(rc) <<std::endl;
			return;
		}
		deviceSerial.resize(rc);
		rc = libusb_claim_interface(handle.get(), interface_num);
		if (rc != 0) {
			std::cout << "failed to claim adb interface for device '" << deviceSerial << "'"
				<< libusb_error_name(rc) << std::endl;
			return;
		}

		rc = libusb_set_interface_alt_setting(handle.get(), interface_num, 0);
		if (rc != 0) {
			std::cout << "failed to set interface alt setting for device '" << deviceSerial
				<< "'" << libusb_error_name(rc) << std::endl;
			return;
		}
```

**rc = libusb_claim_interface(handle.get(), interface_num);** where the lib fails (inferface_num is 0x03 as mentioned above)

The debug log:
`[ 0.014000] [00000914] libusb: debug [libusb_get_device_list]
[ 0.075000] [00000914] libusb: debug [winusb_get_device_list] found new PnP enumerator string 'IUSB3'
[ 0.075000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [1F2C]
[ 0.075000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [1F6C]
[ 0.075000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [1FBC]
[ 0.075000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [200C]
[ 0.075000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [2058]
[ 0.076000] [00000914] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.076000] [00000914] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.076000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [1AF0]
[ 0.076000] [00000914] libusb: debug [get_api_type] driver(s): USBAAPL64
[ 0.076000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [1B40]
[ 0.076000] [00000914] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.076000] [00000914] libusb: debug [get_api_type] upper filter driver(s): ew_usbccgpfilter
[ 0.076000] [00000914] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.076000] [00000914] libusb: debug [winusb_get_device_list] allocating new device for session [1BC4]
[ 0.077000] [00000914] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_A2AF&SUBSYS_50071458&REV_00\3&11583659&0&A0' bus number 1
[ 0.079000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [1AF0]
[ 0.079000] [00000914] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.079000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 84 bytes)
[ 0.079000] [00000914] libusb: debug [init_device] (bus: 1, addr: 3, depth: 1, port: 10): 'USB\VID_045E&PID_07B2\5&74DC32E&0&10'
[ 0.079000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [1B40]
[ 0.080000] [00000914] libusb: debug [init_device] found 4 configurations (active conf: 4)
[ 0.080000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 39 bytes)
[ 0.080000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 1 (bConfigurationValue=1, 39 bytes)
[ 0.080000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 2 (bConfigurationValue=1, 39 bytes)
[ 0.080000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 3 (bConfigurationValue=1, 39 bytes)
[ 0.080000] [00000914] libusb: debug [init_device] (bus: 1, addr: 2, depth: 1, port: 9): 'USB\VID_05AC&PID_12A8\89EC1870AD005073FA47A05A7BFAA9413BEA02FD'
[ 0.080000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [1BC4]
[ 0.080000] [00000914] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.080000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 176 bytes)
[ 0.080000] [00000914] libusb: debug [init_device] (bus: 1, addr: 18, depth: 3, port: 2): 'USB\VID_12D1&PID_107D\GLDDU16A30003604'
[ 0.081000] [00000914] libusb: debug [winusb_get_device_list] extra GUID: {F72FE0D4-CBCB-407D-8814-9ED673D0DD6B}
[ 0.081000] [00000914] libusb: debug [winusb_get_device_list] extra GUID: {9DB27A70-239F-4598-A0E6-C94D8FC7F1B3}
[ 0.081000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [1F6C]
[ 0.081000] [00000914] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.081000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 31 bytes)
[ 0.081000] [00000914] libusb: debug [init_device] (bus: 1, addr: 4, depth: 1, port: 22): 'USB\VID_2109&PID_0813\5&74DC32E&0&22'
[ 0.082000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [1FBC]
[ 0.170000] [00000914] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.171000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 31 bytes)
[ 0.171000] [00000914] libusb: debug [init_device] (bus: 1, addr: 7, depth: 2, port: 4): 'USB\VID_2109&PID_0813\6&385E9B4F&0&4'
[ 0.172000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [200C]
[ 0.173000] [00000914] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.174000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 25 bytes)
[ 0.174000] [00000914] libusb: debug [init_device] (bus: 1, addr: 1, depth: 1, port: 6): 'USB\VID_2109&PID_2813\5&74DC32E&0&6'
[ 0.175000] [00000914] libusb: debug [winusb_get_device_list] found existing device for session [2058]
[ 0.176000] [00000914] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.176000] [00000914] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 25 bytes)
[ 0.176000] [00000914] libusb: debug [init_device] (bus: 1, addr: 6, depth: 2, port: 4): 'USB\VID_2109&PID_2813\6&4C3E0C1&0&4'
[ 0.180000] [00000914] libusb: debug [init_device] (bus: 1, addr: 0, depth: 0, port: 0): 'IUSB3\ROOT_HUB30\4&92B3C53&0'
[ 0.181000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.181000] [00000914] libusb: debug [set_composite_interface] interface[1] = \\.\HID#VID_045E&PID_07B2&MI_01&COL01#7&6967C7&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.182000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.182000] [00000914] libusb: debug [set_composite_interface] interface[0] = \\.\HID#VID_045E&PID_07B2&MI_00#7&182CF40C&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.183000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.183000] [00000914] libusb: debug [set_composite_interface] interface[1] already set - ignoring HID collection: HID\VID_045E&PID_07B2&MI_01&COL02\7&6967C7&0&0001
[ 0.184000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.184000] [00000914] libusb: debug [set_composite_interface] interface[2] = \\.\HID#VID_045E&PID_07B2&MI_02&COL01#7&28EEFC62&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.185000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.186000] [00000914] libusb: debug [set_composite_interface] interface[2] already set - ignoring HID collection: HID\VID_045E&PID_07B2&MI_02&COL02\7&28EEFC62&0&0001
[ 0.188000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.190000] [00000914] libusb: debug [set_composite_interface] interface[2] already set - ignoring HID collection: HID\VID_045E&PID_07B2&MI_02&COL03\7&28EEFC62&0&0002
[ 0.192000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1AF0]:
[ 0.194000] [00000914] libusb: debug [set_composite_interface] interface[2] already set - ignoring HID collection: HID\VID_045E&PID_07B2&MI_02&COL04\7&28EEFC62&0&0003
[ 0.198000] [00000914] libusb: debug [get_api_type] driver(s): WinUSB
[ 0.199000] [00000914] libusb: debug [get_api_type] matched driver name against WinUSB
[ 0.200000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1BC4]:
[ 0.202000] [00000914] libusb: warning [set_composite_interface] failure to read interface number for USB\VID_12D1&SUBCLASS_42&PROT_01\8&309DA40&0&0003, using default value
[ 0.204000] [00000914] libusb: debug [set_composite_interface] interface[0] = \\.\USB#VID_12D1&SUBCLASS_42&PROT_01#8&309DA40&0&0003#{F72FE0D4-CBCB-407D-8814-9ED673D0DD6B}
[ 0.208000] [00000914] libusb: debug [get_api_type] driver(s): WinUSB
[ 0.208000] [00000914] libusb: debug [get_api_type] matched driver name against WinUSB
[ 0.210000] [00000914] libusb: debug [winusb_get_device_list] setting composite interface for [1BC4]:
[ 0.212000] [00000914] libusb: warning [set_composite_interface] failure to read interface number for USB\VID_12D1&SUBCLASS_48&PROT_01\8&309DA40&0&0004, using default value
[ 0.214000] [00000914] libusb: debug [set_composite_interface] interface[0] = \\.\USB#VID_12D1&SUBCLASS_48&PROT_01#8&309DA40&0&0004#{9DB27A70-239F-4598-A0E6-C94D8FC7F1B3}
[ 0.218000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.219000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.220000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.222000] [00000914] libusb: debug [libusb_open] open 1.18
[ 0.224000] [00000914] libusb: debug [libusb_alloc_transfer] transfer 0087B478
[ 0.225000] [00000914] libusb: debug [libusb_submit_transfer] transfer 0087B478
[ 0.228000] [00000914] libusb: debug [usbi_add_pollfd] add fd 2 events 1
[ 0.230000] [00000914] libusb: debug [composite_submit_control_transfer] using interface 0
[ 0.232000] [00000914] libusb: debug [libusb_claim_interface] interface 0
[ 0.233000] [00000914] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 0.235000] [00000914] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 82 to interface 0
[ 0.236000] [00000914] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 81 to interface 0
[ 0.238000] [00000914] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 01 to interface 0
[ 0.240000] [00000914] libusb: debug [auto_claim] auto-claimed interface 0 for control request
[ 0.241000] [00000914] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 0.243000] [00000914] libusb: debug [libusb_get_next_timeout] next timeout in 0.984282s
[ 0.244000] [00000914] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.247000] [00000914] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.249000] [00000914] libusb: debug [handle_events] poll() 2 fds with timeout in 985ms
[ 0.250000] [00000914] libusb: debug [handle_events] poll() returned 1
[ 0.252000] [00000914] libusb: debug [windows_handle_events] checking fd 2 with revents = 0001
[ 0.253000] [00000914] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 0.255000] [00000914] libusb: debug [windows_transfer_callback] handling I/O completion with errcode 0, size 4
[ 0.257000] [00000914] libusb: debug [libusb_release_interface] interface 0
[ 0.258000] [00000914] libusb: debug [auto_release] auto-released interface 0
[ 0.260000] [00000914] libusb: debug [usbi_handle_transfer_completion] transfer 0087B478 has callback 00B12D10
[ 0.262000] [00000914] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.264000] [00000914] libusb: debug [libusb_free_transfer] transfer 0087B478
[ 0.266000] [00000914] libusb: debug [libusb_alloc_transfer] transfer 0087B478
[ 0.267000] [00000914] libusb: debug [libusb_submit_transfer] transfer 0087B478
[ 0.269000] [00000914] libusb: debug [usbi_add_pollfd] add fd 2 events 1
[ 0.271000] [00000914] libusb: debug [composite_submit_control_transfer] using interface 0
[ 0.272000] [00000914] libusb: debug [libusb_claim_interface] interface 0
[ 0.274000] [00000914] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 0.276000] [00000914] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 82 to interface 0
[ 0.277000] [00000914] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 81 to interface 0
[ 0.279000] [00000914] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 01 to interface 0
[ 0.281000] [00000914] libusb: debug [auto_claim] auto-claimed interface 0 for control request
[ 0.283000] [00000914] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 0.285000] [00000914] libusb: debug [libusb_get_next_timeout] next timeout in 0.983962s
[ 0.286000] [00000914] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.288000] [00000914] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.289000] [00000914] libusb: debug [handle_events] poll() 2 fds with timeout in 984ms
[ 0.291000] [00000914] libusb: debug [handle_events] poll() returned 1
[ 0.293000] [00000914] libusb: debug [windows_handle_events] checking fd 2 with revents = 0001
[ 0.294000] [00000914] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 0.296000] [00000914] libusb: debug [windows_transfer_callback] handling I/O completion with errcode 0, size 34
[ 0.298000] [00000914] libusb: debug [libusb_release_interface] interface 0
[ 0.300000] [00000914] libusb: debug [auto_release] auto-released interface 0
[ 0.301000] [00000914] libusb: debug [usbi_handle_transfer_completion] transfer 0087B478 has callback 00B12D10
[ 0.303000] [00000914] libusb: debug [sync_transfer_cb] actual_length=34
[ 0.305000] [00000914] libusb: debug [libusb_free_transfer] transfer 0087B478
[ 0.306000] [00000914] libusb: debug [libusb_claim_interface] interface 3
[ 0.308000] [00000914] libusb: debug [composite_claim_interface] unsupported API call for 'claim_interface' (unrecognized device driver)
[ 0.310000] [00000914] libusb: debug [libusb_close]
[ 0.312000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.314000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.315000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.317000] [00000914] libusb: debug [libusb_get_device_descriptor]
[ 0.319000] [00000914] libusb: debug [libusb_get_device_descriptor]`

Problematic line:
**[ 0.202000] [00000914] libusb: warning [set_composite_interface] failure to read interface number for USB\VID_12D1&SUBCLASS_42&PROT_01\8&309DA40&0&0003, using default value**

There is no MI_prefixed string to determine the interface number (however I assume that the last element in the string (0003) is the real interface number)

**Comment by dickens** [comment]
This device must be using usbccgp as its driver, which is strange if it is not a composite device.  What is this device's parent?  Can you show what the Device Manager looks like when viewing by connection?

**Comment by dickens** [comment]
Closing since there has been no response to the request for information in over 6 months.  Please reopen if there is additional information to provide.
