### ISSUE TITLE
Access denied when uploading file to camera

### ISSUE THREAD

**Issue by brivbl** [libusb/libusb#465]
Hello,

I am using a canon EOS M10 camera but whenever I try to configure it or to upload a file to the camera using gphoto2, I get a permission error : "PTP access denied".

I tried adding write permissions with the following command : sudo chmod 777 /dev/bus/usb/001/006
and it still does not work

Is there a way to have a write permission on this type of usb device with libusb ?

Here is the error I found in the log after running a set config command in gphoto2 :

21.313167 gp_libusb1_read libusb1.c:603: 'libusb_bulk_transfer (port->pl->dh, port->settings.usb.inep, (unsigned char*)bytes, size, &curread, port->timeout)' failed: Operation timed out (-7)

**Comment by mcuee** [comment]
Please use libusb mailing list for technical support. This github is for reporting of libusb issues.
