### ISSUE TITLE
If you have a problem with uninstalling libusb drivers(windows 10)!

### ISSUE THREAD

**Issue by spasimir21** [libusb/libusb#467]
1. Uninstall LibUsb-win32 from Control Panel
2. Restart your computer
3. Download device driver from the internet or the hardware installation disk (If you have one)
4. Uninstall the device`s driver or driver program
5. Reinstall from the downloaded driver installer
6. Unplug and plug the device back in
7. Party!

**Comment by mcuee** [comment]
Your step is not necessary. Anyway, take note libusb-win32 is a seperate project from libusb.
