### ISSUE TITLE
Failure to receive data from printer (libusb error - 7: (0/8 from 0x82))

### ISSUE THREAD

**Issue by bulletxt** [libusb/libusb#47]
Hi, as topic says once in a while when printing with ubuntu 14.04 64bit with a DNP DS40 or DNP DS80 usb printer we the print job hangs and cups reports the error  Failure to receive data from printer (libusb error - 7: (0/8 from 0x82))

We tried changing USB cable, USB port on server... same behaviour (randomly we get that error)
I've checked libusb version of ubuntu 14.04 and it says it's 1.017 .... can someone help me?  It's very important for us we are in production usage...

Thanks a lot in advance I'm willing to give you all needed information

**Comment by dickens** [comment]
Hi,

That is a timeout error, meaning the printer did not send any data within
whatever timeframe CUPS allows. This is likely not a physical USB issue
(e.g. port, cable). The host simply sends a request for data from the
printer. It is up to the printer to respond to the request.

This could be a CUPS or device firmware issue. The first step in trying to
figure out which is probably to determine what data CUPS is asking for when
the timeout occurs.

Regards,
Chris

**Comment by pbatard** [comment]
Since OP received a reply and hasn't provided further updates for more than a month, we will close this issue.

**Comment by bulletxt** [comment]
I'm sorry. I actually confirm this issue means the server all of a sudden is unable to comunicate with the printer.
As of now the only thing I'm able to understand is that this issue happens only if I connect at least 6 USB printers and they are all on.  After a while and in a very random way all of a sudden this issue arises with a random printer. The only way to get rid of this issue is to completley turn off the printer and then turn it back on.  Still, this will not always work so at the moment I must keep 4 printers (haven't tried 5 yet).... I know this doesnt make sense but this is really what is happening.

The server is a professional HP ML 110 G8 v2 server, we also tried changing the server with another one and still this happens.
If there is something more I can provide please let me know.

**Comment by pbatard** [comment]
OK, I'll leave the issue open, if anybody else wants to chime in. 

The fact that you need to have 6 printers on at the same time for the issue to manifest itself would tend to point at a limitation external to libusb, as Chris pointed out, as I don't recall seeing reports from people failing to access multiple devices at once, and I seem to recall that we had a few users of libusb eager to apply it in configurations where quite a few devices of the same type (10 or more) were accessed by the same application.

**Comment by bulletxt** [comment]
Hi people, I just wanted to let you know we finally discovered the issue. It wasn't libusb fault or anything else! Simply, too many USB printers connect (4 and above) created too much elettromagnetic propagation......  we changed USB cables with good shielded ones and the issue totally went away!

**Comment by mcuee** [comment]
Thanks for reporting back.
