### ISSUE TITLE
Bulk: data transferred but callback never called

### ISSUE THREAD

**Issue by jelicicm** [libusb/libusb#472]
Hello,
I'm trying to implement USB 2.0 Bulk transfers between my Ubuntu PC and Zybo board (Arm Cortex A9). 
Code for PC application is [here](https://github.com/jelicicm/libusb_pc/blob/master/git_support.c) and you'll see that I'm trying to send 100 bytes of data. On Zybo, I get callback to "data received", and data received matches what is sent, both in size and what is stored. However, my PC application never enters callback routine.

Any idea on how I can fix this?

**Comment by dickens** [comment]
I think you missed the part in the documentation where your app has to call some variant of libusb_handle_events() (e.g. http://libusb.sourceforge.net/api-1.0/group__libusb__poll.html#ga4989086e3f0327f3886a4c474ec7c327).
