### ISSUE TITLE
async delay waiting for external stuff

### ISSUE THREAD

**Issue by SteveatHerasys** [libusb/libusb#474]
Hi, I am using libusb in async mode. It works fine.

I have a flakey device which needs occasional "pauses" to get its act together before more I/O. I still want async I/O to go on on some endpoints or clearing out the devices IN buffers, so I cannot just sleep in my app. 

 libusb_handle_events_timeout_completed will return when either the timeout happens or any event happens.

If I want to loop and let async events happen AND timeout after say 500 milliseconds, is there a way to do it in pure libusb or do I need to create my own timer?

Thanks, Steve

**Comment by mcuee** [comment]
Close this for now. 
Please ask in libusb mailing list.
