### ISSUE TITLE
Input/output error randomly happened and app stop working. 

### ISSUE THREAD

**Issue by WonMian** [libusb/libusb#479]
We build usb-c app, in most of cases it works fine, but Input/output error randomly happened and then app stop working. Anyone know about this issue? Thanks!

   
I am using libusb_bulk_transfer function. 

   do{
        status = libusb_bulk_transfer(pDevItr->pHandle, //handle to the device
                                      dataEndPointAddr, //Endpoint for data transfer
                                      pDataBuffer,      //Buffer for data
                                      dataLength,       //actual length of data
                                      &sizeTransferred, //actual size of data transferred
                                      USB_TIMEOUT_MS);  //Timeout

        if (status == LIBUSB_ERROR_PIPE)
        {
            libusb_clear_halt(pDevItr->pHandle,
                              dataEndPointAddr);
        }
        tries++;
  } while ((status == LIBUSB_ERROR_PIPE) && (tries < USB_MAX_RETRIES));

    if (status != LIBUSB_SUCCESS)
    {
        printf("%s\n", libusb_strerror(static_cast<libusb_error>(status)));
        printf("Cannot transfer data to USB device with vid:pid:serialNum = %u:%u:%s\n",
               pDevItr->vendorId,
               pDevItr->productId,
               pDevItr->serialNum);
        return -1;
    }

**Comment by mtedeschi** [comment]
Following up on this issue—I've noticed this problem occurring in another repo that uses libusb where "Input / Output Errors" are appearing: https://github.com/scanlime/fadecandy

**Comment by mcuee** [comment]
Close this for now. 
Please ask in libusb mailing list.

**Comment by zangetsudo** [comment]
hi, WonMian
im facing the same issue with:
1. v1.0.23: libusb 1.0.23, 
2. linux: gcc version 5.3.1 20160113 (Linaro GCC 5.3-2016.02) 
3. kernel 4.4.84
have you fixed it ?
