### ISSUE TITLE
Get usb position with libusb-win32

### ISSUE THREAD

**Issue by ltaini** [libusb/libusb#480]
Hello.I am using libusb-win32.But I have two questions now.
One is why libusb0 can call CreateFile success with filename like this "\\.\libusb0-0001"? Can I can detail info about this.
The other is what can i do if i want to get detail position info of one usb device ?Like this format Port_#0002.Hub_#0002.
Thanks.

**Comment by mcuee** [comment]
Please use libusb-win32 mailing list for technical support related to libusb-win32. The github site is for issue reporting for libusb project. libusb-win32 is a seperate project from libusb.
