### ISSUE TITLE
Arguments for fxload.exe

### ISSUE THREAD

**Issue by prateek1108** [libusb/libusb#49]
Hello Sir,

I want to upgrade my ios phone firmware by code while connecting iPhone by usb with my windows computer. Is by this libusb code Fxload.c can i upgrade my iphone firmware for .exe or code what parameter i need to pass.please help me out regarding this issue your help is really precious for me. please guide me to do this job.

**Comment by mcuee** [comment]
No, you can not use fxload to upgrade your iPhone firmware. You should use Apple's software to do that.

**Comment by prateek1108** [comment]
Hello,
Thanks a lot sir for your reply, Sir i want to update firmware of iPhone by code please help if you have any idea about the project or article to do my job. Please guide me

**Comment by mcuee** [comment]
Sorry but this has nothing to do with libusb. You have to seek help
elsewhere.

-- 
Xiaofan
