### ISSUE TITLE
Wrong bus number reported for AppleUSBRootHubDevice (MacOS 10.13.6 High Sierra)

### ISSUE THREAD

**Issue by timdesi** [libusb/libusb#492]
Wrong bus number reported for AppleUSBRootHubDevice (MacOS 10.13.6 High Sierra). 
Try latest code with fix for https://github.com/libusb/libusb/pull/428, but nothing changes.

All three AppleUSBRootHubDevices are reported at bus 26.

05ac:8006 (bus 26, device 0)
05ac:8006 (bus 26, device 0)
05ac:8006 (bus 26, device 0)

Expected to be;

05ac:8006 (bus 26, device 0)
05ac:8006 (bus 29, device 0)
05ac:8006 (bus 20, device 0)

Console output;

Admins-Mac-mini:examples administration$ ./listdevs
10c4:8293 (bus 20, device 21) path: 4
17ef:600e (bus 20, device 20) path: 2
046d:c31c (bus 20, device 19) path: 1
05ac:828a (bus 29, device 6) path: 1.8.1.3
05ac:8242 (bus 29, device 4) path: 1.8.2
0a5c:4500 (bus 29, device 3) path: 1.8.1
0424:2512 (bus 29, device 2) path: 1.8
8087:0024 (bus 29, device 1) path: 1
8087:0024 (bus 26, device 1) path: 1
05ac:8006 (bus 26, device 0)
05ac:8006 (bus 26, device 0)
05ac:8006 (bus 26, device 0)

Admins-Mac-mini:examples administration$  ioreg -p IOUSB
+-o Root  <class IORegistryEntry, id 0x100000100, retain 18>
  +-o AppleUSBEHCI Root Hub Simulation@1a000000  <class AppleUSBRootHubDevice, id 0x1000002ed, registered, matched, active, busy 0 (30 ms), retain $
  | +-o IOUSBHostDevice@1a100000  <class AppleUSBDevice, id 0x1000002ef, registered, matched, active, busy 0 (31 ms), retain 38>
  +-o AppleUSBEHCI Root Hub Simulation@1d000000  <class AppleUSBRootHubDevice, id 0x1000002fd, registered, matched, active, busy 0 (0 ms), retain 9$
  | +-o IOUSBHostDevice@1d100000  <class AppleUSBDevice, id 0x1000002ff, registered, matched, active, busy 0 (313 ms), retain 39>
  |   +-o IOUSBHostDevice@1d180000  <class AppleUSBDevice, id 0x10000031b, registered, matched, active, busy 0 (276 ms), retain 40>
  |     +-o BRCM20702 Hub@1d181000  <class AppleUSBDevice, id 0x10000032a, registered, matched, active, busy 0 (169 ms), retain 39>
  |     | +-o Bluetooth USB Host Controller@1d181300  <class AppleUSBDevice, id 0x100000359, registered, matched, active, busy 0 (44 ms), retain 44$
  |     +-o IR Receiver@1d182000  <class AppleUSBDevice, id 0x10000033b, registered, matched, active, busy 0 (76 ms), retain 38>
  +-o AppleUSBXHCI Root Hub Simulation@14000000  <class AppleUSBRootHubDevice, id 0x100000486, registered, matched, active, busy 0 (0 ms), retain 1$
    +-o USB Keyboard@14100000  <class AppleUSBDevice, id 0x100001494, registered, matched, active, busy 0 (9 ms), retain 40>
    +-o Lenovo USB Optical Mouse@14200000  <class AppleUSBDevice, id 0x1000014b5, registered, matched, active, busy 0 (10 ms), retain 38>
    +-o Telegesis USB Device@14400000  <class AppleUSBDevice, id 0x1000016d9, registered, matched, active, busy 0 (1609 ms), retain 23>

**Comment by mcuee** [comment]
What is the real use case here? Is this anomaly still valid now?

**Comment by mcuee** [comment]
FYI, for the latest version of libusb under my Mac Mini M1, the output is like this. The root hub is no longer listed.

```
mcuee@mcuees-Mac-mini libusb % sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29

mcuee@mcuees-Mac-mini libusb % ./examples/listdevs 
1915:1025 (bus 2, device 13) path: 2.5.6
04b4:8613 (bus 2, device 12) path: 2.5.2
04d8:0033 (bus 2, device 11) path: 2.5.1
0ac8:3420 (bus 2, device 10) path: 1.4
0bda:5411 (bus 2, device 9) path: 1.1
0a5c:21e8 (bus 2, device 8) path: 2.7
046d:c52b (bus 2, device 7) path: 2.2
1a40:0201 (bus 2, device 6) path: 2.5
05e3:0749 (bus 2, device 5) path: 5.1.1
0bda:5411 (bus 2, device 4) path: 1
0bda:0411 (bus 2, device 3) path: 5.1
1a40:0201 (bus 2, device 2) path: 2
0bda:0411 (bus 2, device 1) path: 5
```

**Comment by mcuee** [comment]
@timdesi I will close this issue for now. Please re-open if you have new info.
