### ISSUE TITLE
android platform open failed

### ISSUE THREAD

**Issue by VitoHed** [libusb/libusb#498]
in some android plate form , if receive attach message, then use libusb_open function, sometimes open failed, because the /dev/bus/usb/xxx/xxx may not create. what can I do ?

I solve the problem using sleep(1) like that:  but it not a beautiful resolution, and what's your suggest?

`int wait_count = 0;
static int _get_usbfs_fd(struct libusb_device *dev, mode_t mode, int silent)
{
	struct libusb_context *ctx = DEVICE_CTX(dev);
	char path[PATH_MAX];
	int fd;
	int delay = 10000;

	if (usbdev_names)
		snprintf(path, PATH_MAX, "%s/usbdev%d.%d",
			usbfs_path, dev->bus_number, dev->device_address);
	else
		snprintf(path, PATH_MAX, "%s/%03d/%03d",
			usbfs_path, dev->bus_number, dev->device_address);

	wait_count = 0;
	while(access(path, F_OK)){
		sleep(1);
		printf("wait for device node make...%d\n", wait_count);
		if(wait_count ++ >= 2)
		{
			printf("can't find device node\n");
			break;
		}
	}

	fd = _open(path, mode);
	if (fd != -1)
		return fd; /* Success */

	if (errno == ENOENT) {
		if (!silent) 
			usbi_err(ctx, "File doesn't exist, wait %d ms and try again", delay/1000);
   
		/* Wait 10ms for USB device path creation.*/
		nanosleep(&(struct timespec){delay / 1000000, (delay * 1000) % 1000000000UL}, NULL);

		fd = _open(path, mode);
		if (fd != -1)
			return fd; /* Success */
	}
	
	if (!silent) {
		usbi_err(ctx, "libusb couldn't open USB device %s: %s",
			 path, strerror(errno));
		if (errno == EACCES && mode == O_RDWR)
			usbi_err(ctx, "libusb requires write access to USB "
				      "device nodes.");
	}

	if (errno == EACCES)
		return LIBUSB_ERROR_ACCESS;
	if (errno == ENOENT)
		return LIBUSB_ERROR_NO_DEVICE;
	return LIBUSB_ERROR_IO;
}`

**Comment by grzegb** [comment]
My app in java/C++ uses libuvc and:
1. Creates intent filter for USB: `new Intent(ACTION_USB_PERMISSION)` and handles intent actions
1. Requests permission
1. Opens usb port `UsbDeviceConnection connection = mUsbManager.openDevice(device);`
1. Extracts file descriptor an passes it to libuvc and libusb `fd = connection.getFileDescriptor();`

**Comment by usbxyz** [comment]
android 7+ can not work

**Comment by mcuee** [comment]
Please try 1.0.22/1.0.23 to see if either one helps. I will close this for now. Please reopen if both 1.0.22 and 1.0.23 failed.

**Comment by mcuee** [comment]
Reopen this topic to allow more comments on Android.

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/pull/760

Not so sure if the above will help or not.

**Comment by mcuee** [comment]
Close this for now. Users can comment on other ticket.
