### ISSUE TITLE
Seg Fault when called libusb_exit() after a failed libusb_init();

### ISSUE THREAD

**Issue by notlistening** [libusb/libusb#511]
During some testing we found a senario where the library would not initalised correctly.

When running libusb in a docker container on armhf with QEMU 2.x as version of QEMU doesn't support netlink. 

So calling libusb_init() would fail and then it would call libusb_exit() to cleanup.

However this causes a segfault. This can be simplied by calling libusb_exit() first. 

I have not stepped through the code to see exactly where the issue is but i'd imagine is it a NULL pointer somewhere. 

Will post a patch if I get time to look at it. 

Also this behaviour/bug can be seen when other software fails in this way like pyusb.

**Comment by mcuee** [comment]
Can you reproduce this issue without QEMU? I do not think this is a libusb issue.

**Comment by hjelmn** [comment]
@mcuee We should probably strengthen the documentation of libusb_exit to indicate that it should not be called except after libusb_init is successfully invoked.

**Comment by mcuee** [comment]
I agree that documentation can be improved.
