### ISSUE TITLE
libusb is not working on windows for high speed devices ,but works fine for mac and linux

### ISSUE THREAD

**Issue by chaitanya77185** [libusb/libusb#515]
Hi,
I was working on libusb for data transfers between isochronous IN & OUT. For full speed devices it worked well but for high speed devices, the callback function transfer status is LIBUSB_TRANSFER_ERROR.
I tried to debug but nothing is happening.
But the same code is working for mac and linux.
I was using libusbk driver for windows.

Thanks & Regards,
Chaitanya.

**Comment by mcuee** [comment]
Try usbk?

**Comment by chaitanya77185** [comment]
Hi,
I have tried with usbdk driver , but there is small issue in windows 10.
The issue is the callback function for isochronous OUT transfers not
reporting the actual length of transfers,but transfer occurs while seeing
the captured bus trace.
This is not present in isochronous IN transfers, it is giving correct
actual length.
This issue only present in windows 10 only.In windows 7 everything is
working fine as expected.

**Comment by vijaykumarprathipati** [comment]
Can you please respond to this issue.

**Just to summarize, Isoch In and Out Full Speed Transfers are working fine. But HighSpeed Transfers are failing with Transfer Status as 1.**
Below are the samples with which the issue can be reproduced. Please rename the files to .c 
[isoch_out.txt](https://github.com/libusb/libusb/files/2982501/isoch_out.txt)
[isoch_in.txt](https://github.com/libusb/libusb/files/2982502/isoch_in.txt)


Thanks for all your help.
Vijay.

**Comment by chaitanya77185** [comment]
Hey,

I just signed the petition "Chief justice supreme court: Recall for
elections in Andhrapradesh with a ballot paper, as we people of andhra
believe" and wanted to see if you could help by adding your name.

Our goal is to reach 75,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/9xQg9RYcDn

Thanks!
chaitanya

**Comment by dickens** [comment]
Can you provide a debug log?

**Comment by mcuee** [comment]
@vijaykumarprathipati Can you try the WinUSB driver under Windows 10 with latest release or git?
Can you provide a debug log for both libusbk driver or WinUSB driver?

**Comment by dickens** [comment]
OP is not responding, so I'll close this for now.  Feel free to reopen if there is additional information to provide.
