### ISSUE TITLE
parse_endpoint fails when parsing devices on ubuntu

### ISSUE THREAD

**Issue by aili03** [libusb/libusb#522]
Issue description： parse_endpoint fails,when I use the libusb library to redirect the camera, prompt 
     “libusb: error [parse_endpoint] short endpoint descriptor read 0/2
      libusb: error [raw_desc_to_config] parse_configuration failed with error -1” 
camera infomation: mylumens DC125

note：1.This device works fine on Windows 
           2. What happens to the endpoint without the 'size' to parse
           3.When I try to add if 'size' is 0, the endpoint will not parse. The camera device can use it, but the screen will not show properly

I hope you can provide a direction to solve the issue

**Comment by mcuee** [comment]
Looks not a libusb issue and rather a device firmware issue. 

You may want to ask in libusb-devel mailing list to get better help.
