### ISSUE TITLE
Open 2 devices with same vendor_id and product_id

### ISSUE THREAD

**Issue by cotestatnt** [libusb/libusb#529]
Hello!
I need to open two distinct same type of device (with the same vendor id e product id) in the same application. 
I can open successfully one device with libusb_open_device_with_vid_pid(), but how can i do with 2 devices?

Thank you, in advance

**Comment by diabolo38** [comment]
You have to get dev list and do your own search

**Comment by cotestatnt** [comment]
I've done as you suggest and as i find the right devices i open it with libusb_open(dev, handler);

Thank you!
