### ISSUE TITLE
FAQ: Dead link to HIDAPI

### ISSUE THREAD

**Issue by Nickwiz** [libusb/libusb#543]
Minor nuisance.

FAQ: Does libusb support USB HID devices?

https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices

Links to Signal 11 homepage, which seems dead or at least is down. Perhaps link to GitHub page: https://github.com/signal11/hidapi instead.

Also curious to know if the project itself is alive. Last commit was in 2016 and the issue tracker looks to be filling up without much response. IDK. As in - would it be wise to use libusb over hidapi if the project has halted?

**Comment by LudovicRousseau** [comment]
Fixed.
Thanks.

I can't say about hidapi project liveness. I have not used it for a while.
