### ISSUE TITLE
open 2 device in the meantime ,some question

### ISSUE THREAD

**Issue by snikeguo** [libusb/libusb#548]
I have two identical devices: Dev0, Dev1; and wrote some code:
libusb_init(&gloal_ctx);
create_thread(libusb_handle_events_completed); //create a thread 
libusb_get_device_list(&devs);

libusb_open(devs[0],&handle0);
libusb_set_configuration(handle0);
libusb_claim_interface(handle0);

libusb_open(devs[1],&handle1);
libusb_set_configuration(handle1);
libusb_claim_interface(handle1);

libusb_bulk_transfer(handle0,some data);
libusb_close(handle0);
### **libusb_bulk_transfer(handle1,some data);//not return !!why??**
libusb_close(handle1);
libusb_exit(&gloal_ctx);
Q1:
if i  have 2 device,How many times do I need to call the libusb_init function?   1 or 2?
Q2:
libusb_bulk_transfer(handle1,some data);//not return !!why??

**Comment by mcuee** [comment]
Q1: one time.
Q2: You have to know the communication protocol. 

Question should be asked in the mailing list and not here. Please subscribe to the mailing list and ask there.
