### ISSUE TITLE
Minor issue in USBD status translation (WinUSB backend)

### ISSUE THREAD

**Issue by philemonf** [libusb/libusb#552]
While looking at the post-merged diff of the PR #284, I noticed that `usbd_status_to_libusb_transfer_status` (see code [here](https://github.com/libusb/libusb/blob/acaa806ed0d3ec0ee84697ae6bd9ae7a5d031ada/libusb/os/windows_winusb.c#L2541)), which is invoked for each isochronous packet to convert USBD status to `libusb_transfer_status` after the completion of an isochronous transfer, will always return `LIBUSB_TRANSFER_ERROR` in the event of an error as opposed to a more specific enum member such as `LIBUSB_TRANSFER_TIMED_OUT`.

This is most probably due to a misunderstanding in the [official documentation of USBD status](https://msdn.microsoft.com/de-de/library/ff539136(v=vs.85).aspx) which states that "the least significant 28 bits of USB status values are defined in the following table", but then lists full 32-bit values. As a result, the current code is comparing `status & 0x0fffffff` against these 32-bit values and falls back to `LIBUSB_TRANSFER_ERROR` if it does not find a corresponding error in the libusb world. Since erroneous USBD status always have the most significant bit set to 1, this fallback code path will always be taken :).

As a robustness improvement, I think that, since this conversion of status occurs after the transfer is completed, I think that `USBD_STATUS_PENDING` should be translated to `LIBUSB_TRANSFER_ERROR` as it should never happen once the transfer is completed. Furthermore, the documentation is confusing as it contains both hexadecimal and binary values, but based on [this](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.14393.0/shared/usb.h#L260), it occurs when the 4 most significant bits are 0b0100 and not 0x01 as the code mentions. As a result of the latter, my understanding is that the code already returns `LIBUSB_TRANSFER_ERROR` for `USBD_STATUS_PENDING`, but not explicitly.

If someone else has time and the ability to test it, feel free to take it :).

**Comment by dickens** [comment]
This was mostly addressed with PR #665 except for the pending case.  I'm not too concerned about that right now, but if it proves to be an issue we can revisit this.
