### ISSUE TITLE
Memory passed to ioctl is not initialized in reap_for_handle

### ISSUE THREAD

**Issue by liangyunwang** [libusb/libusb#555]
In function reap_for_handle (linux_usbfs.c), a double pointer is passed to usbfs through ioctl. The value of that pointer has not been initialized, and hence could trigger alert in some memory usage check tools.

**Comment by hjelmn** [comment]
Sure. Not really a bug but worth fixing to avoid having to ship a suppression file for libusb.

**Comment by liangyunwang** [comment]
I've sent a pull request for this tiny issue. Pretty trivial change.
