### ISSUE TITLE
libusb_get_device_list() list same device twice in Win 8.1

### ISSUE THREAD

**Issue by podonoghue** [libusb/libusb#56]
Hi,

I have been using libusb with a custom USB device for a few years without problem but when updating to a WIndows 8.1 machine there is an issue with the device appearing twice in the list returned from `libusb_get_device_list()`.

The really confusing thing is that the concurrence seems to depend on the serial number of the device.

The above occurs with my custom software but also can be seen with `listdevs` (offending device is `16d0:0567` and appears twice in the list with the same path):
```
...\libusb-1.0.19-rc1-win\examples\bin32>listdevs.exe
045e:07dc (bus 1, device 27) path: 3
2109:0811 (bus 1, device 26) path: 11.3
2109:0811 (bus 1, device 23) path: 11.3.4
045e:07be (bus 1, device 6) path: 7
17e9:4305 (bus 1, device 33) path: 11.3.1
046d:c52f (bus 1, device 18) path: 2.6
045e:07bf (bus 1, device 5) path: 8
1286:204b (bus 1, device 9) path: 6
2109:3431 (bus 1, device 7) path: 2.3
16d0:0567 (bus 1, device 4) path: 2.3.3
045e:07ca (bus 1, device 20) path: 2.5
045e:07cc (bus 1, device 29) path: 2
17e9:4305 (bus 1, device 33) path: 11.3.1
2109:3431 (bus 1, device 3) path: 2.3.4
045e:07c6 (bus 1, device 21) path: 11.1
16d0:0567 (bus 1, device 4) path: 2.3.3
045e:07bf (bus 1, device 5) path: 8
8086:9c31 (bus 1, device 1)
2109:3431 (bus 1, device 3) path: 2.3.4
045e:07cb (bus 1, device 28) path: 11
```
A similar device (same firmware apart from serial number) is only reported once:
```
C:\Users\podonoghue\Downloads\libusb-1.0.19-rc1-win\examples\bin32>listdevs.exe
045e:07dc (bus 1, device 27) path: 3
16d0:0567 (bus 1, device 13) path: 2.3.3
2109:0811 (bus 1, device 26) path: 11.3
2109:0811 (bus 1, device 23) path: 11.3.4
045e:07be (bus 1, device 6) path: 7
17e9:4305 (bus 1, device 33) path: 11.3.1
046d:c52f (bus 1, device 18) path: 2.6
045e:07bf (bus 1, device 5) path: 8
1286:204b (bus 1, device 9) path: 6
2109:3431 (bus 1, device 7) path: 2.3
045e:07ca (bus 1, device 20) path: 2.5
045e:07cc (bus 1, device 29) path: 2
17e9:4305 (bus 1, device 33) path: 11.3.1
045e:07c6 (bus 1, device 21) path: 11.1
045e:07bf (bus 1, device 5) path: 8
8086:9c31 (bus 1, device 1)
2109:3431 (bus 1, device 3) path: 2.3.4
045e:07cb (bus 1, device 28) path: 11
```
Any ideas where the problem lies?

bye

**Comment by mcuee** [comment]
On Fri, Mar 6, 2015 at 9:03 AM, podonoghue <notifications@github.com> wrote:

> The above occurs with my custom software but also can be seen with
> listdevs (offending device is 16d0:0567 and appears twice in the list with
> the same path) :
>
> ...\libusb-1.0.19-rc1-win\examples\bin32>listdevs.exe
>
Please use libusb-1.0.19 Windows binary and not rc1. Thanks.
And please post the output of "xusb -d 16d0:0567".

Make sure you did not install libusb-win32 filter over your
device.

-- 
Xiaofan

**Comment by podonoghue** [comment]
Hi Xiafan,

Appear to be the same results for libusb-1.0.19.

I have attached:

listdevs_fail.txt  - Failing result for listdevs (as before)
xusb_fail.txt – xusb report for failing device

listdev_ok.txt – listdevs OK report for other device
xusb_ok.txt – xusb report for OK device

The two device are meant to only differ in serial number.

bye

**Comment by bvernoux** [comment]
Does someone is working on this issue ?

**Comment by mcuee** [comment]
Seems no.

When you say that "the two device are meant to only differ in serial
number", what do you mean by that?

**Comment by bvernoux** [comment]
It means such configuration for 1st Board:
        ------------------ Device Descriptor ------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.00)
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x1D50
idProduct                : 0x60A1
bcdDevice                : 0x100
iManufacturer            : 0x01
 Language 0x0409         : "www.airspy.com"
iProduct                 : 0x02
 Language 0x0409         : "AIRSPY"
iSerialNumber            : 0x03
 Language 0x0409         : "AIRSPY SN:16C463C8212185C7"
bNumConfigurations       : 0x01

Then such configuration for 2nd Board:
        ------------------ Device Descriptor ------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.00)
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x1D50
idProduct                : 0x60A1
bcdDevice                : 0x100
iManufacturer            : 0x01
 Language 0x0409         : "www.airspy.com"
iProduct                 : 0x02
 Language 0x0409         : "AIRSPY"
iSerialNumber            : 0x03
 Language 0x0409         : "AIRSPY SN:16C463C8325D5FC7"
bNumConfigurations       : 0x01

And such type of configuration is not managed correctly by libusb.

**Comment by mcuee** [comment]
Most likely the device driver installation is the problem. Maybe you want
to uninstall the driver related to this device and the use Zadig to install
WinUSB driver again.

**Comment by bvernoux** [comment]
There is no need to install Zadig driver with Win7 & Win8.x with AirSpy as it is managed by the AirSpy firmware which use feature of Windows Auto WinUsb Install (see https://msdn.microsoft.com/en-us/windows/hardware/gg463179 or more details)

**Comment by mcuee** [comment]
I see. Just try to use Zadig and see if that makes any differences.

**Comment by mcuee** [comment]
Not hearing from the report and I do not see this as a libusb problem. Probably a driver problem or device problem. Will reopen with more information.

**Comment by podonoghue** [comment]
I am the original poster.

Please note that the issue posted by bvernoux is probably unrelated to the original issue which was a single device appearing more than once in the libusb list.

I am still waiting for a response from my second posting which supplied information requested.
I have no problem with you closing the issue but please don't indicate the reason as lack of response since I have provided all information requested and was awaiting a response.

I am no longer much interested in the issue as I added a check to remove repeated devices.

bye

**Comment by bvernoux** [comment]
podonoghue could you check if your issue always happen with libusb 1.20 ?
