### ISSUE TITLE
PC TO PC communication

### ISSUE THREAD

**Issue by nosleduc** [libusb/libusb#571]
Hi

Is it possible to use the library to communicate between two pcs  using USB 3 ?

I have a diy project that connects two pcs. 
The first one have a camera attached to it. This pc must send camera frames and receive orders from the second pc. The second pc is also here to process each frame and sends some results to the first one.
I cannot use ethernet.

**Comment by mcuee** [comment]
No libusb is for host to device communication only, no way to do host to host.
