### ISSUE TITLE
missing install-filter-win.exe

### ISSUE THREAD

**Issue by seginming** [libusb/libusb#576]
I have a Masoon power monitor devices which comes with a python SDK to measure realtime power usage through USB cable.

The Monsoon python library uses libusb which is suggested to be downloaded at The Monsoon python library uses. To use these SDK/API's on windows platform, The additional step of installing the libusb filter is necessary. 

However, only 32bit support is there. When i try to install this filter, i keep getting below error:
This is a 64bit operating system and requires the 64bit libusb-win32 installer application.

Is there a 64bit version of libusb filter installer available?
Please help.

**Comment by seginming** [comment]
btw, the 32bit version is downloaded at https://sourceforge.net/projects/libusb-win32/

**Comment by mcuee** [comment]
Closed. libusb-win32 is a separate project.
And you should use libusbK or Zadig for the task as mentioned in libusb-win32 project file download area.
