### ISSUE TITLE
Windows 10 IoT Core support

### ISSUE THREAD

**Issue by galvesribeiro** [libusb/libusb#577]
Hello folks,

Do we have support to build libusb native lib to Windows 10 IoT?

Thank you!

**Comment by mcuee** [comment]
I do not think so.

**Comment by photron** [comment]
AFAIK, Windows 10 IoT Core only supports UWP that lacks several Win32 APIs that libusb uses: WinUSB, SetupAPI, etc. Therefore, libusb would have to be ported to UWP to work on Windows 10 IoT Core.

**Comment by dickens** [comment]
No, libusb does not support this.
