### ISSUE TITLE
libusb block in handle_events().

### ISSUE THREAD

**Issue by Mason1989** [libusb/libusb#578]
1.platform:linux
2.in my code, I submit three rx transfers at the same time.in other thread,i send date to usb by submitting tx transfers.but,when usb is out, when my code running on libusb_handle_events_timeout(),it will be blocked in handle_events function.
3.how can I solve the problem like this,thanks for your help!

**Comment by mcuee** [comment]
Please use libusb mailing list for questions like this. You also need to add more information when asking there, like what is the device, the code snippets, etc.

**Comment by Mason1989** [comment]
Thanks.
Now, the problem have been solved. Maybe, we should sync the receive and send threads, then, it works well.
