### ISSUE TITLE
why wIndex is different between libusb0 and libusb1 ?

### ISSUE THREAD

**Issue by Sleepingbug** [libusb/libusb#581]
libusb0:
wIndex = 0x04;
ret = usb_control_msg(devh, 0x21,0x09, 0x0202, wIndex, data, data_length, 1000);

libusb1:
wIndex = 0x05;
ret = libusb_control_transfer(devh, 0x21,0x09, 0x0202, wIndex, data, data_length, 10000);

why wIndex is different between libusb0 and libusb1 ?

**Comment by hjelmn** [comment]
Can you give more info? wIndex is identical in libusb 0.1.x and libusb-1.0. Are you referring to libusb0 (windows)?  That is a completely different project.

**Comment by Sleepingbug** [comment]
Testing environment:

**Comment by Sleepingbug** [comment]
Testing environment:

**Comment by Sleepingbug** [comment]
Testing environment:
windows 10 , visual studio 2017 ,x64, C/C++

**Comment by hjelmn** [comment]
That isn't enough info. Were you using libusb0 (https://sourceforge.net/projects/libusb-win32/)? If so that has never been affiliated with libusb. They implemented their own version of the libusb API.

**Comment by Sleepingbug** [comment]
Thank you very much!
