### ISSUE TITLE
failed to receive data from usb device ( libusb_control_transfer )

### ISSUE THREAD

**Issue by Sleepingbug** [libusb/libusb#582]
Testing environment:
windows 10 , visual studio 2017 ,x64, C/C++

1,  i use libusb_control_transfer() to receive data from usb device.
it returns -9.  how to fix it ?

my code:
`
int main()
{
	libusb_device_handle *devh = NULL;
 
	int ret = libusb_init(NULL);
	if (ret < 0) {
		perror("libusb_init");
		return ret;
	}

	libusb_set_debug(NULL, LIBUSB_LOG_LEVEL_DEBUG );

	devh = libusb_open_device_with_vid_pid(NULL, VID, PID);

	if (!devh) {
		printf("libusb_open_device_with_pid_vid Error: %d,\n", ret);
		Sleep(1000);
		libusb_exit(NULL);
	}

	
	Sleep(1000);
	// claim interface
	int interface_number = 4;
	ret = libusb_claim_interface(devh, interface_number);

	if (ret < 0) {
		printf("libusb_claim_interface Error: %d,\n", ret);
		Sleep(2000);
		if (devh) {
			libusb_close(devh);
			devh = NULL;
		}
		return ret;
	}

	unsigned char readType = LIBUSB_ENDPOINT_IN | LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_RECIPIENT_DEVICE;// CTRL_IN;
	unsigned char readRequest = HID_GET_REPORT;
	uint16_t wReadValue = 0x0202;
	uint16_t wReadIndex = 0x83;// 0x03;
	uint16_t wReadBufSize = 0x10;
	unsigned char readBuf[16] = { 0 };
	ret = libusb_control_transfer(devh, readType, readRequest, wReadValue, wReadIndex, readBuf, wReadBufSize, 10000);
	printf("ret=%d\n", ret);

	//...
	
	return 0;
}`

2, logs:
`[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
...

[ 6.273137] [00003f0c] libusb: debug [libusb_alloc_transfer] transfer 00FAFEE0
[ 6.273330] [00003f0c] libusb: debug [libusb_submit_transfer] transfer 00FAFEE0
[ 6.274550] [00003f0c] libusb: debug [usbi_add_pollfd] add fd 2 events 1
[ 6.275005] [00003f0c] libusb: debug [composite_submit_control_transfer] using interface 4
[ 6.275473] [00003f0c] libusb: debug [hid_submit_control_transfer] will use interface 4
[ 6.275957] [00003f0c] libusb: warning [hid_submit_control_transfer] unsupported HID control request
[ 6.276509] [00003f0c] libusb: debug [composite_submit_control_transfer] using interface 6
[ 6.277032] [00003f0c] libusb: debug [libusb_claim_interface] interface 6
[ 6.277656] [00003f0c] libusb: debug [winusbx_claim_interface] claimed interface 6
[ 6.278119] [00003f0c] libusb: debug [parse_endpoint] skipping descriptor 25
[ 6.278667] [00003f0c] libusb: debug [parse_endpoint] skipping descriptor 25
[ 6.279208] [00003f0c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 04 to interface 6
[ 6.279696] [00003f0c] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 84 to interface 6
[ 6.280265] [00003f0c] libusb: debug [auto_claim] auto-claimed interface 6 for control request
[ 6.280774] [00003f0c] libusb: debug [winusbx_submit_control_transfer] will use interface 6
[ 6.281393] [00003f0c] libusb: debug [libusb_get_next_timeout] next timeout in 9.993173s
[ 6.281811] [00003f0c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 6.282274] [00003f0c] libusb: debug [handle_events] poll fds modified, reallocating
[ 6.285207] [00003f0c] libusb: debug [handle_events] poll() 2 fds with timeout in 9994ms
[ 6.289048] [00003f0c] libusb: debug [handle_events] poll() returned 1
[ 6.289171] [00003f0c] libusb: debug [windows_handle_events] checking fd 2 with revents = 0001
[ 6.290060] [00003f0c] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 6.291233] [00003f0c] libusb: debug [windows_transfer_callback] handling I/O completion with errcode 31, size 0
[ 6.291819] [00003f0c] libusb: debug [windows_transfer_callback] detected endpoint stall
[ 6.292324] [00003f0c] libusb: debug [libusb_release_interface] interface 6
[ 6.292892] [00003f0c] libusb: debug [auto_release] auto-released interface 6
[ 6.293343] [00003f0c] libusb: debug [usbi_handle_transfer_completion] transfer 00FAFEE0 has callback 01151960
[ 6.293848] [00003f0c] libusb: debug [sync_transfer_cb] actual_length=0
[ 6.295237] [00003f0c] libusb: debug [libusb_free_transfer] transfer 00FAFEE0
ret=-9
`

3, my usb device info: 
`
Interface Descriptor 4/0 HID, 2 Endpoints
Offset	Field	Size	Value	Description
0	bLength	1	09h	
1	bDescriptorType	1	04h	Interface
2	bInterfaceNumber	1	04h	
3	bAlternateSetting	1	00h	
4	bNumEndpoints	1	02h	
5	bInterfaceClass	1	03h	HID
6	bInterfaceSubClass	1	00h	
7	bInterfaceProtocol	1	00h	
8	iInterface	1	73h	"HID Interface"
HID Descriptor 
Offset	Field	Size	Value	Description
0	bLength	1	09h	
1	bDescriptorType	1	21h	HID
2	bcdHID	2	0101h	1.01
4	bCountryCode	1	00h	
5	bNumDescriptors	1	01h	
6	bDescriptorType	1	22h	Report
7	wDescriptorLength	2	0162h	354 bytes
Endpoint Descriptor 83 3 In, Interrupt, 10 ms
Offset	Field	Size	Value	Description
0	bLength	1	07h	
1	bDescriptorType	1	05h	Endpoint
2	bEndpointAddress	1	83h	3 In
3	bmAttributes	1	03h	Interrupt
	1..0: Transfer Type		......11 	Interrupt
	7..2: Reserved		000000.. 	
4	wMaxPacketSize	2	0040h	64 bytes
6	bInterval	1	0Ah	10 ms
Endpoint Descriptor 03 3 Out, Interrupt, 10 ms
Offset	Field	Size	Value	Description
0	bLength	1	07h	
1	bDescriptorType	1	05h	Endpoint
2	bEndpointAddress	1	03h	3 Out
3	bmAttributes	1	03h	Interrupt
	1..0: Transfer Type		......11 	Interrupt
	7..2: Reserved		000000.. 	
4	wMaxPacketSize	2	0040h	64 bytes
6	bInterval	1	0Ah	10 ms

`

**Comment by dickens** [comment]
A device stalls the control endpoint when the requested control transfer is not supported.  I'm going to close this as it does not appear to be a libusb problem.  If you can verify that this same request works properly on another OS, feel free to reopen the issue.
