### ISSUE TITLE
on the android 8 platfrom, libusb_init is ok，but libusb_get_device_list return 0 -- 1.0.22 is okay, regression in 1.0.23

### ISSUE THREAD

**Issue by laomengandroid** [libusb/libusb#584]
Use the sample you provided，Step by step；
1.added log on the testlibusb.c adb libusb Source code
2.will binaryed libusb1.0 Library push   /system/lib64
3.will binaryed testlibusb  push  /system/bin
4.adb shell  /system/bin/ testlibusb
5.view log printf:
   >libusb_init is successfull
        r = libusb_init(ctx);
	@printf("libusb_init==%d",r);   printf r ==0;
   >libusb_get_device_list return 0
     cnt = libusb_get_device_list(NULL, &devs);
	  if (cnt < 0)
		return (int)cnt;
        @printf("libusb_get_device_list==%d\n",cnt); ---> cnt==0

**Comment by wbing-xu** [comment]
I also found the same problem.
when i  reset to tag 'v1.0.22',  device can be found!

**Comment by hjelmn** [comment]
What version are you running?

**Comment by cnlohr** [comment]
It's broken in 1.0.23. I can't find any code path which can actually do enumeration on android in 1.0.23.

**Comment by sicauyanglei** [comment]
What can I do for this problem?

**Comment by sicauyanglei** [comment]
> ag 'v1.0.22

how can I do it

**Comment by cnlohr** [comment]
use `git checkout` to specify the older branch.  I.e. `git checkout v1.0.22` in the folder where you've checked out the source.

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/commit/2f3bc98b0d0f4766496df53c855685a5f0e5e7cf

Maybe this commit has some problems.

**Comment by mcuee** [comment]
#233 comment is relevant.

**Comment by laran002** [comment]
Parts of 2f3bc98, related to linux_scan_devices(), is reverted back in #637

**Comment by IXMSbhatt** [comment]
libusb_get_device_list still return 0 in android 7.1.1 too

**Comment by cnlohr** [comment]
Just checking - are you running on a rooted device with selinux set to not enforce?

**Comment by IXMSbhatt** [comment]
it's rooted device and selinux is not set. With libusb-1.0.22 it's working perfectly fine. I have revert back 1.0.23 to 1.0.22. Now my problem is solved with libusb-1.0.22.

**Comment by green-green-avk** [comment]
Hmm...
What do you think about this approach: <https://github.com/green-green-avk/LibUsbManager> as it uses <https://github.com/green-green-avk/libusb-1.0.23-android-helper-service-patch>?

Device enumeration and hot plug/unplug events are supported.
No existing software (if dynamically linked to **libusb**) recompilation are required (in case of some Linux distributition under **PRoot**).
Tested as a part of <https://github.com/green-green-avk/AnotherTerm>.

**Comment by hongguangli** [comment]
Thanks to Almighty github, and everyone on github.(translate.google 0_0)

**Comment by mcuee** [comment]
So there seems to be a regression from 1.022 to 1.023. For those who are interested in Android, root cause analysis and patches are welcome.

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/pull/760

Not so sure if the above will help.

**Comment by mcuee** [comment]
Please try 1.0.24 to see if it is okay in 1.0.24. Thanks.

**Comment by mcuee** [comment]
@IXMSbhatt and other users, please help to check if 1.0.24 release sorted out the issue. Thanks.

**Comment by mcuee** [comment]
I assume the issues have been sorted out in 1.0.24. Close for now. Please reopen if this is not sorted out.

And for Android users, please refer to Pull Requests #830 and #874.

Related discussions:
https://github.com/libusb/libusb/issues/717
https://github.com/libusb/libusb/issues/868

**Comment by adhiti33** [comment]
@mcuee 

Usb on android is not working for me. I am using latest v1.0.24. Can you confirm below understanding is right ?

1> https://github.com/libusb/libusb/pull/830/commits/ff03b23022782dfaf4bfbac54c6251aea4e5e613

>> Individually picking this patch did not work for me

2> https://github.com/libusb/libusb/pull/874

>> Do I need to directly pick libusb git from @xloem distribution ??

**Comment by mcuee** [comment]
Please comment on #830 if it does not work for you. Please try out #874.

**Comment by mcuee** [comment]
@adhiti33 BTW, does libusb-1.0.22 works for you or not? If it does not, then your issue is different from this one. Thanks.

**Comment by adhiti33** [comment]
@mcuee We can resolve this issue. I will discuss further in https://github.com/libusb/libusb/pull/874 and try it.
