### ISSUE TITLE
Solaris: fails to find USB devices on SPARC platform

### ISSUE THREAD

**Issue by kentsuji** [libusb/libusb#587]
On SPARC platform running Solaris, libusb-1 fails to find USB devices.  In sunos_fill_in_dev_info(), it reads the usb-dev-descriptor property and stores idVendor and idProduct to the dev_descr structure in *little endian*, as the following:

```
        descr = (struct libusb_device_descriptor *)rdata;
        bcopy(descr, &dpriv->dev_descr, LIBUSB_DT_DEVICE_SIZE);
        dpriv->dev_descr.bcdUSB = libusb_cpu_to_le16(descr->bcdUSB);
        dpriv->dev_descr.idVendor = libusb_cpu_to_le16(descr->idVendor);
        dpriv->dev_descr.idProduct = libusb_cpu_to_le16(descr->idProduct);
        dpriv->dev_descr.bcdDevice = libusb_cpu_to_le16(descr->bcdDevice);

```
However, when creating a device name for 'match_str' to be specified to sunos_physpath_to_devlink(),  it's using the idVendor and idProduct in dev_descr as is without converting them to the host endian that is *big endian*, as the following:

```
                snprintf(match_str, sizeof(match_str), "^usb/%x.%x",
                    dpriv->dev_descr.idVendor, dpriv->dev_descr.idProduct);

```

As a result, 'match_str' has a wrong device name and sunos_physpath_to_devlink() will fail to find the device path corresponding to the USB device.  This code works accidentally on x86, because the host endian is little endian on x86.
Please see my suggested fix attached.

Thanks,
Kenjiro
[sunos_usb.c.endian_patch.txt](https://github.com/libusb/libusb/files/3303099/sunos_usb.c.endian_patch.txt)

**Comment by dickens** [comment]
Looks like this was resolved in #628, so closing.
