### ISSUE TITLE
Kindle Fire HD 8 (1949:0231) not recognized in libusb 1.0.22

### ISSUE THREAD

**Issue by gleepy** [libusb/libusb#599]
mtp-detect reports:
    libmtp version: 1.1.15

    Listing raw device(s)
       No raw devices found.

Manually editing the udev rules file to add the device does not work.

**Comment by mcuee** [comment]
You have to provide more details like the OS version and libusb debug log.

**Comment by mcuee** [comment]
It is better to ask in the libusb-devel mailing list for questions.

**Comment by mcuee** [comment]
Close this for now.
