### ISSUE TITLE
Misc: libusbx issues (before the migration) available at http://libusb.org/report/1

### ISSUE THREAD

**Issue by LudovicRousseau** [libusb/libusb#61]
libusbx was the previous name of libusb.
libusbx issues can be found at http://libusb.org/report/1

See "Migration of the issues and milestones of libusbx into libusb " https://sourceforge.net/p/libusb/mailman/message/33499435/

**Comment by mcuee** [comment]
Looks like libusb.org is down.

**Comment by LudovicRousseau** [comment]
Maybe we can just close this 5 years old issue?
We have enough libusb issues and no need to take care of libusbx issues :-)

**Comment by mcuee** [comment]
Yes. I agree.

**Comment by mcuee** [comment]
Closed this one.
