### ISSUE TITLE
Why 7z

### ISSUE THREAD

**Issue by genifycom** [libusb/libusb#615]
Please developers. Why would you use 7z and not native Windows ZIP (as libusb-win32-bin-1.2.6.0.zip was provided).
I know we love our own tools, but do not force us to install more on development machines than we need to. Use the facilities that are already there.

**Comment by mcuee** [comment]
Build from source then.
1.0.23 does not even have a Windows binary now that there is no active Windows developer. It is not difficult to build libusb from source, using your existing development tools like Visual C++ or MinGW-w64 (MSYS2 recommended).

**Comment by mcuee** [comment]
Close this for now.
