### ISSUE TITLE
Misc: To release 1.0.24

### ISSUE THREAD

**Issue by hjelmn** [libusb/libusb#618]
Target to add windows hotplug support.

**Comment by mcuee** [comment]
Maybe we can delay the Windows hotplug to 1.0.25 and have a release 1.0.24 as early as possible.

**Comment by mcuee** [comment]
As per @mvp libusb 1.0.23 is broken in macOS Catalina. It also has major regression in Android.

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/pull/760 is good to have in 1.0.24 if possible.

**Comment by mvp** [comment]
@mcuee, #760 is merged now. Can you start release process for 1.0.24 now?

**Comment by mcuee** [comment]
I agree. Need to get agreement with other admins.
@hjelmn @dickens

**Comment by mvp** [comment]
Any update on the 1.0.24 release?

**Comment by dickens** [comment]
I have one last set of changes to get in for Windows (relating to examples) and then I can start the release.

**Comment by mvp** [comment]
Hate to be that guy, but is there any update on releasing 1.0.24?

**Comment by dickens** [comment]
> Hate to be that guy, but is there any update on releasing 1.0.24?

Yes, I'm finishing my last changes to the examples.  I expect to be done this week.

**Comment by dickens** [comment]
I've officially started the 1.0.24 release with rc1 available [here](https://github.com/libusb/libusb/releases/tag/v1.0.24-rc1).  I'll send out the announcement to the libusb-devel mailing list shortly.

**Comment by dickens** [comment]
Primary release work is finished with c6a35c5.  I'll send the announcement and upload Windows binaries to follow.
