### ISSUE TITLE
Dose 1.0.23 work with Android? 1.0.22 works.

### ISSUE THREAD

**Issue by TommySato** [libusb/libusb#623]
I replaced libusb1.0.so from 1.0.22 to 1.0.23 on my Android studio.
But libusb_get_device_list() always reports no device.
1.0.22 is OK.
linux_default_scan_devices() is not called because of compiler switch.
I think UDEV option have to be ON when compiling. 
Do you know how to turn it on?
I compile libusb1.0.so using ndk-build command on Windows10.

**Comment by laran002** [comment]
Is this a duplicate of #584

**Comment by mcuee** [comment]
2f3bc98

Maybe this commit has some problems.

**Comment by mcuee** [comment]
I have labeled this as duplicate for #584

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/pull/760

Not so sure if the above will help.

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/pull/760

Maybe users can try Pull Request 760.

**Comment by mcuee** [comment]
Close this for now. Please go to the main thread. #584
