### ISSUE TITLE
question: how to use this to control mouse click in windows

### ISSUE THREAD

**Issue by xoraxrax** [libusb/libusb#630]
is there any examples to test this idea?

------

best regards.

**Comment by pbatard** [comment]
What you are attempting to achieve won't work. As per the [libusb.info Wiki](https://github.com/libusb/libusb/wiki/Windows#Known_Restrictions):

> * HID keyboards and mice cannot be accessed using the native HID driver as Windows reserves exclusive access to them.

You'll need to use something that sits at a much higher level than the USB bus if you want to intercept or control mouse clicks in Windows. Please google how to do that, as you should have no trouble finding information.
