### ISSUE TITLE
Missing pre-built binaries for 1.0.23

### ISSUE THREAD

**Issue by achow101** [libusb/libusb#636]
Previous releases have a 7zip archive containing pre-built binaries, but 1.0.23 is missing these.

**Comment by hjelmn** [comment]
I don't have a windows system so I can not provide these. Hopefully one of the other maintainers will upload them at some point. 1.0.24 will likely come out (next couple of weeks) before that happens.

**Comment by mcuee** [comment]
@achow101 You can build libusb pretty easily under Windows using MinGW-w64 (MSys 2) or Visual C++. 

But unfortunately I do not really know how to build a proper release under Windows.

**Comment by mcuee** [comment]
@dickens Now you are back, maybe you can help. Thanks.

**Comment by dickens** [comment]
Binaries have been uploaded.
