### ISSUE TITLE
Cross compilation support

### ISSUE THREAD

**Issue by brandonros** [libusb/libusb#648]
Adding cross-compilation support (targeting static library for arm64) would allow this library to be added to the latest iPhoneOS (iOS) along with IOKit.framework + CoreFoundation.framework

This in theory would allow low level Thunderbolt -> USB device support, yes?

**Comment by LudovicRousseau** [comment]
Have you tried to cross-compile libusb?
- Using `./configure`?
- Using the Xcode project in the Xcode/ directory?

**Comment by mcuee** [comment]
Close this for now. 
To OP: please reopen if you have new info.
