### ISSUE TITLE
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access

### ISSUE THREAD

**Issue by duanbaihong** [libusb/libusb#654]
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found
libusb: error [darwin_claim_interface] interface not found

**Comment by hjelmn** [comment]
Error is self-explanatory. The device is in use by another program or a system driver.

Is this an HID device? If so please use hidapi instead.

**Comment by mcuee** [comment]
Close for now. The OP can reopen if needed.
