### ISSUE TITLE
Windows 7 32 bit: Additional line breaks at position 64

### ISSUE THREAD

**Issue by maxwell130631** [libusb/libusb#656]
Hi,
We read out a measurement device via the function hid_read_timeout. The strings we receive are usually about 180 characters, and this works fine on Windows 10 64 bit and Linux. However, on a Windows 7 32 bit machine, we suddenly have line breaks (0D 0A) every 64 characters. What could be the reason for our code to work differently on the Windows 7 32 bit machine.

**Comment by mcuee** [comment]
Please use libusb mailing list for technical support.
