### ISSUE TITLE
hotplug example not working on macOS Mojave

### ISSUE THREAD

**Issue by kakyoism** [libusb/libusb#660]
I tried to run the libusb sample code on macOS Majave

https://github.com/libusb/libusb/blob/master/examples/hotplugtest.c

only to find that the callbacks are not fired up when hotplugging in my iPhone to my Mac.

Is this a known issue?

The initialization and registration are all fine and the program was in the while loop waiting for events. It's just that the callbacks don't fire up.

**Comment by mcuee** [comment]
Please post the debug log.

**Comment by jhihn** [comment]
I am on Mojave and hotplug works fine for me.

**Comment by hisschemoller** [comment]
I have the same as @kakyoism ,  hotplugtest runs without error but no callbacks fired when I plug or unplug several USB devices. Two other examples, listdevs and testlibusb run fine.

Tried on two Macbooks with the same result. Macbook pro 2018, MacOS Mojave and Macbook pro 2010, OSX El Capitan. Libusb installed with Homebrew in both cases.

I'm just starting with c programming so I have not much knowledge. I don't know how to generate a debug log yet.

**Comment by dickens** [comment]
How are you invoking the hotplug example?  You must provide the VID and PID of the device you are interested in as command line arguments, otherwise it defaults to searching for VID 0x045a and PID 0x5005, which I believe is a Rio S10 MP3 player.

**Comment by kakyoism** [comment]
@dickens That's a surprise. Then how could I detect hogplugs from ANY USB devices?

**Comment by dickens** [comment]
> @dickens That's a surprise. Then how could I detect hogplugs from ANY USB devices?

The hotplug example would have to be enhanced to do that.  The example program is really meant to verify that hotplug works on your system given a specific device that you will be plugging in and out.

**Comment by seanm** [comment]
Seems like this ticket could be closed...
