### ISSUE TITLE
Control Transfer function not returning the actual length returned by the DATA packet

### ISSUE THREAD

**Issue by GarageGadget** [libusb/libusb#667]
Hi,

The Control Transfer function (sync) [_libusb_control_transfer_] not returning the actual length returned by the DATA packet but instead returning the size of the assigned buffer.

The issue appears to be the result of the _ControlTransfer_ returning True at which point the overlapped structure has the  _overlapped->InternalHigh_ set with the correct number of data bytes. 
The _windows_force_sync_completion_ function is called with the buffer size which is then used to set the _overlapped->InternalHigh_ to the buffer size overriding the actual received byte count.

I used _Wireshark_ to sniff the packets to verify the actual data  count returned by the Overlapped structure when returning from the ControlTransfer function is correct and not the buffer size.

**Example:**
My application is expecting 2 bytes but the _libusb_control_transfer_ returns 8 bytes which is the size of the buffer passed into the libusb_control_transfer.

**OS: Windows 10**

**Comment by mcuee** [comment]
Sorry but just wondering if you see the same thing under other OS like macOS or Linux if you have access to those OS.

**Comment by GarageGadget** [comment]
Hi,

 

The issue appears to be isolated to the Windows OS and is working on Raspbian without issue.

 

BR

**Comment by dickens** [comment]
Thanks for the report.  Fix coming soon.

**Comment by dickens** [comment]
Reopening as this isn’t quite fixed yet.  I’ll close it again with the proper fix.

**Comment by dickens** [comment]
This should now _really_ be fixed in 9c28ad219b654011783a42ec888ca87dbda704a6
