### ISSUE TITLE
Missing documentation for libusb_set_option

### ISSUE THREAD

**Issue by th-otto** [libusb/libusb#668]
libusb_set_debug was deprecated, in favour of libusb_set_option. But that function is lacking documentation which API version is needed (0x01000106 i think).

**Comment by dickens** [comment]
Not sure which documentation you are viewing, but the latest published one does have this available. See the [official documentation](http://libusb.sourceforge.net/api-1.0/group__libusb__lib.html#gaf6ce5db28dac96b1680877a123da4fa8l) for more info.
