### ISSUE TITLE
libatomic.a: No such file or directory

### ISSUE THREAD

**Issue by Mathew44** [libusb/libusb#671]
While compile Android libusb I have an error. I am using Windows and cmd. Do you have any ideas how to resolve it?

C:/Path/android-ndk-r20b-windows-x86_64/android-ndk-r20b/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open C:/Path/android-ndk-r20b-windows-x86_64/android-ndk-r20b/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a/libatomic.a: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Path/libusb-master/libusb-master/android/obj/local/armeabi-v7a/libusb1.0.so] Error 1

**Comment by Mugutech62** [comment]
@Mathew44  what is the fix for above issue?
Thanks
