### ISSUE TITLE
Maximum Transfer Size for bulk In transfer

### ISSUE THREAD

**Issue by winkingwolf** [libusb/libusb#672]
hi,
I use bulk transfer on winusb/win7, I use fill-submit-LIBUSB_CALL mode for bulk transfer. The biggest size of transfer seems to be 2MB, I want to transfer 5MB in one transfer,ONLY 2MB is in good transfer, the other part（5MB-2MB=3MB）is not in good transfer.

Is it because the limitation of WinUSB driver or something else?
What is the Maximum Transfer Size for bulk  transfer for Libusb?
OS:win7/winusb

**Comment by mcuee** [comment]
I believe that is a WinUSB driver limitation. It is said the limit is 2.1MB.

Ref: https://community.osr.com/discussion/189326/changing-maximum-transfer-size-pipe-policy-in-winusb

**Comment by mcuee** [comment]
Close this for now.
