### ISSUE TITLE
libusb_bulk_transfer not writing but return 0

### ISSUE THREAD

**Issue by Nailik** [libusb/libusb#673]
Hello,

i try to get a basic example running with `libusb_bulk_transfer` my problem is that it says all data is transferred to device and the method is 0, but it seems like nothing at all is transferred.

I'm using the option `libusb_set_option(context, LIBUSB_OPTION_USE_USBDK);` otherwise `libusb_claim_interface` returns -3.

I have it runnin on windows 10 and i try to transfer data to a Sony Camera. I precaptured a working software and i'm sure that i have set the correct endpoint.

![Unbenannt](https://user-images.githubusercontent.com/13292441/71857265-37cd4700-30e7-11ea-87de-61700264488f.PNG)

Wireshark gives this output but only after i call `libusb_close(deviceHandle);` and the shown URB_BULK out is also done when i don't use `libusb_bulk_transfer`  so i think it's a thing called by libusb.

.... I hope someone can point out my problem, how can i send data to the device?

**Comment by mcuee** [comment]
For question like this it is better to use the mailing list. Thanks. You also need to show the code snippets. And you also need to know the protocols in order to talk to the USB device.
