### ISSUE TITLE
libusb_open failed on Win10 Dell XPS 15 laptop

### ISSUE THREAD

**Issue by garfungiloops** [libusb/libusb#691]
Windows 10, Dell XPS 15 (9550), different USB sticks, libusb 1.0.23

1. libusb_get_device_descriptor - works fine!

2. libusb_open - fails with the code "LIBUSB_ERROR_NO_DEVICE = -4" when usb-stick is connected to the Dell Thunderbolt TB16 dock.

3. libusb_open - fails with the code "LIBUSB_ERROR_NOT_SUPPORTED = -12"  when the same usb device is connected to the Dell XPS 15 laptop usb directly

All USB sticks were checked with the free tool UsbDevView (https://www.nirsoft.net/utils/usb_devices_view.html) whcih displays all descriptors correctly.

**Comment by dickens** [comment]
Please provide a debug log.

**Comment by mcuee** [comment]
Hmm, is this USB Flash Drive?

**Comment by garfungiloops** [comment]
yes this is USB flash.
But I have already realized that the problem was perhaps that I had no WinUSB driver installed.
For my project I need a solution that works without any extra drivers.
So I decided to switch to libusbp (which works in my case).
I think you can close the issue.
