### ISSUE TITLE
Can't use usb webcam in Windows remote host (Windows 10) from ubuntu vm

### ISSUE THREAD

**Issue by myjimmy** [libusb/libusb#694]
**Describe the bug**
I installed Ubuntu 18.04 64 bit virtual machine in VMware 15.0.4 and Windows 10 64bit.
Also, I installed Windows 10 64bit virtual machine as a remote host.
I plugged the USB webcam on my computer and connected it to ubuntu virtual machine.
![attach-webcam](https://user-images.githubusercontent.com/52309150/74639414-8a823000-5176-11ea-937b-331f9ab2d3e6.png)

In ubuntu vm, I run the following command:
`$ sudo xfreerdp /v:192.168.77.134 /u:ptc /dvc:urbdrc,dev:1908:2311`
192.168.77.134 is Windows 10 virtual machine.
![terminal-command](https://user-images.githubusercontent.com/52309150/74639686-fcf31000-5176-11ea-99b0-efd7a5660a2a.png)

**Error**
Then, I get the following error:
```
... ... ...
VID: 0x1908, PID: 0x2311
libusb_set_configuration: error LIBUSB_ERROR_OTHER [-99]
Set interface altsetting get error num -99
libusb_control_transfer LIBUSB_ERROR_PIPE [-9]
... ... ...
```

![terminal-error](https://user-images.githubusercontent.com/52309150/74641516-19447c00-517a-11ea-94f7-8631815bce15.png)

I can see the webcam item on the camera page of Chrome web browser in about 20s.
![chrome-camera-page](https://user-images.githubusercontent.com/52309150/74642001-e64eb800-517a-11ea-873f-baa5c10258d5.png)

But I can't use this device in the webRTC sample pages such as the following pages:
https://simpl.info/getusermedia/sources/
https://webrtc.github.io/samples/src/content/getusermedia/gum/
![webrtc-sample-page](https://user-images.githubusercontent.com/52309150/74642202-39286f80-517b-11ea-9aa9-9e1dd0019ac7.png)

** Application details
* Version of FreeRDP : latest version of master branch
* Command line used : sudo xfreerdp /v:192.168.77.134 /u:ptc /dvc:urbdrc,dev:1908:2311

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 64bit (libusb 1.0.21)

Thanks for any help.

**Comment by diabolo38** [comment]
I had functional issue using several devices (most usb3 bulk ) on VM under Window  (VMware and Virtual Box)
Device detection works so it's fine for device detection and  driver iinstall test  but i can't run most functional test they fail  while they  run just fine on real machines.
So it is likely a VM issue not  libusb one

**Comment by mcuee** [comment]
I think you have to ask the VM vendor. Traditionally there are multiple issues with VM's USB driver.
