### ISSUE TITLE
Add vcpkg installation instructions

### ISSUE THREAD

**Issue by NancyLi1013** [libusb/libusb#708]
`libusb`  is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for libusb and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build libusb, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/libusb/portfile.cmake) We try to keep the library maintained as close as possible to the original library.

I try to add vcpkg installation instructions but I couldn't find the related docs in github except for on https://github.com/libusb/libusb/wiki page.

Could you please help add the following contents to this port?

Installing and building libusb via vcpkg

You can download and install libusb using the vcpkg dependency manager:

     git clone https://github.com/Microsoft/vcpkg.git
     cd vcpkg
     ./bootstrap-vcpkg.bat
     ./vcpkg integrate install
     vcpkg install libusb

The libusb port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.

Thanks.

**Comment by LudovicRousseau** [comment]
I don't think we should document how to use vcpkg in the libusb project.
vcpkg documentation should be in the vcpkg project as it is now as you indicate.

libusb already refused to provide configuration files to support this or that software distribution. The problem is that the documentation/files provided by the libusb project would soon become out of date.

**Comment by gregsskyles** [comment]
But it wouldn't hurt to document that, for example, "While we do not maintain this, Windows users might find it convenient to install `libusb` via `vcpkg` ([https://github.com/microsoft/vcpkg](url))"

**Comment by dickens** [comment]
Can you provide a PR with this addition?

**Comment by NancyLi1013** [comment]
@dickens 
Do you mean that let me make a PR or someone else?
Since I have no idea about which document is suitable to be added in.
I am happy to add this if some suggestions are given.

**Comment by dickens** [comment]
> @dickens
> Do you mean that let me make a PR or someone else?
> Since I have no idea about which document is suitable to be added in.
> I am happy to add this if some suggestions are given.

I was suggesting that you make a PR if you wanted this information in the repo itself.  I would imagine INSTALL_WIN.txt is the best place for such an addition.

You can also consider the [Windows](https://github.com/libusb/libusb/wiki/Windows) page on the Wiki.

**Comment by NancyLi1013** [comment]
Since I have no permission to add this on WiKi.
I add the instructions to INSTALL_WIN.txt in PR #715.

Thanks for your suggestion.

**Comment by dickens** [comment]
Thanks for the PR.  If you have a suggested edit to the Wiki, I can facilitate that as well.

**Comment by mcuee** [comment]
vcpkg added to the Wiki Windows page.
https://github.com/libusb/libusb/wiki/Windows#vcpkg_port

**Comment by NancyLi1013** [comment]
Hi @dickens and @mcuee 
Thanks for your support and help.

I have noticed the info that you added to Wiki Windows page. It looks good.

Actually, it might be better if we can also add how to use `libusb `via vcpkg. In this case, the users may find that it is more simple to use libusb via vcpkg.

We can add the instructions to https://github.com/libusb/libusb/wiki/Windows#how-to-use-libusb-on-windows.
The contents can be like this:

```
Installing and building libusb via vcpkg

You can download and install libusb using the vcpkg dependency manager:

    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.bat
    ./vcpkg integrate install
    ./vcpkg install libusb

The libusb port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please create an issue or pull request(https://github.com/Microsoft/vcpkg) on the vcpkg repository.
```
In fact, vcpkg supports multiple platforms(Windows, linux and MacOS). But only adding to windows is enough.

**Comment by mcuee** [comment]
Done. Please check if the following is okay or not.
https://github.com/libusb/libusb/wiki/Windows#vcpkg_port

**Comment by NancyLi1013** [comment]
It's so nice. 
LGTM now. Thanks for your hard work. @mcuee

**Comment by NancyLi1013** [comment]
Thanks for your correction. @Gustavomurta `"./" ` should be used on Unix platform. For Windows, it should be `".\"`.

**Comment by mcuee** [comment]
> > I believe you instruction will not work under Windows Terminal.
> 
> I tested it in Windows 10, in the **Visual Studio 2019 Developer Command Prompt** and then I tested it again in the **command prompt window**.

I know your instruction works under the cmd.exe command prompt. I am just saying it does not work with Windows Terminal if you use Powershell. So the wiki instruction is more generic and it should work under both cmd.exe and powershell.

I use Powershell under Windows Terminal now much more often than command prompt.
