### ISSUE TITLE
libusb on android 9

### ISSUE THREAD

**Issue by mm-tk** [libusb/libusb#720]
Is it possible to run this libusb library on android 9 ?
If yes, so which version should I use.
Please give me some hints.

**Comment by LudovicRousseau** [comment]
See https://github.com/libusb/libusb/wiki#supported-environments

> Android -- [status: EXPERIMENTAL]

**Comment by mm-tk** [comment]
Support or not ?

**Comment by mcuee** [comment]
Supported but may have issues -- that is why it is stated as "EXPERIMENTAL".
