### ISSUE TITLE
Missing INSTALL file listed in `.gitignore`?

### ISSUE THREAD

**Issue by shardros** [libusb/libusb#742]
Hello,

I was trying to install using msys by following the instructions in `INSTALL_WIN.txt`:

```
Installation Instructions for Windows
*************************************

If you are compiling for MinGW or cygwin, please refer to the INSTALL file.
```

The `INSTALL` file isn't present in the repo but has been added to the `.gitignore`?

Thank you

**Comment by LudovicRousseau** [comment]
The `INSTALL` file is generated by the autotools.
It is included in the generated `.tar.gz` for example https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.tar.bz2
