### ISSUE TITLE
Issue running commands - RZUSB USB Semantical Error

### ISSUE THREAD

**Issue by grf240** [libusb/libusb#748]
![85795793-dd608b00-b706-11ea-9f5a-bae2653bf747](https://user-images.githubusercontent.com/67398124/86066354-eec7d100-ba3f-11ea-9b78-a71e6b2b9810.jpg)

Installed all dependencies, Scapy and KillerBee, as well as having the RZUSB Stick Flashed with the KillerBee firmware, but cannot utilize. I am running a USB persistence Kali Linux and using "root" to run. ZBID works just fine and recognizes the RZUSB Stick.

Can I get some advice as to where I might be going wrong or if there is an issue with the code?

Thanks!

**Comment by mcuee** [comment]
This has nothing to do with libusb. Close for now. Please ask the relevant project.
