### ISSUE TITLE
Handle leak in windows backend

### ISSUE THREAD

**Issue by BiroBalazs** [libusb/libusb#76]
Hi all,

It is not a big issue/problem, I thought it would be good to let you know about this.
The function windows_init from windows_usb.c creates a mutex : 
   ...
   usbi_mutex_init(&autoclaim_lock, NULL);
   ...
This mutex won't be destroyed in windows_exit, so with repeated connections (e.g. a stress test) these open handles can accumulate.

Thank you.

**Comment by dickens** [comment]
Thanks for reporting this. The issue has been fixed.
