### ISSUE TITLE
deadlock in handle_iso_completion after uvc_stream_stop 

### ISSUE THREAD

**Issue by ccdcn** [libusb/libusb#770]
Hi, 
I am running libuvc on my android device.
Sometimes I have a dead lock in
usbi_mutex_lock(&itransfer->lock);  
in entering handle_iso_completion,  after calling uvc_stream_stop,
bcz uvc_stream_stop free the lock in libusb_cancel_transfer right after set running flag = false,
and then the lock seems can't be obtained in handle_iso_completion.
Any idea to fix this ?

**Comment by diabolo38** [comment]
Lock come invalid as freed look like  theirs a racy or bad use of the flag 
BTW is the handle event called from the application and in it s for w/o the flags? If so then that is likely  the reason why

**Comment by mcuee** [comment]
Please post the code snippets and debug log.

**Comment by ccdcn** [comment]
Got it.
I should have report this is issue in libuvc project.
Thanks.
