### ISSUE TITLE
libusb provides duplicate entries 

### ISSUE THREAD

**Issue by ginkoob** [libusb/libusb#78]
I have two usb devices connected to my computer. lsusb shows a duplicate ID instead of individual entries 

Bus 001 Device 039: ID 19d2:1405 ZTE WCDMA Technologies MSM 
Bus 001 Device 033: ID 19d2:1405 ZTE WCDMA Technologies MSM 

---- 
Tested wotj lsusb (usbutils) 007
OS: Ubuntu  15.04

**Comment by PhilOsIvan** [comment]
Why ID sould be different if this is the same devices?
If difference is only in device path then you will need use libusb_get_port_numbers.

**Comment by dickens** [comment]
The list shows two devices on the same bus with different addresses, and by all appearances the two devices are the same. This is to be expected if you indeed have two of the same device connected to the host. Are you saying that two *different* devices are being reported with the same VID/PID and descriptor strings?

**Comment by ginkoob** [comment]
@Chris yes, both have same VID/PID. It's a common practice on ZTE, huawei
devices.

**Comment by dickens** [comment]
On Saturday, August 1, 2015, ginkoob <notifications@github.com> wrote:

> @Chris yes, both have same VID/PID. It's a common practice on ZTE, huawei
> devices.


Then what exactly is the issue? This is the expected result.

**Comment by dickens** [comment]
I think there is a misunderstanding of the lsusb output. The "ID" listed here is not something unique generated by libusb, it is <VID>:<PID> as reported by the device in the device descriptor. Therefore I am closing this issue.
