### ISSUE TITLE
Loop starvation bug

### ISSUE THREAD

**Issue by mildsunrise** [libusb/libusb#780]
I'm using libusb integrated with a custom event loop (Node.js) and it seems libusb is vulnerable to loop starvation. That is, if USB events arrive fast enough then `libusb_handle_events_timeout` never returns, preventing the rest of the event loop tasks from running.

I still need to verify, but this code looks like the culprit, `reap_for_handle` is repeatedly called in an infinite loop:

https://github.com/libusb/libusb/blob/4b64ecc6409ff3533b00153c65e02099c6ca55a9/libusb/os/linux_usbfs.c#L2671-L2673

**Comment by dickens** [comment]
I suppose if the transfer callback does a lot of work this could happen.  I don't know if this is really a bug.

**Comment by mildsunrise** [comment]
this can happen anytime events arrive faster than processed (be it because of heavy callbacks, CPU scarceness or high traffic)

to prevent loop starvation, it's common to place a rough limit on the amount of iterations, see [an example](https://github.com/libuv/libuv/blob/aa4fcc49a29bb55928d5d519c179a1ba3f9d71b7/src/unix/udp.c#L258)
