### ISSUE TITLE
How to know the device driven by which driver? Windows.

### ISSUE THREAD

**Issue by PeterPeterPan** [libusb/libusb#783]
In my case, 
Cam-1 driven by Microsoft
Cam-2 driven by libusbk

I want to get Cam-2 only, after using func libusb_get_device_list.
How can I do?

thanks

**Comment by mcuee** [comment]
Please use libusb mailing list for questions. Thanks.

**Comment by mcuee** [comment]
Read the Windows wiki as well. Thanks.
https://github.com/libusb/libusb/wiki/Windows#How_to_use_libusb_on_Windows
