### ISSUE TITLE
i met a problem in some device: WDI_ERROR_NEEDS_ADMIN

### ISSUE THREAD

**Issue by ShiverZm** [libusb/libusb#785]
i used Administrator privilige to run this exe,but it stil exited. And my roler also is Administrator.

**Comment by ShiverZm** [comment]
forget it, i used libusb-win32,inf-wizard.exe

**Comment by mcuee** [comment]
libusb-win32 is a different project. And libusb-win32 inf-wizard has already been deprecated. You should use Zadig.

**Comment by ShiverZm** [comment]
thanks for your mention,Zadig,

**Comment by dickens** [comment]
Why is this reopened?  What is the problem within libusb?

**Comment by ShiverZm** [comment]
it was mistake that i pressed,sorry,and may i ask a additional question ?how to uninstall libusb-win32
