### ISSUE TITLE
Misc: Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [libusb/libusb#79]
I have seen that [no loop is used around a call](https://github.com/libusb/libusb/blob/9b2c8abf134b96b6c1798615e0ed17991b8c0692/libusb/io.c#L1887) of the function "[usbi_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html)".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7)"?

**Comment by mcuee** [comment]
Close this aging request. Please re-open if you think it is wrongly closed.

**Comment by elfring** [comment]
Unfortunately, I can not reopen this issue myself here directly.

How do you think about to clarify [the affected implementation details](https://github.com/libusb/libusb/blob/a90331a3be0a7919dfd256d700c38cfad5718575/libusb/io.c#L1965 "Update candidate: libusb_wait_for_event()") further?
