### ISSUE TITLE
WinUSB: Functionality broken if there is a "Device Descriptor Request Failed" device in the system

### ISSUE THREAD

**Issue by bohdan-tymkiv** [libusb/libusb#791]
The 'libusb_get_device_list' stops enumerating devices and returns -1 if such device is present in the system.
![image](https://user-images.githubusercontent.com/10281082/94716735-f5742600-0357-11eb-9658-f519f629380c.png)

I've narrowed down the issue to commit https://github.com/libusb/libusb/commit/d21956dc

Simple change of this line 
https://github.com/libusb/libusb/blob/d21956dc3357bb40cde6d47eaf2497caf8d0a2de/libusb/os/windows_winusb.c#L844
to 
```
if (conn_info.ConnectionStatus == NoDeviceConnected || \
    conn_info.DeviceDescriptor.bNumConfigurations == 0) {
```
when applied on top of https://github.com/libusb/libusb/commit/d21956dc makes the issue go away.

However, such change leads to Segmentation fault when applied to current HEAD (https://github.com/libusb/libusb/commit/eee6998395184d87bd8e9c07ce2637caed1207f4).
I suspect that all special handling of LIBUSB_ERROR_NO_DEVICE is broken in current HEAD.

---- edit ---- 
```
> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

$ uname -a
MINGW64_NT-10.0-16299 host-name-removed 3.1.7-340.x86_64 2020-09-22 20:54 UTC x86_64 Msys
```

**Comment by VitaSokhatska** [comment]
any updates here? We'd like to understand whether it is going to be addressed somehow in the nearest releases

**Comment by Youw** [comment]
Confirm: seeing same issue on Windows 10.0.19041.572.
The patch suggested above does work for me too.

**Comment by Youw** [comment]
> However, such change leads to Segmentation fault when applied to current HEAD (eee6998).

Don't see any issues with c3deb6dd6440fd467ce12965742f2d7a228b3bbe.
