### ISSUE TITLE
Cannot access SFP module register

### ISSUE THREAD

**Issue by OopsLouie** [libusb/libusb#800]
Hi all,
i am using a CP2112 to connect double level PCA9548s, and using libusb to transfer data.
![image](https://user-images.githubusercontent.com/21199549/96853387-dd8e4e80-148c-11eb-85dc-85349a6ef4e2.png)

I can simply use i2c command to get info from 10GE SFP module connect to level 2 PCA9548.

But when i use libusb, it will crush and detect nothing when i read 0xa0 and 0xa2 from 10GE SFP module. By the way, if i use 25GE SFP module, libusb perfroms well!

here's the debug message:

`[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000011] [00000d41] libusb: debug [libusb_init] created default context
[ 0.000058] [00000d41] libusb: debug [libusb_init] libusb v1.0.19.10903
[ 0.000092] [00000d41] libusb: debug [find_usbfs_path] found usbfs at /dev/bus/usb
[ 0.000108] [00000d41] libusb: debug [op_init] bulk continuation flag supported
[ 0.000114] [00000d41] libusb: debug [op_init] zero length packet flag supported
[ 0.000127] [00000d41] libusb: debug [op_init] sysfs can relate devices
[ 0.000131] [00000d41] libusb: debug [op_init] sysfs has complete descriptors
[ 0.000449] [00000d42] libusb: debug [linux_udev_event_thread_main] udev event thread entering.
[ 0.001478] [00000d41] libusb: debug [linux_get_device_address] getting address for device: usb1 detached: 0
[ 0.001488] [00000d41] libusb: debug [linux_get_device_address] scan usb1
[ 0.001533] [00000d41] libusb: debug [linux_get_device_address] bus=1 dev=1
[ 0.001540] [00000d41] libusb: debug [linux_enumerate_device] busnum 1 devaddr 1 session_id 257
[ 0.001544] [00000d41] libusb: debug [linux_enumerate_device] allocating new device for 1/1 (session 257)
[ 0.001677] [00000d41] libusb: debug [linux_get_device_address] getting address for device: 1-2 detached: 0
[ 0.001685] [00000d41] libusb: debug [linux_get_device_address] scan 1-2
[ 0.001720] [00000d41] libusb: debug [linux_get_device_address] bus=1 dev=2
[ 0.001727] [00000d41] libusb: debug [linux_enumerate_device] busnum 1 devaddr 2 session_id 258
[ 0.001730] [00000d41] libusb: debug [linux_enumerate_device] allocating new device for 1/2 (session 258)
[ 0.001789] [00000d41] libusb: debug [linux_get_parent_info] Dev 0xe6c620 (1-2) has parent 0xe6c580 (usb1) port 2
[ 0.001906] [00000d41] libusb: debug [linux_get_device_address] getting address for device: usb2 detached: 0
[ 0.001922] [00000d41] libusb: debug [linux_get_device_address] scan usb2
[ 0.001962] [00000d41] libusb: debug [linux_get_device_address] bus=2 dev=1
[ 0.001974] [00000d41] libusb: debug [linux_enumerate_device] busnum 2 devaddr 1 session_id 513
[ 0.001984] [00000d41] libusb: debug [linux_enumerate_device] allocating new device for 2/1 (session 513)
[ 0.002110] [00000d41] libusb: debug [linux_get_device_address] getting address for device: 2-3 detached: 0
[ 0.002126] [00000d41] libusb: debug [linux_get_device_address] scan 2-3
[ 0.002165] [00000d41] libusb: debug [linux_get_device_address] bus=2 dev=2
[ 0.002187] [00000d41] libusb: debug [linux_enumerate_device] busnum 2 devaddr 2 session_id 514
[ 0.002196] [00000d41] libusb: debug [linux_enumerate_device] allocating new device for 2/2 (session 514)
[ 0.002234] [00000d41] libusb: debug [linux_get_parent_info] Dev 0xe6c760 (2-3) has parent 0xe6c6c0 (usb2) port 3
[ 0.002319] [00000d41] libusb: debug [usbi_add_pollfd] add fd 7 events 1
[ 0.002337] [00000d41] libusb: debug [usbi_add_pollfd] add fd 9 events 1
[ 0.002352] [00000d41] libusb: debug [usbi_io_init] using timerfd for timeouts
[ 0.002361] [00000d41] libusb: debug [usbi_add_pollfd] add fd 11 events 1
[ 0.002374] [00000d41] libusb: debug [libusb_get_device_list] 
[ 0.002403] [00000d41] libusb: debug [libusb_get_device_descriptor] 
[ 0.002416] [00000d41] libusb: debug [libusb_get_device_descriptor] 
[ 0.002426] [00000d41] libusb: debug [libusb_get_device_descriptor] 
The USB devices 10c4:ea90 found
[ 0.002447] [00000d41] libusb: debug [libusb_open] open 1.2
[ 0.002473] [00000d41] libusb: debug [usbi_add_pollfd] add fd 12 events 4
The USB handle found
The USB dev is 0xe6c620
The USB dev handle is 0xea6000
Kernel driver auto detach set
[ 0.002531] [00000d41] libusb: debug [libusb_claim_interface] interface 0
Interface Claimed
[ 0.017244] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.017279] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.017291] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.017469] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.017491] [00000d41] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=14
[ 0.017502] [00000d41] libusb: debug [handle_control_completion] handling completion status 0
[ 0.017512] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.017522] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.017533] [00000d41] libusb: debug [sync_transfer_cb] actual_length=14
SM bus initialized
[ 0.017556] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.017568] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.017584] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.017596] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.067591] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.067611] [00000d41] libusb: debug [handle_events] timerfd triggered
[ 0.067621] [00000d41] libusb: debug [libusb_cancel_transfer] 
[ 0.067721] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.067742] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 0ms
[ 0.067753] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.067765] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=-2 transferred=0
[ 0.067775] [00000d41] libusb: debug [handle_bulk_completion] handling completion status -2 of bulk urb 1/1
[ 0.067784] [00000d41] libusb: debug [handle_bulk_completion] abnormal reap: urb status -2
[ 0.067792] [00000d41] libusb: debug [handle_bulk_completion] abnormal reap: last URB handled, reporting
[ 0.067801] [00000d41] libusb: debug [usbi_handle_transfer_cancellation] detected timeout cancellation
[ 0.067810] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.067819] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.067828] [00000d41] libusb: debug [sync_transfer_cb] actual_length=0
Ongoing transfers flushed
[ 0.067849] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.067860] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.067876] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.067887] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.069064] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.069086] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.069096] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.069106] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.069124] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.069136] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.069146] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.069157] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 500ms (first in line)
[ 0.069168] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.069185] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.069196] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.070044] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.070066] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.070077] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.070086] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.070095] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.070105] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.070115] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.070126] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.070137] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.070153] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.070164] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.071035] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.071058] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.071068] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.071077] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.071086] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.071096] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.071106] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
Outstanding transfers cancelled
detecting 0xa0
[ 0.071158] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.071169] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.071186] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.071197] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.072042] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.072065] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.072075] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.072085] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.072094] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.072104] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.072114] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.072128] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.072140] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.072157] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.072169] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.073040] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.073062] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.073072] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.073082] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.073092] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.073102] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.073112] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.073132] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.073144] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.073160] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.073174] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.074039] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.074061] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.074071] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.074080] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.074089] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.074099] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.074110] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.075181] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.075195] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.075212] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.075223] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.076040] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.076062] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.076072] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.076082] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.076090] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.076100] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.076110] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.076120] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.076131] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.076147] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.076157] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.077039] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.077060] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.077070] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.077079] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.077088] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.077099] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.077108] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.078186] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.078200] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.078217] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.078228] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.079041] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.079063] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.079074] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.079083] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.079093] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.079103] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.079114] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.079125] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.079144] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.079160] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.079171] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.080038] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.080059] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.080070] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.080080] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.080089] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.080099] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.080110] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.081178] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.081193] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.081209] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.081220] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.082064] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.082086] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.082096] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.082105] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.082114] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.082125] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.082135] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.082146] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.082158] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.082174] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.082186] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.083039] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.083060] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.083070] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.083079] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.083089] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.083099] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.083109] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.083120] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.083131] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.083147] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.083167] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.084038] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.084060] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.084070] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.084079] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.084089] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.084098] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.084108] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.084118] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 500ms (first in line)
[ 0.084129] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.084145] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.084156] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.085038] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.085059] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.085069] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.085078] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.085087] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.085098] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.085107] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
[ 0.085124] [00000d41] libusb: debug [add_to_flying_list] arm timerfd for timeout in 50ms (first in line)
[ 0.085136] [00000d41] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.085152] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.085162] [00000d41] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.086037] [00000d41] libusb: debug [handle_events] poll() returned 1
[ 0.086059] [00000d41] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
[ 0.086070] [00000d41] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
[ 0.086079] [00000d41] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
[ 0.086088] [00000d41] libusb: debug [disarm_timerfd] 
[ 0.086098] [00000d41] libusb: debug [usbi_handle_transfer_completion] transfer 0xec6060 has callback 0x7f2c9ccc11d0
[ 0.086107] [00000d41] libusb: debug [sync_transfer_cb] actual_length=64
Timed out waiting on operation read with status 'address not acknowledged' at wait_for_transfer:341
Error<-1>: at my_process_read_response:361
Error<-1>: While waiting read (addr 0xa0) response at my_bf_pltfm_cp2112_read:1021
detecting 0xa0 result -1
[ 0.086147] [00000d41] libusb: debug [libusb_close] 
[ 0.086161] [00000d41] libusb: debug [usbi_remove_pollfd] remove fd 12
[ 0.086210] [00000d41] libusb: debug [libusb_exit] 
[ 0.086224] [00000d41] libusb: debug [libusb_exit] destroying default context
[ 0.086237] [00000d41] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.086248] [00000d41] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
[ 0.086258] [00000d41] libusb: debug [handle_events] poll() returned 0
[ 0.086267] [00000d41] libusb: debug [libusb_unref_device] destroy device 1.2
[ 0.086277] [00000d41] libusb: debug [usbi_remove_pollfd] remove fd 7
[ 0.086291] [00000d41] libusb: debug [usbi_remove_pollfd] remove fd 9
[ 0.086304] [00000d41] libusb: debug [usbi_remove_pollfd] remove fd 11
[ 0.086333] [00000d42] libusb: debug [linux_udev_event_thread_main] udev event thread exiting
`

I really need some help, thanks

**Comment by mcuee** [comment]
Please use libusb mailing list for question like this. Take note you need to understand the communication protocol.
