### ISSUE TITLE
Libusb output in QtCreator

### ISSUE THREAD

**Issue by kparent60** [libusb/libusb#811]
Hi everyone,

I have an issue with QtCreator and libusb. I'm using Qt5.14.2 with a libusb communication. QtCreator version is 4.11.0 community edition.

Each time I start my application, I always get the next message in my application output:

AllK required contiguous memory = 534200 (64bit)
  8 HotK Handles: HandleSize 2112 PoolSize 16912 (bytes)
  64 LstK Handles: HandleSize 64 PoolSize 4112 (bytes)
  1024 LstInfoK Handles: HandleSize 64 PoolSize 65552 (bytes)
  64 UsbK Handles: HandleSize 96 PoolSize 6160 (bytes)
  32 DevK Handles: HandleSize 112 PoolSize 3600 (bytes)
  4096 OvlK Handles: HandleSize 104 PoolSize 426000 (bytes)
  64 OvlPoolK Handles: HandleSize 96 PoolSize 6160 (bytes)
  32 StmK Handles: HandleSize 176 PoolSize 5648 (bytes)

Dynamically allocated as needed:
	KLST_DEVINFO = 2596 bytes each

This message seems to be purely informational since my application is working as it should even though I get the message (I might be wrong on that since there might be an issue I didnt catch yet). First, I didn't bother with it since I didn't used the console so far for debugging. But now, I want to use it and this message keeps popping. It seems like this message is refreshed every 2-3 seconds. My buffer gets spammed with it and it's becoming quite complicated to follow up my own debug messages.

I think this message is libusbk oriented from what I found online but my devices' drivers are using WinUSB so I'm not sure where it's coming from. I might even be on the wrong issue page for it.

If you have some informations on where this is coming from and how to disable it let me know.

Thank you in advance and have a good day 😄,
Keven

**Comment by dickens** [comment]
It comes from libusbK's DLL when its internal function `LibK_Context_Init()` is called.  These messages are unconditionally sent to the debugger via `OutputDebugString()` so there is nothing that can be controlled from the libusb side.  You could always compile libusbK from source and comment these messages out.

In any case, this is not a libusb issue so I am closing this.
