### ISSUE TITLE
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access

### ISSUE THREAD

**Issue by SindenDev** [libusb/libusb#817]
` 
bool USBDevice::openDevice(RawUSBDevice *dev)
{
    int opened = -1;
    if((nullptr == m_pDevice) && (nullptr != dev)){
        m_pDevice = dev;
        libusb_ref_device(m_pDevice);
        opened = libusb_open(m_pDevice, &m_pDeviceHandle);
        if(0 != opened){
            qWarning() << "open usb Reasnow device error!" << libusb_error_name(opened) << "vendorId:" << vendorId(dev) << "productId:" << productId(dev);
        }else{
//            printDeviceInfo(m_pDevice, m_pDeviceHandle);

            libusb_set_auto_detach_kernel_driver(m_pDeviceHandle, true);

            struct libusb_device_descriptor desc;

            opened = libusb_get_device_descriptor(m_pDevice, &desc);
            if (opened < 0) {
                qDebug() <<  "failed to get device descriptor" << libusb_error_name(opened);
                m_pDevice = nullptr;
                return opened;
            }

            for (int i = 0; i < desc.bNumConfigurations; i++) {
                USBConfigDescriptor *config;

                opened = libusb_get_config_descriptor(m_pDevice, i, &config);
                if (LIBUSB_SUCCESS != opened) {
                    qDebug("  Couldn't retrieve descriptors\n");
                    continue;
                }
                int nb_ifaces = config->bNumInterfaces;
                for (int iface = 0; iface < nb_ifaces; iface++){
                    qDebug("\nClaiming interface %d ...\n", iface);
                    opened = libusb_claim_interface(m_pDeviceHandle, iface);
                    if (opened != LIBUSB_SUCCESS) {
                        qWarning("Claim Interface  Failed !\n");
                    }
                }

                libusb_free_config_descriptor(config);
            }

            if(opened < 0){
                m_pDevice = nullptr;
                qWarning() << "open interface failed!" <<  libusb_error_name(opened);
            }else{
                qDebug() << "open usb Reasnow device OK!"<< m_pDevice << "vendorId:" << vendorId(dev) << "productId:" << productId(dev);
                m_isOpened = true;
                Q_EMIT isOpenedChanged(m_isOpened);
            }
        }
    }
    return opened;
}

`

I try build a remote desktop client on macOS, the system architecture is virt-viewer + spice-gtk + libusb. In order to achieve USB devices redirection, I try to access USB devices through libusb, but I met a problem, I plug in a USB mass storage device, and I got the error log like this：
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access

I have tried the methods described in the FAQ，but it's still not working
1, sudo kextunload -b com.apple.driver.AppleUSBFTDI,
and I got the return: com.apple.driver.AppleUSBFTDI not found for unload request. Failed to unload com.apple.driver.AppleUSBFTDI

2, sudo kextunload FTDIUSBSerialDriver.kext,
and I got: Unable to determine realpath for /FTDIUSBSerialDriver.kext - failing. Can't create FTDIUSBSerialDriver.kext

the libusb version I used is 1.0.23,
the macOS version is 10.14.6 Mojave

Is there any other ways to fix this problem?

**Comment by mcuee** [comment]
You can not use libusb with a USB mass storage under macOS.
USB mass storage does not use FTDI driver. There is no way to detach the USB storage driver.
