### ISSUE TITLE
Dynamic Linking Error, Symbol not found.

### ISSUE THREAD

**Issue by ganeshrvel** [libusb/libusb#818]
While trying to run a macos application which uses dylib is throwing:

```
Error: Dynamic Linking Error: dlopen(/Applications/Myapp.app/Contents/Resources/bin/mylib.dylib, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Myapp.app/Contents/Resources/bin/libusb.dylib
```

This was happening in macOS version 10.12.6. In Catalina this issue isn't happening.

How do I fix this?

**Comment by mcuee** [comment]
Please ask question in libusb mailing list to ask question like this. Thanks.
