### ISSUE TITLE
release 1.0.24

### ISSUE THREAD

**Issue by vovkos** [libusb/libusb#819]
An issue to ask a question.

When is the release 1.0.24 scheduled? The PR 483 (https://github.com/libusb/libusb/pull/483) by @jiez fixes a critical issue on some Windows installations. I would certainly prefer to use the official libusb binaries on Windows, but if it's not going to happen any time soon, I will make a custom build of libusb for my project.

Thank you!

**Comment by dickens** [comment]
Closing this.  Refer to #618 and please do not open issues to ask questions.
