### ISSUE TITLE
missing asset in release 1.0.24

### ISSUE THREAD

**Issue by vovkos** [libusb/libusb#822]
Happy to see version 1.0.24 being officially released!

However, the Windows binaries asset is missing. The official website https://libusb.info has a broken download link leading to:

https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.7z

**Comment by mcuee** [comment]
Yes you are right. Windows binary is not yet up.

**Comment by dickens** [comment]
Yes, working on it...

**Comment by dickens** [comment]
Uploaded, closing.
