### ISSUE TITLE
Assertion failed: (NULL == darwin_cached_devices.next), function darwin_init, file os/darwin_usb.c, line 584.

### ISSUE THREAD

**Issue by efe-star** [libusb/libusb#828]
hi. i am trying to use a tool using libusb. I installed libusb 1.0.24 and I am getting this error or whatever idk. And sorry about my English **
Operating system: Mac OS 11.0.1
Assertion failed: (NULL == darwin_cached_devices.next), function darwin_init, file os/darwin_usb.c, line 584.

what should I do ? 
Thanks..

**Comment by LudovicRousseau** [comment]
I guess you are using PyUSB Python wrapper.
See https://github.com/libusb/libusb/issues/824#issuecomment-743964046

**Comment by dickens** [comment]
Closing this as a duplicate of #824
