### ISSUE TITLE
LibUSBDotNet device communication issues on Windows7 64 bit HP EliteBook 840 G3 Model

### ISSUE THREAD

**Issue by AsNalage** [libusb/libusb#834]
I am connecting and communicating to the USB device successfully on all the windows (7, 8, 8.1, 10 - 32 bit and 64 bit).
But I am facing issues in communicating with USB device on one particular laptop i.e.  Windows7 64 bit HP EliteBook 840 G3 Model. On this laptop device works perfectly if I install windows7 32 bit and for Windos8, 10.  
I installed divers from libusbinfwizard.exe as well.
Below are the errors catched in USB error event.
ErrorCode    : Win32Error
Description : GetOverlappedResult failed. IoCtlCode:2237440 LibUsbDriverIO
Win32ErrorNumber : 1
Win32ErrorString : Incorrect function
Sender  : LibUsbDotNet.Internal.LibUsb.LibUsbDriverIO

**Comment by mcuee** [comment]
https://github.com/LibUsbDotNet/LibUsbDotNet
libusbdotnet is a seperate project.

Please go there for support. Thanks.
