### ISSUE TITLE
Synchronize the relative timestamps from libusb with the absolute ones in the system log

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb#853]
From here.
https://github.com/libusb/libusb/issues/237

From tormodvolden:
>Is there a trick to synchronize the relative timestamps from libusb with the absolute ones in the system log?

**Comment by dickens** [comment]
I guess it depends on which clock the system log uses.

Note that the user also has the option to use a log callback and use an alternate time stamp.

**Comment by mcuee** [comment]
Good point. I will leave this open for a while to see if there are more inputs. If not, I will close it.

**Comment by mcuee** [comment]
Close for now.
