### ISSUE TITLE
libusb_handle_events_timeout_completed not waiting on timeout

### ISSUE THREAD

**Issue by matallui** [libusb/libusb#858]
This started happening after upgrading from v1.0.23 to v1.0.24.

Calling:
```
libusb_handle_events_timeout_completed(ctx, tv, NULL)
```
with tv = 1 second

Before: it would wait 1 second before returning

After: returns immediately, which in our case causes our thread to use 100% CPU

**Comment by mcuee** [comment]
Please post more details, the OS version and libusb debug log (set LIBUSB_DEBUG=4).

**Comment by dickens** [comment]
I think I know the answer to this.  I suspect that a hotplug callback has been unregistered.  A bug was introduced when the event abstraction code was merged that leaves the `USBI_EVENT_HOTPLUG_CB_DEREGISTERED` set in the pending event flags.  This is addressed in #856.

**Comment by mcuee** [comment]
@matallui Please try out #856 patch to see if the issue goes away. Thanks.

**Comment by matallui** [comment]
Yes! That change seems to have fixed the issue. Thanks you guys!

**Comment by mcuee** [comment]
Pending #856 to be merged.

**Comment by mcuee** [comment]
Close this now that #856 has been merged.
