### ISSUE TITLE
libusb_claim_interface returned LIBUSB_ERROR_ACCESS on MacOS 11.1 Big Sur

### ISSUE THREAD

**Issue by ssroreo** [libusb/libusb#859]
hi
i'm using libusb to send data from Macbook to HID device,but my program failed.

`int rc = libusb_claim_interface(dev_handle, 0);
    if (rc < 0)
    {
        printf("failed！%d\n", rc);
        return 0;
    }`

it returned LIBUSB_ERROR_ACCESS.

how to solve this?

can i use libusb in MacOS to send data from macbook to hid devices?

**Comment by mcuee** [comment]
Please read the FAQ and use HIDAPI instead.
https://github.com/libusb/libusb/wiki/FAQ#Does_libusb_support_USB_HID_devices
