### ISSUE TITLE
libusb_interrupt_transfer return-1

### ISSUE THREAD

**Issue by wangdaao** [libusb/libusb#860]
When I use libusb1.0.24 to read and write with the mouse, I always return - 1. The error message is as follows:
libusb: error [hid_submit_bulk_transfer] HID transfer failed: [5] access denied。

**Comment by wangdaao** [comment]
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.006621] [00006f90] libusb: debug [libusb_get_device_list]  
[ 0.006748] [0000671c] libusb: debug [windows_iocp_thread] I/O completion thread started
[ 0.016820] [00006f90] libusb: debug [winusb_get_device_list] allocating new device for session [77]
[ 0.017156] [00006f90] libusb: debug [get_api_type] driver(s): HidUsb
[ 0.017185] [00006f90] libusb: debug [get_api_type] matched driver name against HID API
[ 0.017189] [00006f90] libusb: debug [winusb_get_device_list] allocating new device for session [54]
[ 0.017283] [00006f90] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.017308] [00006f90] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.017311] [00006f90] libusb: debug [winusb_get_device_list] allocating new device for session [55]
[ 0.017404] [00006f90] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.017429] [00006f90] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.017432] [00006f90] libusb: debug [winusb_get_device_list] allocating new device for session [56]
[ 0.017544] [00006f90] libusb: debug [get_api_type] driver(s): USBSTOR
[ 0.017575] [00006f90] libusb: debug [winusb_get_device_list] allocating new device for session [57]
[ 0.017679] [00006f90] libusb: debug [get_api_type] driver(s): HidUsb
[ 0.017704] [00006f90] libusb: debug [get_api_type] matched driver name against HID API
[ 0.017707] [00006f90] libusb: debug [winusb_get_device_list] allocating new device for session [58]
[ 0.017856] [00006f90] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_A2AF&SUBSYS_50071458&REV_00\3&11583659&0&A0' bus number 1
[ 0.018642] [00006f90] libusb: debug [winusb_get_device_list] found existing device for session [56]
[ 0.018691] [00006f90] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.018702] [00006f90] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 107 bytes)
[ 0.018712] [00006f90] libusb: debug [init_device] (bus: 1, addr: 34, depth: 1, port: 10): 'USB\VID_1FF7&PID_0001\00000400-511D4815-58F14000-02B09709'
[ 0.018770] [00006f90] libusb: debug [winusb_get_device_list] found existing device for session [55]
[ 0.018797] [00006f90] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.018805] [00006f90] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 59 bytes)
[ 0.018811] [00006f90] libusb: debug [init_device] (bus: 1, addr: 32, depth: 1, port: 5): 'USB\VID_1C4F&PID_0026\5&2108AD5D&0&5'
[ 0.018869] [00006f90] libusb: debug [winusb_get_device_list] found existing device for session [54]
[ 0.018894] [00006f90] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.018901] [00006f90] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 34 bytes)
[ 0.018908] [00006f90] libusb: debug [init_device] (bus: 1, addr: 41, depth: 1, port: 7): 'USB\VID_046D&PID_C077\5&2108AD5D&0&7'
[ 0.019036] [00006f90] libusb: debug [winusb_get_device_list] found existing device for session [58]
[ 0.019062] [00006f90] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.019070] [00006f90] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 34 bytes)
[ 0.019076] [00006f90] libusb: debug [init_device] (bus: 1, addr: 42, depth: 1, port: 8): 'USB\VID_0000&PID_0538\5&2108AD5D&0&8'
[ 0.019132] [00006f90] libusb: debug [winusb_get_device_list] found existing device for session [57]
[ 0.019157] [00006f90] libusb: debug [init_device] found 1 configurations (current config: 1)
[ 0.019164] [00006f90] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 32 bytes)
[ 0.019170] [00006f90] libusb: debug [init_device] (bus: 1, addr: 23, depth: 1, port: 3): 'USB\VID_23A9&PID_EF18\5&2108AD5D&0&3'
[ 0.019258] [00006f90] libusb: debug [init_root_hub] root hub 'USB\ROOT_HUB30\4&92B3C53&0&0' reports 20 ports
[ 0.019298] [00006f90] libusb: warning [init_root_hub] could not get node connection information (V2) for root hub 'USB\ROOT_HUB30\4&92B3C53&0&0' port 11: [87] 参数错误。
[ 0.019304] [00006f90] libusb: debug [init_device] (bus: 1, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\4&92B3C53&0&0'
[ 0.019531] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019536] [00006f90] libusb: debug [set_composite_interface] interface[0] = \\?\HID#VID_1FF7&PID_0001&MI_00&COL03#7&375D38D&0&0002#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.019552] [00006f90] libusb: debug [winusb_get_device_list] setting HID interface for [58]:
[ 0.019554] [00006f90] libusb: debug [set_hid_interface] interface[0] = \\?\HID#VID_0000&PID_0538#6&1047CE7A&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.019567] [00006f90] libusb: debug [winusb_get_device_list] setting HID interface for [54]:
[ 0.019569] [00006f90] libusb: debug [set_hid_interface] interface[0] = \\?\HID#VID_046D&PID_C077#6&F2E2A79&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.019598] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [55]:
[ 0.019600] [00006f90] libusb: debug [set_composite_interface] interface[1] = \\?\HID#VID_1C4F&PID_0026&MI_01&COL02#7&29899891&0&0001#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.019621] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019623] [00006f90] libusb: debug [set_composite_interface] interface[0] already set - ignoring HID collection: HID\VID_1FF7&PID_0001&MI_00&COL05\7&375D38D&0&0004
[ 0.019639] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019641] [00006f90] libusb: debug [set_composite_interface] interface[0] already set - ignoring HID collection: HID\VID_1FF7&PID_0001&MI_00&COL06\7&375D38D&0&0005
[ 0.019657] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [55]:
[ 0.019659] [00006f90] libusb: debug [set_composite_interface] interface[1] already set - ignoring HID collection: HID\VID_1C4F&PID_0026&MI_01&COL01\7&29899891&0&0000
[ 0.019674] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019676] [00006f90] libusb: debug [set_composite_interface] interface[0] already set - ignoring HID collection: HID\VID_1FF7&PID_0001&MI_00&COL01\7&375D38D&0&0000
[ 0.019692] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019694] [00006f90] libusb: debug [set_composite_interface] interface[0] already set - ignoring HID collection: HID\VID_1FF7&PID_0001&MI_00&COL04\7&375D38D&0&0003
[ 0.019710] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019712] [00006f90] libusb: debug [set_composite_interface] interface[0] already set - ignoring HID collection: HID\VID_1FF7&PID_0001&MI_00&COL07\7&375D38D&0&0006
[ 0.019727] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [56]:
[ 0.019729] [00006f90] libusb: debug [set_composite_interface] interface[0] already set - ignoring HID collection: HID\VID_1FF7&PID_0001&MI_00&COL02\7&375D38D&0&0001
[ 0.019745] [00006f90] libusb: debug [winusb_get_device_list] setting composite interface for [55]:
[ 0.019747] [00006f90] libusb: debug [set_composite_interface] interface[0] = \\?\HID#VID_1C4F&PID_0026&MI_00#7&5B25ACF&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}\KBD
[ 0.020441] [00006f90] libusb: debug [libusb_get_device_descriptor]  
[ 0.020516] [00006f90] libusb: debug [libusb_get_device_descriptor]  
[ 0.020571] [00006f90] libusb: debug [libusb_get_device_descriptor]  
[ 0.020628] [00006f90] libusb: debug [libusb_open] open 1.41
[ 0.020646] [00006f90] libusb: warning [hid_open] could not open HID device in R/W mode (keyboard or mouse?) - trying without
[ 0.020746] [00006f90] libusb: debug [hid_open] set maximum input buffer size to 512
[ 0.020760] [00006f90] libusb: debug [hid_open] 3 HID input report value(s) found
[ 0.020766] [00006f90] libusb: debug [hid_open]   Report ID: 0x00
[ 0.020768] [00006f90] libusb: debug [hid_open]   Report ID: 0x00
[ 0.020770] [00006f90] libusb: debug [hid_open]   Report ID: 0x00
[ 0.020772] [00006f90] libusb: debug [hid_open] 0 HID output report value(s) found
[ 0.020773] [00006f90] libusb: debug [hid_open] 0 HID feature report value(s) found
[ 0.022181] [00006f90] libusb: debug [libusb_unref_device] destroy device 1.34
[ 0.022191] [00006f90] libusb: debug [libusb_unref_device] destroy device 1.32
[ 0.022195] [00006f90] libusb: debug [libusb_unref_device] destroy device 1.42
[ 0.022198] [00006f90] libusb: debug [libusb_unref_device] destroy device 1.23
[ 0.022201] [00006f90] libusb: debug [libusb_kernel_driver_active] interface 0
[ 0.022262] [00006f90] libusb: debug [libusb_detach_kernel_driver] interface 0
[ 0.022266] [00006f90] libusb: debug [libusb_claim_interface] interface 0
[ 0.022268] [00006f90] libusb: debug [hid_claim_interface] claimed interface 0
[ 0.022276] [00006f90] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 81 to interface 0
[ 0.988098] [00006f90] libusb: debug [libusb_alloc_transfer] transfer 0591F8A8
[ 0.988112] [00006f90] libusb: debug [libusb_submit_transfer] transfer 0591F8A8
[ 0.988115] [00006f90] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 0.988129] [00006f90] libusb: debug [hid_submit_bulk_transfer] matched endpoint 81 with interface 0
[ 0.988132] [00006f90] libusb: debug [hid_submit_bulk_transfer] reading 5 bytes (report ID: 0x00)
[ 0.988148] [00006f90] libusb: error [hid_submit_bulk_transfer] HID transfer failed: [5] access denied。
[ 0.988152] [00006f90] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 0.988155] [00006f90] libusb: debug [libusb_free_transfer] transfer 0591F8A8
[ 0.988321] [00006f90] libusb: debug [libusb_get_device_descriptor]  
[ 1.991735] [00006f90] libusb: debug [libusb_alloc_transfer] transfer 0591F038
[ 1.991749] [00006f90] libusb: debug [libusb_submit_transfer] transfer 0591F038
[ 1.991752] [00006f90] libusb: debug [add_to_flying_list] arm timer for timeout in 1000ms (first in line)
[ 1.991757] [00006f90] libusb: debug [hid_submit_bulk_transfer] matched endpoint 81 with interface 0
[ 1.991760] [00006f90] libusb: debug [hid_submit_bulk_transfer] reading 5 bytes (report ID: 0x00)
[ 1.991774] [00006f90] libusb: error [hid_submit_bulk_transfer] HID transfer failed: [5] access denied。
[ 1.991776] [00006f90] libusb: debug [arm_timer_for_next_timeout] no timeouts, disarming timer
[ 1.991780] [00006f90] libusb: debug [libusb_free_transfer] transfer 0591F038

**Comment by mcuee** [comment]
Do not use libusb with an mouse. Read the libusb wiki. 

And please use libusb mailing list for questions.

**Comment by wangdaao** [comment]
But I read the mouse, keyboard, U disk and other USB devices are the same situation




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "libusb/libusb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 中午11:58
收件人:&nbsp;"libusb/libusb"<libusb@noreply.github.com&gt;;
抄送:&nbsp;"1593323923"<1593323923@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libusb/libusb] libusb_interrupt_transfer return-1 (#860)





 
Do not use libusb with an mouse. Read the libusb wiki.
 
And please use libusb mailing list for questions.

**Comment by mcuee** [comment]
Again, read the Wiki. You need to install the supported driver (eg: WinUSB) in order to use libusb under Windows.

**Comment by wangdaao** [comment]
Yeah, I've got it. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "libusb/libusb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 下午2:02
收件人:&nbsp;"libusb/libusb"<libusb@noreply.github.com&gt;;
抄送:&nbsp;"1593323923"<1593323923@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libusb/libusb] libusb_interrupt_transfer return-1 (#860)





 
Again, read the Wiki. You need to install the supported driver (eg: WinUSB) in order to use libusb under Windows.
