### ISSUE TITLE
Will the next version support the detection of USB hotplug  under wondows？？

### ISSUE THREAD

**Issue by yyang2021** [libusb/libusb#879]

**Comment by mcuee** [comment]
Please use the main thread for discussion. 
https://github.com/libusb/libusb/issues/86

**Comment by mcuee** [comment]
Next version will be 1.0.25 for bug fixes. Windows hotplug will most likely be 1.0.26 or later since we do not have enough resource to support Windows. Only Chris is working on Windows now and Windows codes are complicated as of now.

**Comment by yyang2021** [comment]
ok,thanks for your hard work.



---Original---
