### ISSUE TITLE
Windows: libusb_control_transfer

### ISSUE THREAD

**Issue by Lulz322** [libusb/libusb#880]
**Yo, i want to recreate control transfer request to a mice as seems below**

![image](https://user-images.githubusercontent.com/36892265/108826482-00607900-75cd-11eb-9895-b745cd55d539.png)

I used this code:
```
        dev_handle = libusb_open_device_with_vid_pid(ctx, USB_VENDOR_ID, USB_PRODUCT_ID);

	libusb_control_transfer(dev_handle, 0x40, 0x01, 0x0100, 0x010a, NULL, 0, 0);
``` 
On linux it works correctly, but on windows there are a few errors:
```
libusb: warning [hid_open] could not open HID device in R/W mode (keyboard or mouse?) - trying without
libusb: warning [hid_submit_control_transfer] unsupported HID control request
libusb: warning [hid_submit_control_transfer] unsupported HID control request
libusb: warning [hid_submit_control_transfer] unsupported HID control request
libusb: error [composite_submit_control_transfer] no libusb supported interfaces to complete request
```

How to fix that?

**Comment by diabolo38** [comment]
I kind of remember some back/end (HID/winusb) may limit control transfer toward interface 
and here if think your are doing a control targeting the device (req type => 0x40 for interface it would be 0xx1)

you can try changing your control toward interface or use different back-end 
I may have used  such dev control in the past with libusbk back end but am nto 100% sure

**Comment by mcuee** [comment]
You can not use libusb Windows with a mouse. This is mentioned in the wiki.
https://github.com/libusb/libusb/wiki/Windows#Known_Restrictions
HID keyboards and mice cannot be accessed using the native HID driver as Windows reserves exclusive access to them.

If you want to try it, you can use WinUSB driver for your mouse and then try again. But then it will lose the mouse function.
