### ISSUE TITLE
application crash on init

### ISSUE THREAD

**Issue by ehrenmann1977** [libusb/libusb#883]
I am trying to connect to a usb device but on the init the app crash, i have win 10 with and i disabled the updates to keep fast.

```
   libusb_context *ctx = NULL; //a libusb context for library intialization
    int r=libusb_init(&ctx);
    libusb_set_option(ctx, LIBUSB_OPTION_USE_USBDK);   //initializing the library

```

**Comment by mcuee** [comment]
If you want to use usbdk, you need to install usbdk. If not, please use WinUSB instead.

**Comment by mcuee** [comment]
Please also post the debug log by running your application with LIBUSB_DEBUG=4 set.

**Comment by mcuee** [comment]
Close for now. Please reopen if you can reproduce the issue and post the debug log.

**Comment by ehrenmann1977** [comment]
the issue was compiling the library again with my compiler mingw

**Comment by mcuee** [comment]
Thanks for the updates.
