### ISSUE TITLE
how libusb and HIDAPI work together

### ISSUE THREAD

**Issue by nxpfrankli** [libusb/libusb#885]
https://github.com/NXPmicro/mfgtools, uuu use libusb to implement image deployment at nxp boards.
Basically,  use HID talk with chip ROM to download a firmware to boards. Then switch to bulk transfer(andorid fastboot) to download big part. 

it worked well on windows and linux machine. but it met claim interface failure at MacOS when HID phase.

Unload HID driver on MacOS need signature key, which we have not gotten over years. 

So I consider use HIDAPI at ROM download Phase.  But I need make sure HIDAPI hid_open libusb_device is the same device, or at then same usb port. 

Our ROM have not serial ID.

**Comment by mcuee** [comment]
You should just use HIDAPI instead for HID device if you want it to work under macOS, to save the trouble.

Ref: I actually have an RFC to remove HID from libusb Windows backend.
https://github.com/libusb/libusb/issues/758

**Comment by nxpfrankli** [comment]
The problem is that I have to use the both libusb and hidapi.  Need a method identify that is the same device or the same usb port. 

for example, there are two boards A and B with the same chip and connect to one PC. 

I can use libusb enumerate all devices and list usb port path, and filter out board A. such as uuu -m 1:10. 

Then pass libusb_device_handle to HIDAPI open such device.

**Comment by mcuee** [comment]
I will say just forget about such a complicated method. Just go with HIDAPI for the chip download stage and libusb for the other stage. libusb will not work with HID device under macOS anyway.

**Comment by mcuee** [comment]
BTW, just wondering if you can change the CHIP ROM so as not to use HID at all, then you only need to use libusb.

**Comment by nxpfrankli** [comment]
we have to handle multi devices connect into one PC case.  Board A and Board B is the difference, but use the same chips, the same vid and pid.  How HIDAPI can distinguish A and B?

**Comment by nxpfrankli** [comment]
We can't change ROM, which is in the chip.

**Comment by nxpfrankli** [comment]
There are good reason to choose ROM at 10-15 years ago. HID have max compatibility and needn't develop driver for windows and linux.  All chip ROM follow up the the first success ROM.

**Comment by nxpfrankli** [comment]
unfortunately, our chip have not serial number because windows will add new entry at registry table when new device added.  For manufacturer, they will handle over 100k chips. windows system enumeration will become very slow.

**Comment by nxpfrankli** [comment]
Actually I have read API documents,  I need a method, how to map hid_device_info with libusb_device.  I need know that's the same port when HID switch to bulk io.

**Comment by mcuee** [comment]
How about this?
When you Use HIDAPI for the first stage. Close the device. Use libusb for the next stage.

**Comment by nxpfrankli** [comment]
Thank you for serial number trick. But ROM can't change now. 

About close and open at libusb,  there are problem that. 

Assume connect two difference boards A and B connect to PC with the same chip.  That's our normal use case for test board farm.  

Assume board A connect usb port 1:12, board B connect usb port 1:13.

I can use  
          uuu -m 1:12  image_A. 
          uuu -m 1:13  image_B. 

the uuu will handle phase 1 and phase 2 automatically. 

if HID part switch into HIDAPI,  HIDAPI have not API to get usb port information.

**Comment by mcuee** [comment]
HIDAPI has the API to get HID path. You can ask in the HIDAPI github side to see how to best sort out your issue. 

HIDAPI github:
https://github.com/libusb/hidapi/issues

**Comment by mcuee** [comment]
And maybe you want to ask in the libusb mailing list as well and people may have more ideas in the libusb mailing list.

**Comment by nxpfrankli** [comment]
Is it possible that libusb return a kernel driver assigned device node path? like /dev/hidraw<n> or /dev/ttyUSB<n>

**Comment by Youw** [comment]
`/dev/hidraw` is a kernel assigned path for **_hidraw_**-driver devices. libusb isn't using it. I may not even be presen in the kernel, and libusb would still work.

**Comment by mcuee** [comment]
I am going to close this as this is not an issue for libusb but rather a question. You can use libusb mailing list for further discussion.
