### ISSUE TITLE
Crash in usbi_signal_transfer_completion

### ISSUE THREAD

**Issue by bclay1297** [libusb/libusb#886]
I am attempting to get a USB to DMX controller working with the following code.  Every time I get to the libusb_claim_interface call the program crashes in usbi_signal_transfer_completion which as you can see is not in the code below.  I assume this is invoked by a callback somewhere.  I pulled the basic code example from PiOpenLighting.  I stepped though the code in Visual Studio 2017 and everything seems ok until it crashes with an error "Exception thrown: read access violation.
dev_handle->dev was 0x8BAEA8B4800."

	r = libusb_init(NULL);

		libusb_device **device_list;
		size_t device_count = libusb_get_device_list(NULL, &device_list);

		int index = 4;  // index of the USB device

		libusb_device *usb_device = device_list[index];
		libusb_open(usb_device, &mUsbDevHandle);
		struct libusb_device_descriptor device_descriptor;
		libusb_get_device_descriptor(usb_device, &device_descriptor);

		unsigned int  debug_level = 0;  

		libusb_set_debug(NULL, debug_level);
//		libusb_set_configuration(mUsbDevHandle, 1); // set device to be I/O

		r = libusb_claim_interface(mUsbDevHandle, 0);

Any thoughts would be greatly appreciated.
Bruce

**Comment by mcuee** [comment]
You need to mention more about the device (USB descriptors) and driver used (winusb or others). Then please generate the debug log by setting LIBUSB_DEBUG=4 and then run your program.

**Comment by bclay1297** [comment]
I was using libusbK  but finally got winusb to work.  Not that I got my
code to work just that it stopped crashing.  I am pretty much shooting in
the dark here.  I self singed the uDMX drive that came with the USB to DMX
adapter (USB\VID_16C0&PID_05DC).  Actually it seems I am still using the
libusbK.dll.  I thought I had removed it but windows apparently reinstalled
it because it is showing up under driver details along with winusb.sys,
WdfCoInstaller01009.dll and WinUSBCoInstaller2.dll

So at this point it looks like I can initialize but the write always
fails.  I am trying to send just a few bytes to the DMX controller.  Is
bulk transfer the only option for writing to the device?

The device in question is  vid=16C0 pid=05DC

Source code and debug dump follow per you request


The initialize code contains

r = libusb_init(NULL);

unsigned int  debug_level = 4;  //LIBUSB_DEFAULT_DEBUG_LEVEL;

libusb_set_debug(NULL, debug_level);

mUsbDevHandle = libusb_open_device_with_vid_pid(NULL, vid, pid);

std::string manufacturer;
std::string product;
std::string serial;

if (mUsbDevHandle != NULL)
{
libusb_device **device_list;
size_t device_count = libusb_get_device_list(NULL, &device_list);

int index = 4;
libusb_device *usb_device = device_list[index];

// libusb_open(usb_device, &mUsbDevHandle);

struct libusb_device_descriptor device_descriptor;
libusb_get_device_descriptor(usb_device, &device_descriptor);


libusb_set_configuration(mUsbDevHandle, 1); // set device to be I/O

r = libusb_claim_interface(mUsbDevHandle, 0);
// if (r < 0)
{
// fprintf(stderr, "usb_claim_interface error %d\n", r);
// return 2;
}
// printf("Interface claimed\n");


endPoint = active_config(usb_device, mUsbDevHandle);

status = 0;
}

return(status);

and the write code contains

int UsbWrapper::UsbWrite(unsigned int numBytes, unsigned char *dataBuf)
{
int n, ret;

memcpy(mTransferBuf, dataBuf, numBytes);

//write transfer
//probably unsafe to use n twice...
ret = libusb_bulk_transfer(mUsbDevHandle, USB_ENDPOINT_OUT, mTransferBuf,
numBytes,
&n, 0);

//Error handling
switch (ret)
{
case 0:
printf("send %d bytes to device\n", n);
return 0;
case LIBUSB_ERROR_TIMEOUT:
printf("ERROR in bulk write: %d Timeout\n", ret);
break;
case LIBUSB_ERROR_PIPE:
printf("ERROR in bulk write: %d Pipe\n", ret);
break;
case LIBUSB_ERROR_OVERFLOW:
printf("ERROR in bulk write: %d Overflow\n", ret);
break;
case LIBUSB_ERROR_NO_DEVICE:
printf("ERROR in bulk write: %d No Device\n", ret);
break;
default:
printf("ERROR in bulk write: %d\n", ret);
break;

}
return -1;

}

The dump contains

[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 2.814739] [00004fc8] libusb: debug [windows_iocp_thread] I/O completion
thread started
[ 2.815252] [00005ae8] libusb: debug [libusb_get_device_list]
[ 2.831619] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [72]
[ 2.831889] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [73]
[ 2.832103] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [74]
[ 2.832394] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [75]
[ 2.832850] [00005ae8] libusb: debug [get_api_type] driver(s): S3XXx64
[ 2.833030] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [A]
[ 2.833650] [00005ae8] libusb: debug [get_api_type] driver(s): WinUSB
[ 2.833819] [00005ae8] libusb: debug [get_api_type] matched driver name
against WinUSB
[ 2.833914] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [20]
[ 2.834855] [00005ae8] libusb: debug [get_api_type] driver(s): usbccgp
[ 2.835009] [00005ae8] libusb: debug [get_api_type] matched driver name
against Composite API
[ 2.835153] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [5C]
[ 2.836150] [00005ae8] libusb: debug [get_api_type] driver(s): usbccgp
[ 2.836568] [00005ae8] libusb: debug [get_api_type] matched driver name
against Composite API
[ 2.837157] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [5D]
[ 2.837984] [00005ae8] libusb: debug [get_api_type] driver(s): USBSTOR
[ 2.838435] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [5E]
[ 2.839573] [00005ae8] libusb: debug [enumerate_hcd_root_hub] assigning HCD
'PCI\VEN_1B21&DEV_2142&SUBSYS_50071458&REV_00\4&302206E1&0&00E4' bus number
1
[ 2.839837] [00005ae8] libusb: debug [enumerate_hcd_root_hub] assigning HCD
'PCI\VEN_1912&DEV_0015&SUBSYS_00000000&REV_02\4&32E30212&0&00DB' bus number
2
[ 2.840205] [00005ae8] libusb: debug [enumerate_hcd_root_hub] assigning HCD
'PCI\VEN_8086&DEV_A2AF&SUBSYS_50071458&REV_00\3&11583659&0&A0' bus number 3
[ 2.841619] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [5E]
[ 2.841732] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.842056] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 44 bytes)
[ 2.842438] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 2, depth:
1, port: 18): 'USB\VID_1058&PID_2627\5758563245373046305A3538'
[ 2.842877] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [A]
[ 2.843168] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.843488] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 93 bytes)
[ 2.843875] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 3, depth:
2, port: 2): 'USB\VID_04E6&PID_5116\53311717707644'
[ 2.844366] [00005ae8] libusb: debug [init_root_hub] root hub
'USB\ROOT_HUB30\5&2D7DCE09&0&0' reports 4 ports
[ 2.844601] [00005ae8] libusb: debug [init_device] (bus: 1, addr: 0, depth:
0, port: 0): 'USB\ROOT_HUB30\5&2D7DCE09&0&0'
[ 2.845000] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [5D]
[ 2.845319] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.845635] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 84 bytes)
[ 2.846502] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 5, depth:
2, port: 4): 'USB\VID_1532&PID_0040\6&27620D36&0&4'
[ 2.848808] [00005ae8] libusb: debug [winusb_get_device_list] extra GUID:
{4305F882-1D4B-4458-92A5-E857589D66F3}
[ 2.849054] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [20]
[ 2.849550] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.850254] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 18 bytes)
[ 2.850790] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 8, depth:
1, port: 3): 'USB\VID_16C0&PID_05DC\ILLUTZMINATOR001'
[ 2.851381] [00005ae8] libusb: debug [init_root_hub] root hub
'USB\ROOT_HUB30\5&D7D1E7&0&0' reports 4 ports
[ 2.851577] [00005ae8] libusb: debug [init_device] (bus: 2, addr: 0, depth:
0, port: 0): 'USB\ROOT_HUB30\5&D7D1E7&0&0'
[ 2.852076] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [72]
[ 2.852318] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.852636] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 25 bytes)
[ 2.853018] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 1, depth:
1, port: 9): 'USB\VID_05E3&PID_0608\5&2108AD5D&0&9'
[ 2.853615] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [5C]
[ 2.853746] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.854090] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 59 bytes)
[ 2.854476] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 4, depth:
2, port: 3): 'USB\VID_06A3&PID_8020\6&27620D36&0&3'
[ 2.854956] [00005ae8] libusb: debug [init_root_hub] root hub
'USB\ROOT_HUB30\4&92B3C53&0&0' reports 26 ports
[ 2.855234] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 0, depth:
0, port: 0): 'USB\ROOT_HUB30\4&92B3C53&0&0'
[ 2.855548] [00005ae8] libusb: debug [discovered_devs_append] need to
increase capacity
[ 2.856355] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.856418] [00005ae8] libusb: debug [set_composite_interface] interface[0]
=
\\?\HID#VID_1532&PID_0040&MI_00#8&185D61C3&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 2.856866] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.857117] [00005ae8] libusb: debug [set_composite_interface] interface[1]
=
\\?\HID#VID_1532&PID_0040&MI_01&COL03#8&99D57E&0&0002#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 2.857558] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.857831] [00005ae8] libusb: debug [set_composite_interface] interface[1]
=
\\?\HID#VID_06A3&PID_8020&MI_01&COL02#8&19BD205A&0&0001#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 2.858260] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.858535] [00005ae8] libusb: debug [set_composite_interface] interface[2]
=
\\?\HID#VID_1532&PID_0040&MI_02#8&28BE8EAB&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}\KBD
[ 2.858952] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.859242] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL04\8&99D57E&0&0003
[ 2.859652] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.859949] [00005ae8] libusb: debug [set_composite_interface] interface[0]
=
\\?\HID#VID_06A3&PID_8020&MI_00#8&1F99415&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}\KBD
[ 2.860372] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.860676] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_06A3&PID_8020&MI_01&COL01\8&19BD205A&0&0000
[ 2.861102] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.861393] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_06A3&PID_8020&MI_01&COL03\8&19BD205A&0&0002
[ 2.862019] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.864125] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL02\8&99D57E&0&0001
[ 2.864558] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.864843] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL05\8&99D57E&0&0004
[ 2.865290] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.865586] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL01\8&99D57E&0&0000
[ 2.866820] [00005ae8] libusb: debug [get_api_type] driver(s): WinUSB
[ 2.866938] [00005ae8] libusb: debug [get_api_type] matched driver name
against WinUSB
[ 2.868285] [00005ae8] libusb: debug [libusb_get_device_descriptor]
[ 2.868362] [00005ae8] libusb: debug [libusb_get_device_descriptor]
[ 2.868725] [00005ae8] libusb: debug [libusb_get_device_descriptor]
[ 2.869058] [00005ae8] libusb: debug [libusb_get_device_descriptor]
[ 2.869406] [00005ae8] libusb: debug [libusb_get_device_descriptor]
[ 2.869738] [00005ae8] libusb: debug [libusb_open] open 3.8
[ 2.870120] [00005ae8] libusb: debug [libusb_unref_device] destroy device
3.2
[ 2.870465] [00005ae8] libusb: debug [libusb_unref_device] destroy device
3.3
[ 2.870817] [00005ae8] libusb: debug [libusb_unref_device] destroy device
1.0
[ 2.871162] [00005ae8] libusb: debug [libusb_unref_device] destroy device
3.5
[ 2.871508] [00005ae8] libusb: debug [libusb_unref_device] destroy device
2.0
[ 2.871852] [00005ae8] libusb: debug [libusb_unref_device] destroy device
3.4
[ 2.872191] [00005ae8] libusb: debug [libusb_unref_device] destroy device
3.1
[ 2.872537] [00005ae8] libusb: debug [libusb_get_device_list]
[ 2.880814] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [72]
[ 2.880948] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [73]
[ 2.881307] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [74]
[ 2.881644] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [75]
[ 2.882143] [00005ae8] libusb: debug [get_api_type] driver(s): S3XXx64
[ 2.882361] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [A]
[ 2.883023] [00005ae8] libusb: debug [get_api_type] driver(s): WinUSB
[ 2.883461] [00005ae8] libusb: debug [get_api_type] matched driver name
against WinUSB
[ 2.883957] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [20]
[ 2.884871] [00005ae8] libusb: debug [get_api_type] driver(s): usbccgp
[ 2.885376] [00005ae8] libusb: debug [get_api_type] matched driver name
against Composite API
[ 2.885728] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [5C]
[ 2.886375] [00005ae8] libusb: debug [get_api_type] driver(s): usbccgp
[ 2.886621] [00005ae8] libusb: debug [get_api_type] matched driver name
against Composite API
[ 2.886978] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [5D]
[ 2.887907] [00005ae8] libusb: debug [get_api_type] driver(s): USBSTOR
[ 2.888226] [00005ae8] libusb: debug [winusb_get_device_list] allocating
new device for session [5E]
[ 2.889252] [00005ae8] libusb: debug [enumerate_hcd_root_hub] assigning HCD
'PCI\VEN_1B21&DEV_2142&SUBSYS_50071458&REV_00\4&302206E1&0&00E4' bus number
1
[ 2.889907] [00005ae8] libusb: debug [enumerate_hcd_root_hub] assigning HCD
'PCI\VEN_1912&DEV_0015&SUBSYS_00000000&REV_02\4&32E30212&0&00DB' bus number
2
[ 2.891865] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [5E]
[ 2.891984] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.892677] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 44 bytes)
[ 2.893453] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 2, depth:
1, port: 18): 'USB\VID_1058&PID_2627\5758563245373046305A3538'
[ 2.894344] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [A]
[ 2.896497] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.896805] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 93 bytes)
[ 2.897197] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 3, depth:
2, port: 2): 'USB\VID_04E6&PID_5116\53311717707644'
[ 2.897723] [00005ae8] libusb: debug [init_root_hub] root hub
'USB\ROOT_HUB30\5&2D7DCE09&0&0' reports 4 ports
[ 2.897937] [00005ae8] libusb: debug [init_device] (bus: 1, addr: 0, depth:
0, port: 0): 'USB\ROOT_HUB30\5&2D7DCE09&0&0'
[ 2.898475] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [5D]
[ 2.898834] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.899764] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 84 bytes)
[ 2.900564] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 5, depth:
2, port: 4): 'USB\VID_1532&PID_0040\6&27620D36&0&4'
[ 2.901704] [00005ae8] libusb: debug [winusb_get_device_list] extra GUID:
{4305F882-1D4B-4458-92A5-E857589D66F3}
[ 2.901954] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [20]
[ 2.902441] [00005ae8] libusb: debug [init_root_hub] root hub
'USB\ROOT_HUB30\5&D7D1E7&0&0' reports 4 ports
[ 2.902743] [00005ae8] libusb: debug [init_device] (bus: 2, addr: 0, depth:
0, port: 0): 'USB\ROOT_HUB30\5&D7D1E7&0&0'
[ 2.903197] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [72]
[ 2.903477] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.903798] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 25 bytes)
[ 2.904226] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 1, depth:
1, port: 9): 'USB\VID_05E3&PID_0608\5&2108AD5D&0&9'
[ 2.904818] [00005ae8] libusb: debug [winusb_get_device_list] found
existing device for session [5C]
[ 2.904990] [00005ae8] libusb: debug [init_device] found 1 configurations
(current config: 1)
[ 2.905339] [00005ae8] libusb: debug [cache_config_descriptors] cached
config descriptor 0 (bConfigurationValue=1, 59 bytes)
[ 2.905779] [00005ae8] libusb: debug [init_device] (bus: 3, addr: 4, depth:
2, port: 3): 'USB\VID_06A3&PID_8020\6&27620D36&0&3'
[ 2.906253] [00005ae8] libusb: debug [discovered_devs_append] need to
increase capacity
[ 2.906854] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.906909] [00005ae8] libusb: debug [set_composite_interface] interface[0]
=
\\?\HID#VID_1532&PID_0040&MI_00#8&185D61C3&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 2.907306] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.907539] [00005ae8] libusb: debug [set_composite_interface] interface[1]
=
\\?\HID#VID_1532&PID_0040&MI_01&COL03#8&99D57E&0&0002#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 2.907908] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.908157] [00005ae8] libusb: debug [set_composite_interface] interface[1]
=
\\?\HID#VID_06A3&PID_8020&MI_01&COL02#8&19BD205A&0&0001#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 2.908538] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.908867] [00005ae8] libusb: debug [set_composite_interface] interface[2]
=
\\?\HID#VID_1532&PID_0040&MI_02#8&28BE8EAB&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}\KBD
[ 2.910583] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.910835] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL04\8&99D57E&0&0003
[ 2.911216] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.911488] [00005ae8] libusb: debug [set_composite_interface] interface[0]
=
\\?\HID#VID_06A3&PID_8020&MI_00#8&1F99415&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}\KBD
[ 2.911857] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.912117] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_06A3&PID_8020&MI_01&COL01\8&19BD205A&0&0000
[ 2.912482] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5C]:
[ 2.912740] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_06A3&PID_8020&MI_01&COL03\8&19BD205A&0&0002
[ 2.913119] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.913369] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL02\8&99D57E&0&0001
[ 2.913733] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.913982] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL05\8&99D57E&0&0004
[ 2.914355] [00005ae8] libusb: debug [winusb_get_device_list] setting
composite interface for [5D]:
[ 2.914617] [00005ae8] libusb: debug [set_composite_interface] interface[1]
already set - ignoring HID collection:
HID\VID_1532&PID_0040&MI_01&COL01\8&99D57E&0&0000
[ 2.915577] [00005ae8] libusb: debug [get_api_type] driver(s): WinUSB
[ 2.915664] [00005ae8] libusb: debug [get_api_type] matched driver name
against WinUSB
[10.992531] [00005ae8] libusb: debug [libusb_get_device_descriptor]
[13.430440] [00005ae8] libusb: debug [libusb_set_configuration]
configuration 1
[13.430799] [00005ae8] libusb: debug [libusb_alloc_transfer] transfer
000001DFE721E3C8
[13.435342] [00005ae8] libusb: debug [libusb_submit_transfer] transfer
000001DFE721E3C8
[13.437639] [00005ae8] libusb: debug [add_to_flying_list] arm timer for
timeout in 1000ms (first in line)
[13.440168] [00005ae8] libusb: debug [libusb_claim_interface] interface 0
[13.441705] [00005ae8] libusb: debug [winusbx_claim_interface] claimed
interface 0
[13.443102] [00005ae8] libusb: debug [windows_assign_endpoints] no
endpoints found for interface 0
[13.444277] [00005ae8] libusb: debug [auto_claim] auto-claimed interface 0
for control request
[13.445434] [00005ae8] libusb: debug [winusbx_submit_control_transfer] will
use interface 0
[13.446597] [00005ae8] libusb: debug [windows_force_sync_completion]
transfer 000001DFE721E3C8, length 0
[13.447807] [00005ae8] libusb: debug
[libusb_handle_events_timeout_completed] doing our own event handling
[13.449239] [00005ae8] libusb: debug [handle_events] event sources
modified, reallocating event data
[13.450654] [00005ae8] libusb: debug [usbi_wait_for_events]
WaitForMultipleObjects() for 2 HANDLEs with timeout in 60000ms
[13.452627] [00005ae8] libusb: debug [usbi_wait_for_events]
WaitForMultipleObjects() returned 0
[13.454784] [00005ae8] libusb: debug [handle_event_trigger] event triggered
[13.459652] [00005ae8] libusb: debug [windows_handle_transfer_completion]
handling transfer 000001DFE721E3C8 completion with errcode 0, length 0
[13.460478] [00005ae8] libusb: debug [libusb_release_interface] interface 0
[13.461099] [00005ae8] libusb: debug [auto_release] auto-released interface
0
[13.461732] [00005ae8] libusb: debug [arm_timer_for_next_timeout] no
timeouts, disarming timer
[13.462361] [00005ae8] libusb: debug [usbi_handle_transfer_completion]
transfer 000001DFE721E3C8 has callback 00007FF679AD40C0
[13.463046] [00005ae8] libusb: debug [sync_transfer_cb] actual_length=0
[13.463654] [00005ae8] libusb: debug [libusb_free_transfer] transfer
000001DFE721E3C8
[15.775144] [00005ae8] libusb: debug [libusb_claim_interface] interface 0
[15.775955] [00005ae8] libusb: debug [winusbx_claim_interface] claimed
interface 0
[15.779122] [00005ae8] libusb: debug [windows_assign_endpoints] no
endpoints found for interface 0

Interface Descriptors:
        Number of Interfaces: 1
        Length: 9
        Desc_Type: 2
        Config_index: 0
        Total length: 18
        Configuration Value: 1
        Configuration Attributes: 128
        MaxPower(mA): 250

EndPoint Descriptors:
        Size of EndPoint Descriptor: 255
        Type of Descriptor: 255
        Endpoint Address: 0x0ff
        Maximum Packet Size: ffff
        Attributes applied to Endpoint: 255
        Interval for Polling for data Tranfer: 255
[128.945264] [00005ae8] libusb: debug [libusb_alloc_transfer] transfer
000001DFE4206AF8
[128.945698] [00005ae8] libusb: debug [libusb_submit_transfer] transfer
000001DFE4206AF8
[128.947362] [00005ae8] libusb: error [winusbx_submit_bulk_transfer] unable
to match endpoint to an open interface - cancelling transfer
[128.949065] [00005ae8] libusb: debug [libusb_free_transfer] transfer
000001DFE4206AF8
ERROR in bulk write: -5

**Comment by mcuee** [comment]
[128.947362] [00005ae8] libusb: error [winusbx_submit_bulk_transfer] unable
to match endpoint to an open interface - cancelling transfer

You need to understand the communication protocol in order to use libusb to communicate to your device. Apparently you are not writing to the correct endpoint in this case.

**Comment by bclay1297** [comment]
How can we determine the correct endpoint?  The debug log showed and
endpoint address of 0xff.  I tried that even though it does not look valid
but it did not help

**Comment by mcuee** [comment]
You have to know which USB ENDPOINT in order to use libusb to talk to the device. If you do not know, then nobody can help you.

If you do not know, then you need to spend the efforts to carry out reverse engineering.

First thing is to get to know the USB descriptors. You can use USBView.
https://ftdichip.com/utilities/

**Comment by mcuee** [comment]
I will close this issue. This github is more for problem reporting and not for technical support. You can ask in libusb mailing list for further support.
