### ISSUE TITLE
cataline 10.15 not support

### ISSUE THREAD

**Issue by developerss** [libusb/libusb#888]
there is no way to install this plugin in cataline 10.15 
it works in 10.13 last /
is there a way i can install cataline 10.15 libusb plugin .,
i tried all ruby and bin bash all failed please show me a new way if possible to install it on 10.15

**Comment by mcuee** [comment]
Which plugin? You can use homebrew to install libusb under macOS.

**Comment by mcuee** [comment]
Homebrew lbusb
https://formulae.brew.sh/formula/libusb#default

**Comment by mcuee** [comment]
If you are talking about Ruby libusb bindings, that belongs to different project.

**Comment by developerss** [comment]
thank you for your suggestion  the home brew not run at cataline so without home brew i can install libusb ?>

**Comment by mcuee** [comment]
I do not understand what you say about Homebrew not run under macOS Catalina 10.15. It works fine. 

If you do not want to use Homebrew, you can try the XCode project.

Anyway, github is for issue report, not for technical support. Please use libusb mailing list for further support.

**Comment by developerss** [comment]
home brew not working in Caroline
