### ISSUE TITLE
Qt Creator Failed to use libusb

### ISSUE THREAD

**Issue by geek-slt** [libusb/libusb#894]
Version： QT 5.12  Qt Creator 4.13.1    window10 x64
translater：MSVC2017 64bit
Question: 
I used Qt Creator to create a new project and then downloaded and decompressed libusb-1.0.24.7z. But when I used libusb in the project, the problem appeared. No matter how I tried, I couldn’t call the functions in libusb normally. I was on the StackOverflow forum. The query found that many people encountered the same problem as me, but none of them had a good solution. Can you help me?

**Comment by mcuee** [comment]
Please use libusb mailing list for question like this. Or better ask in QT related forum. This is not a libusb issue.
