### ISSUE TITLE
windows_winusb not re-enumerating devices while ClassGUID has changes

### ISSUE THREAD

**Issue by CraigHutchinson** [libusb/libusb#897]
The Dfu-Util project causes a reset of a device from DFU-Runtime to DFU-Mode. On windows the WinUSB device `libusb_get_device_list()` backend  re-uses the existing device reporting "found existing device for session [62]" descriptors which causes a bug in that changed/updated device descriptors are not accessible via the LibUsb api: [https://sourceforge.net/p/dfu-util/tickets/110](https://sourceforge.net/p/dfu-util/tickets/110)

# Current WinUSB implements only the following checks
1.  `DevInst`  is used to match session_id
https://github.com/libusb/libusb/blob/bda2344f5e7d460decd3968492faa7a5fb2797cd/libusb/os/windows_winusb.c#L1672
2. `priv->dev_id` path is used to match the device
https://github.com/libusb/libusb/blob/bda2344f5e7d460decd3968492faa7a5fb2797cd/libusb/os/windows_winusb.c#L1691

# The issue
When the device is re-enumerated it is the `ClassGuid` that actually changes and should also be checked

I am happy to try and make a patch if somebody can help provide some advice or best approach as my assumption here may not be correct with limited knowledge i.e:
-  I am not sure if the `ClassGuid` is cached in priv for the device at present to perform the extra comparison in the same manner as at L1691 already?

**Comment by tormodvolden** [comment]
dfu-util bug link should be: https://sourceforge.net/p/dfu-util/tickets/110/

**Comment by CraigHutchinson** [comment]
This appear to possible be a previously reported issue that was unresolved: https://github.com/libusb/libusb/issues/295

**Comment by CraigHutchinson** [comment]
In the case of the issue reported here calling `libusb_exit(ctx)` followed by `libusb_init(ctx)` to instantiate a new context is a workaround

**Comment by mcuee** [comment]
IMHO the ultimate fix will be #86 Windows hotplug support. Before that, it may be difficult to fix.

**Comment by tormodvolden** [comment]
Craig suggested comparing the ClassGuid. Here is a compile-tested patch, adding ClassGuid to the cached priv and comparing it. Maybe Craig can test it and let us know.

[0001-winusb-Compare-ClassGuid-in-check-for-existing-devic.patch.txt](https://github.com/libusb/libusb/files/6208291/0001-winusb-Compare-ClassGuid-in-check-for-existing-devic.patch.txt)

**Comment by CraigHutchinson** [comment]
I will review the patch soon and 

> Craig suggested comparing the ClassGuid. Here is a compile-tested patch, adding ClassGuid to the cached priv and comparing it. Maybe Craig can test it and let us know.
> 
> [0001-winusb-Compare-ClassGuid-in-check-for-existing-devic.patch.txt](https://github.com/libusb/libusb/files/6208291/0001-winusb-Compare-ClassGuid-in-check-for-existing-devic.patch.txt)

I will check this asap :)

**Comment by CraigHutchinson** [comment]
I can confirm this change DID fix the issue :D

 I am not sure this is a 'generic' fix for all occurrences of issues such as this as I m not 100% what the ClassGUID represents here i.e. Does it work because just because in this case the devices is switching between a Composite during RT mode and a different type in DFU mode.

**Comment by CraigHutchinson** [comment]
I have adjusted the title of the issue to be more specific. That is that re-enumeration isn't happening when the ClassGuid of my device was changed.

It is possible there are other, currently unknown issues for re-enumeration on windows that may be addressed in separate Issue topics as they are discovered.

The proposed patch @tormodvolden works and I made a pull-request with the respective code adjustments which directly address this issue.

**Comment by tormodvolden** [comment]
Thanks for the testing. Did you do any changes to my (git-formatted) patch other than splitting it up and adding a comment? Otherwise I see a slight attribution issue here.

For the GUID, I /think/ it will change if the triplet vid/pid/bcdDevice changes and that would already make the difference in your case. Maybe it is also changes with interface changes.

**Comment by CraigHutchinson** [comment]
So true, comment was only addition I made.

please if you make a pull request with your changes it will be correctly attributed and I will close mine. Cheers.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by tormodvolden** [comment]
From looking into where the ClassGuid comes from, my theory is as follows: The ClassGuid is assigned based on a matching driver or one of the predefined classes. The matching might involve looking at the interface descriptors. Windows will treat a device as new and re-evaluate the ClassGuid assignment if vid/pid/bcdDevice has changed. It would be possible that the ClassGuid stays the same even if some descriptors have changed, but checking for ClassGuid is a good improvement.

**Comment by tormodvolden** [comment]
@CraigHutchinson Maybe you can close your pull request to avoid confusion, thanks.

**Comment by mcuee** [comment]
I have closed #899 and refer to #900.

**Comment by CraigHutchinson** [comment]
@mcuee Thanks for that, got it sorted before I started back at work :)

**Comment by CraigHutchinson** [comment]
The associated change #900 rectifies the reported issue.

**Comment by mcuee** [comment]
I will leave this open until #900 gets merged.

**Comment by mcuee** [comment]
#900 has been merged.
