### ISSUE TITLE
error instalation usb_modeswitch

### ISSUE THREAD

**Issue by mrrodriguez1988** [libusb/libusb#939]
The installation of libusb completes ok, but when installing usb_modeswitch it does not find libusb-1.0.pc

![1](https://user-images.githubusercontent.com/86268462/122834735-1fda8a80-d2bd-11eb-965d-ac3d924a84e7.PNG)
![2](https://user-images.githubusercontent.com/86268462/122834752-2406a800-d2bd-11eb-8380-8a1231ae32e8.PNG)

Please if someone can help me

**Comment by LudovicRousseau** [comment]
The solution is given in the error message:

> Package libusb-1.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libusb-1.0.pc'
> to the PKG_CONFIG_PATH environment variable

Set `PKG_CONFIG_PATH` to `/usr/local/lib/pkgconfig`
