### ISSUE TITLE
Calling the libusb_claim_interface function returns -6 LIBUSB_ERROR_BUSY...

### ISSUE THREAD

**Issue by yyang2021** [libusb/libusb#940]
How do I want to stop the BUSY state, is there an available interface to call?

**Comment by mcuee** [comment]
You need to provide more info. What is the OS and what is the device?

If under Linux, you need to detach the kernel driver first.

**Comment by mcuee** [comment]
I will close this for now. Please read the FAQ first before asking questions. And please use libusb-devel mailing list for questions.

But if you think the issue is with libusb, then you can reopen this issue again and post the details.
