### ISSUE TITLE
Build with errors in Visual Studio 2015 (undefined M_PI)

### ISSUE THREAD

**Issue by mbk74** [libusb/libusb#95]
Hi guys
Please fix examples/protonect/CMakeLists.txt. In 177 replace with this
ADD_DEFINITIONS(-DRESOURCES_INC -D_USE_MATH_DEFINES)

**_USE_MATH_DEFINES** - should be defined in project

**Comment by mcuee** [comment]
There is not such thing in libusb. You submit the ticker to the wrong
project.
