### ISSUE TITLE
Running on bare metal

### ISSUE THREAD

**Issue by lonnietc** [libusb/libusb#968]
Hello,

I am interested in a USB lib with minimal clib dependencies so that it might be adaptable to a bare metal project which is working to port over the MUSL Clib standard libraries.

Would libusb be suitable for such an effort or is there another library that might be a better choice to get started with?

Thanks

**Comment by mcuee** [comment]
No. libusb needs to run on OS like Linux or Windows, not for bare metal.

**Comment by mcuee** [comment]
For bare metal, usually the silicon chip vendor will provide the USB stack, in your case, I think you want to use the USB Host stack from the silicon chip vendor as the start.

For the embedded side, embedded Linux is the best bet for libusb, and you can see it is based on the existence of usbfs (using usbfs ioctls).
https://github.com/libusb/libusb/blob/master/libusb/os/linux_usbfs.c

**Comment by mcuee** [comment]
Please also take note libusb is a host side library, it does not work on the device side.

**Comment by lonnietc** [comment]
Thanks again as I am looking for a host side library with minimal dependencies as well as small size so this "might" be the one that I have been seeking.
