### ISSUE TITLE
mac os x 10.10 libusb_claim_interface return -3

### ISSUE THREAD

**Issue by xiaojiangDraug** [libusb/libusb#97]
I was troubled by this issue. I tried call libusb_detach_kernel_driver function, but is not use. Give me some suggestions!

**Comment by hjelmn** [comment]
You cannot detach kernel drivers in os x. Depending on the device you can use a codeless kext to prevent the kernel driver from claiming the device.

**Comment by xiaojiangDraug** [comment]
thank you
