### ISSUE TITLE
Android and linux return extra is different

### ISSUE THREAD

**Issue by zhouconglong** [libusb/libusb#991]
hello, we use the libusb of android and libuvc .  we find them different.
The Android return:
descriptor_subtype 5
block5: 32 
block6: 3 
block7: 208 
block8: 2 

The Linux return:
descriptor_subtype 5
block5: 32 
block6: 3 
block7: 0 
block8: 4

**Comment by mcuee** [comment]
You need to provide extra info. What is the device and what is the=is "block" thingy (eg: post your code)? Are you using the same libusb version under Android and Linux?

**Comment by mcuee** [comment]
If you use libuvc, you can see if you can post the output of libuvc example program. 
Eg: https://github.com/libuvc/libuvc/issues/188
