### ISSUE TITLE
libusb_get_device_list return 0

### ISSUE THREAD

**Issue by zhouconglong** [libusb/libusb#992]
Hi，
I use the libusb of Android 10, I have get the permission of android.
libusb_set_option is ok.
libusb_set_option(ctx, LIBUSB_OPTION_WEAK_AUTHORITY, NULL);
libusb_init is ok.
libusb_init(&ctx);
But libusb_get_device_list return 0.

**Comment by mcuee** [comment]
Is possible for you to post the debug log? What is your platform? Do you have root access or not?

Are you using this one? https://github.com/libusb/libusb/pull/830
Or are you using at least this one as the starting point? https://github.com/libusb/libusb/pull/830

**Comment by zhouconglong** [comment]
Thanks
