### ISSUE TITLE
Android: libusb: error [submit_iso_transfer] submiturb failed, errno=12

### ISSUE THREAD

**Issue by zhouconglong** [libusb/libusb#993]
Hi, I use this he libuvc in android, when I start_streaming 
retrun:
libusb: error [submit_iso_transfer] submiturb failed, errno=12

**Comment by mcuee** [comment]
Again you need to provide more details. What is the Android system? What is the uvc devices? What is the libusb version used? Do you see issues under normal Linux host (not Android)?

**Comment by mcuee** [comment]
https://github.com/libusb/libusb/wiki/Android
Currently there are multiple issues of libusb under Android. But your issue may not may not be related. So you need to make sure your codes work under normal Linux first before trying Android.

**Comment by mcuee** [comment]
@zhouconglong It will be good to tell us whether you have sorted out the issue or not. If you have sorted out the issue, it will be great that you can share what you have done to sort out the issue.
